### ISSUE TITLE
Audit logging: Provide a comment field for some pattern/flag changes

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/pattern-directory#105]
From #57:

> When a moderator changes a pattern, they should include a reason so that it's easier to understand later why something changed. So ideally, when a quick action or bulk edit is modifying patterns, it should trigger a field to appear in a modal or something where a comment about the change can be entered.

**Comment by coreymckrill** [comment]
~This could possibly be solved by using the [Revision Notes](https://wordpress.org/plugins/revision-notes/) plugin.~

**Comment by coreymckrill** [comment]
This functionality can be covered by the [Internal Notes plugin](https://github.com/WordPress/wporg-internal-notes). We just need to add post type support for `wporg-internal-notes` on both the pattern and flag post types and activate the plugin on the Pattern Directory site.

Triggering a modal when a post status changes would require some additional development, but the Internal Notes plugin uses a REST API endpoint, so it should be fairly straightforward to have a custom form in a modal that adds a new note.

**Comment by coreymckrill** [comment]
Well, post type support is now added, but when testing the Internal Notes plugin on the live Pattern Directory site, I was getting [this error](https://github.com/WordPress/wporg-internal-notes/issues/5). It causes the block editor to fatal upon load, so I've turned the Internal Notes plugin back off on the site until this can get resolved.

**Comment by ryelle** [comment]
I think the issue here is that @coreymckrill was not a user on the patterns site, so the `author` of that note is a `rest_user_invalid_id` error. I've re-enabled the Internal Notes plugin, and added more context to the issue in the Internal Notes repo.

**Comment by ryelle** [comment]
Now that the backend part of this is set up, we need a UI for moderators. When someone unlists a pattern, we could show a dialog (like the report modal on the front end). The open textarea will save to the internal notes, and the reason chosen can be used to show a message to the pattern author (see #371).

Front-end modal for reference:
<img width="488" alt="Screen Shot 2021-10-20 at 3 02 15 PM" src="https://user-images.githubusercontent.com/541093/138155410-eeb56c8f-56cb-4f8d-8afd-e6efea018972.png">

The reasons a pattern could be unlisted are…
- Rude, crude, or inappropriate
- Copyrighted or trademark issue
- Broken or unusable
- Author requested removal (maybe not? this would probably just be trashed)
