### ISSUE TITLE
Use of wp-themes.com style loading causes Chrome insecure warning

### ISSUE THREAD

**Issue by dd32** [WordPress/pattern-directory#109]
I'm not sure why, but the below warning is triggered in chrome once the page load starts to include resources from `wp-themes.com`.

<img width="330" alt="Screen Shot 2021-05-18 at 2 59 33 pm" src="https://user-images.githubusercontent.com/767313/118592697-b95bdb80-b7e9-11eb-8eff-499ad73cbb8c.png">

**Comment by ryelle** [comment]
I'm not seeing that in chrome, and the `wp-themes` resource is being loaded via `https`. Do you have `wp-themes.com` sandboxed, maybe?

**Comment by iandunn** [comment]
I also see them loading with `https`

**Comment by dd32** [comment]
I can't duplicate it anymore, but I recall the stylesheets were loaded over https without any issue..

I potentially did have `wp-themes.com` sandboxed at the time (It's no longer), or chrome had recalled the invalid cert for the domain or something similar.

@iandunn Any chance you had it sandboxed at some point in time to trigger it too?

**Comment by iandunn** [comment]
No, I've never worked on it, so it's not in my host file.

**Comment by ryelle** [comment]
@iandunn are you seeing the same insecure content warning?

**Comment by iandunn** [comment]
Er, sorry, I phrased that ambiguously before. I meant that I'm seeing the scripts load over `https`, so I'm not seeing any warnings.

**Comment by dd32** [comment]
I'm going to close this, and assume that it was my own fault :)
