### ISSUE TITLE
Pattern Grid: Blank page when no patterns are found

### ISSUE THREAD

**Issue by ryelle** [WordPress/pattern-directory#116]
When searching for patterns and none are found, it shows this sad empty state

<img width="1013" alt="Screen Shot 2021-05-27 at 10 40 29 AM" src="https://user-images.githubusercontent.com/541093/119846253-f86bea00-bed7-11eb-8239-d8ee72af71a3.png">

I'm assuming this one should give an error message, then either point the user to other categories, or show a set list of popular patterns…?

-------

A similar thing happens if someone tries to go "out of bounds", like to `/page/2000`, it also shows empty

<img width="1007" alt="Screen Shot 2021-05-27 at 10 40 54 AM" src="https://user-images.githubusercontent.com/541093/119846316-06216f80-bed8-11eb-91cb-bd3b8138ca61.png">

This should probably be a simple 404 page, or maybe redirect back to the first page of the query?

cc @shaunandrews

**Comment by shaunandrews** [comment]
For the empty search results maybe we can show some featured patterns:

![Empty Search](https://user-images.githubusercontent.com/191598/120842752-1e7a3580-c53b-11eb-9133-10bda514117f.png)

Here's a design for the 404 page:

![404](https://user-images.githubusercontent.com/191598/120842781-2934ca80-c53b-11eb-97d6-e43f1b6e10db.png)
