### ISSUE TITLE
Single Patterns: Live resizable preview

### ISSUE THREAD

**Issue by ryelle** [WordPress/pattern-directory#122]
Moving some conversation from #121 here so the framework there can be merged. This is all about the resizable preview.

First, which handle design should we use?

<img width="122" alt="Screen Shot 2021-06-04 at 2 59 32 PM" src="https://user-images.githubusercontent.com/541093/120850487-846bba80-c545-11eb-971c-4a4522a6e619.png"> <img width="122" alt="Screen Shot 2021-06-04 at 2 59 42 PM" src="https://user-images.githubusercontent.com/541093/120850490-859ce780-c545-11eb-974b-f38d0ea44fb2.png">

I made the assumption that we shouldn't show the size dropdown at small screens since there weren't size levels to resize to, but the handles are still available. But now I think we should drop the handles at the 480px breakpoint, keep all sizes in dropdown, and scale down the preview to fit the screen. So it will be tiny if someone on a 400px screen tries to preview at 1200 wide, but that's what they should expect.

@shaunandrews, does that match what you expect to happen on smaller screens?

**Comment by shaunandrews** [comment]
The white+blue circles was trying to take cues from the image blocks resize handle, but it was pointed out to me that this is different and should look different. Here's the latest designs that we should use:

Within the editor:

<img width="844" alt="image" src="https://user-images.githubusercontent.com/191598/120852700-8d11c000-c548-11eb-9ce2-515692d86d9c.png">

In the public detail page:

<img width="991" alt="image" src="https://user-images.githubusercontent.com/191598/120852784-ab77bb80-c548-11eb-9950-9e8d53b2cdfd.png">

> I made the assumption that we shouldn't show the size dropdown at small screens since there weren't size levels to resize to, but the handles are still available. But now I think we should drop the handles at the 480px breakpoint, keep all sizes in dropdown, and scale down the preview to fit the screen. So it will be tiny if someone on a 400px screen tries to preview at 1200 wide, but that's what they should expect.

I think this makes sense. At smaller viewports, can we default the preview to the smaller viewportWidth?

**Comment by ryelle** [comment]
> At smaller viewports, can we default the preview to the smaller viewportWidth?

yeah, it defaults to the width of the screen (960 max). I deployed the current selector, so you can try it out on https://wordpress.org/patterns/pattern/three-columns-of-text/

**Comment by ryelle** [comment]
Moving this to "later" - I can get the scale working width-wise, but then the height of the container is janky. Ideally it would automatically be the full height of the content, no scrollbar on the iframe.

**Comment by ryelle** [comment]
Closing this in favor of #380.
