### ISSUE TITLE
Pattern Submission: Trio of patterned header patterns

### ISSUE THREAD

**Issue by kjellr** [WordPress/pattern-directory#124]
I'd like to propose this trio of header patterns to help build up the pattern directory. Each one hinges on a really nice vintage pattern as their background. 

---

## Pattern Title

1. Header area with geometric pattern
2. Header area with hatch mark shapes
3. Header area with halftone pattern 

## Pattern Categories

Header

## Screenshots

1. 
<img width="1200" alt="Frame 1" src="https://user-images.githubusercontent.com/1202812/121058042-ea4a8300-c78d-11eb-8f27-704dab8352aa.png">

2.
<img width="1200" alt="Frame 2" src="https://user-images.githubusercontent.com/1202812/121058046-eae31980-c78d-11eb-9612-09ef5a0600a4.png">

3. 
<img width="1200" alt="Frame 5" src="https://user-images.githubusercontent.com/1202812/121058047-eb7bb000-c78d-11eb-827b-6ba98ec3b67f.png">

## Image Credits

Endleaves of Art. Taste. Beauty (1931) by anonymous. CC0
https://www.rawpixel.com/image/843244/blue-patterned-print

Art - Taste - Beauty, Slips of Feminine Elegance. CC0
https://www.rawpixel.com/image/843237/abstract-backdrop-design

Endleaves of Art. Taste. Beauty by Anonymous. CC0
https://www.rawpixel.com/image/843271/red-patterned-backgrpund

**Comment by kjellr** [comment]
If someone has a better idea of how to create these, let me know... here's my first attempt: 

https://gist.github.com/kjellr/0af4d8129957c78c07f52b53f71dbe7c

Looks decent on desktop: 

<img width="492" alt="Screen Shot 2021-06-08 at 3 20 26 PM" src="https://user-images.githubusercontent.com/1202812/121244653-1e48a580-c86d-11eb-8c8b-0139ae89a104.png">

... but falls apart completely on mobile: 

<img width="179" alt="Screen Shot 2021-06-08 at 3 20 45 PM" src="https://user-images.githubusercontent.com/1202812/121244663-23a5f000-c86d-11eb-8828-2f8def3e6495.png">

**Comment by beafialho** [comment]
I managed to get these looking good on mobile:

<img width="354" alt="Captura de ecrã 2021-06-09, às 17 59 28" src="https://user-images.githubusercontent.com/65220155/121397713-7f937600-c94c-11eb-87e7-b2f6cc4cd244.png">

Here's the markup for the trio: https://gist.github.com/beafialho/65353e0f7167e5a79190aec79bfb5295

**Comment by kjellr** [comment]
These are all added to the directory! Thanks everyone. 

https://wordpress.org/patterns/pattern/header-area-with-geometric-pattern/
https://wordpress.org/patterns/pattern/header-with-hatched-pattern/
https://wordpress.org/patterns/pattern/header-with-halftone-pattern/
