### ISSUE TITLE
Pattern Submission: Two "Link in bio" patterns

### ISSUE THREAD

**Issue by kjellr** [WordPress/pattern-directory#125]
I'd like to propose these two “Link in bio”-style block patterns. This is a feature many folks don’t realize they can do with WordPress, and Gutenberg makes it relatively easy. 

---

## Pattern Title

1. Button links with image background. 
2. Button links with gradient background. 

## Pattern Categories

Buttons

## Screenshots

1. 
![Frame 46](https://user-images.githubusercontent.com/1202812/121063754-b9218100-c794-11eb-9a13-87a0b48ac594.png)

2.
![Frame 53](https://user-images.githubusercontent.com/1202812/121063764-bb83db00-c794-11eb-89a9-f3d764fe1f53.png)

## Image Credits

Experimento de astigmatismo. CC0
https://www.flickr.com/photos/37667416@N04/4051848937

Wild Flower by Dristikon Dristikon. CC0
https://commons.wikimedia.org/w/index.php?curid=73791979

Total eclipse of the sun from the Trouvelot
astronomical drawings. CC0
https://www.rawpixel.com/image/283672/free-illustration-image-space-sun-astronomy

**Comment by kjellr** [comment]
Here's a first shot at implementing these: 

https://gist.github.com/kjellr/7079f81baf7e03dd88644e878e68449a

**Comment by melchoyce** [comment]
Tested this. Looks good on both desktop and mobile! I think it's good to go.

**Comment by melchoyce** [comment]
Added both of these!

https://wordpress.org/patterns/pattern/button-links-with-image-background/
https://wordpress.org/patterns/pattern/button-links-with-gradient-background/
