### ISSUE TITLE
Collection of Media & Text header patterns

### ISSUE THREAD

**Issue by kjellr** [WordPress/pattern-directory#126]
I'd like to propose these five split screen “Media & Text” block patterns. They show the range of what can be done with the media & text block. 

---

## Pattern Title

1. Image with headline and description.
2. Image on solid color with description.
3. Section divider with image and text. 
4. Title area with image and heading. 
5. Introduction with image on the left.

## Pattern Categories

Header, Text

## Screenshots

1. 
<img width="1200" alt="Frame 3" src="https://user-images.githubusercontent.com/1202812/121063943-f423b480-c794-11eb-8298-7e1475f53db4.png">

2.
<img width="1200" alt="Frame 8" src="https://user-images.githubusercontent.com/1202812/121063959-fab22c00-c794-11eb-9fbb-b0806980e26c.png">

3. 
<img width="1200" alt="Frame 12" src="https://user-images.githubusercontent.com/1202812/121063987-069dee00-c795-11eb-9398-ef536d035f60.png">

4. 
<img width="1200" alt="Frame 21" src="https://user-images.githubusercontent.com/1202812/121064094-21706280-c795-11eb-9bd8-52b1baa908a4.png">

5.
<img width="1200" alt="Frame 48" src="https://user-images.githubusercontent.com/1202812/121064104-2503e980-c795-11eb-94bd-6d296c7e85af.png">

## Image Credits

The November meteors from the Trouvelot astronomical drawings. CC0
https://www.rawpixel.com/image/283681/free-illustration-image-astronomy-space-stars

'A lyrical Tree-like', abstract organic wire sculpture by Fons Heijnsbroek. CC0
https://www.flickr.com/photos/97030532@N06/27899409601

Vintage woodblock print of Japanese textile from Shima-Shima (1904) by Furuya Korin. CC0
https://www.rawpixel.com/image/420052/free-illustration-image-pattern-japanese-patterns-shima

Night in Shinagawa (1922) by Negoro Raizan. CC0
https://www.rawpixel.com/image/843243/sea-view-night

The Burgess bird book for children. CC0
https://www.flickr.com/photos/biodivlibrary/6243813364/in/photostream/

**Comment by melchoyce** [comment]
Love how different these all feel! Shows how versatile the Media & Text block can be.

**Comment by kjellr** [comment]
Here's markup for each of these patterns: 

1. https://gist.github.com/kjellr/269f14defd4d1a7188f2dd7b4c556a98
2. https://gist.github.com/kjellr/a22699b201526d852df7bc608fefb629
3. https://gist.github.com/kjellr/4997e2ed90f9860b49ecb33c147e93ac
4. https://gist.github.com/kjellr/7221fda6910556f6ec091fef56749bdb
5. https://gist.github.com/kjellr/eb2c1430a239588525288f60b6aeb527

**Comment by melchoyce** [comment]
These look good to me 👍

**Comment by kjellr** [comment]
These have all been added: 

https://wordpress.org/patterns/pattern/image-with-headline-and-description/
https://wordpress.org/patterns/pattern/section-divider-with-image-and-text/
https://wordpress.org/patterns/pattern/introduction-with-image-on-the-left/
https://wordpress.org/patterns/pattern/title-area-with-image-and-heading/
https://wordpress.org/patterns/pattern/image-on-solid-color-with-description/
