### ISSUE TITLE
Pattern Submission: Set of image + label patterns

### ISSUE THREAD

**Issue by kjellr** [WordPress/pattern-directory#127]
I'd like to propose this set of four "Image + Label" patterns. They each introduce a layout that's more unique than the typical caption-below-an-image treatment we often see. 

---

## Pattern Title

1. Image with description on the bottom right.
2. Image with description below and to the right. 
3. Offset images with descriptions. 
4. Alternating images with descriptions and solid colors. 

## Pattern Categories

Gallery

## Screenshots

1.
<img width="1200" alt="Frame 7" src="https://user-images.githubusercontent.com/1202812/121076039-ea557d80-c7a3-11eb-8922-8395ff26f561.png">

2.
<img width="1200" alt="Frame 10" src="https://user-images.githubusercontent.com/1202812/121076036-ea557d80-c7a3-11eb-8f44-5f6393283142.png">

3.
<img width="1200" alt="Frame 11" src="https://user-images.githubusercontent.com/1202812/121076034-e9bce700-c7a3-11eb-8640-cc74c10e05c9.png">

4.
<img width="1200" alt="Frame 15" src="https://user-images.githubusercontent.com/1202812/121076027-e75a8d00-c7a3-11eb-8c99-73adc5a26ef8.png">

## Image Credits

Apollo 16 Hasselblad Image. Public Domain
https://www.flickr.com/photos/projectapolloarchive/21077888164/in/photostream/

Vintage cupid illustration. CC0
https://www.rawpixel.com/image/539759/free-illustration-image-cupid-love-valentines

Cherry Blossom (1887–1897) by Ogawa Kazumasa. CC0
https://www.rawpixel.com/image/523356/free-illustration-image-cherry-blossom-flower-sakura

White Irises (1887–1897) by Ogawa Kazumasa. CC0
https://www.rawpixel.com/image/523359/free-illustration-image-white-flower-orchid-iris

Vintage avocado illustration. CC0
https://www.rawpixel.com/image/2289530/free-illustration-image-vintage-avocado-1900s-1900s-public-domain

Vintage avocado illustration. CC0
https://www.rawpixel.com/image/2297759/free-illustration-image-avocado-fruit-food

**Comment by melchoyce** [comment]
These are fun. 

With that last pattern, using the avocados, maybe you could cut the avocados out and put them onto either a white or tinted background? The grey clashes a bit with that yellow.

**Comment by beafialho** [comment]
Cool! Definitely more unique than the typical captions. Love the avocado pattern in these colors and also how it's so squared, it feels quite editorial.

**Comment by kjellr** [comment]
I've added the following patterns: 

https://wordpress.org/patterns/pattern/image-with-description-on-the-bottom-right/
https://wordpress.org/patterns/pattern/image-with-description-below-and-to-the-right/
https://wordpress.org/patterns/pattern/offset-images-with-descriptions/

For the avocado one, I realized I can't actually eliminate the vertical gap between the two media & text blocks, so I think we should just close for now. I might reuse those avocado images in a future pattern instead.
