### ISSUE TITLE
Pattern Submission: Event details pattern

### ISSUE THREAD

**Issue by kjellr** [WordPress/pattern-directory#128]
Three columns of text, paired with an image on top. The content here is a little random (since it's missing a title), but I think that's fine since it's just meant to be part of a larger page. When sourcing the image, I imagined this as part of a library's events page. 

---

## Pattern Title

Event details

## Pattern Categories

Text

## Screenshots

<img width="1200" alt="Frame 50" src="https://user-images.githubusercontent.com/1202812/121077527-b8ddb180-c7a5-11eb-8250-047658f58295.png">

## Image Credits

From Hans Christian Andersen's Thumbelina (Kindergarten Negatives). CC0
https://commons.wikimedia.org/w/index.php?curid=86454349

**Comment by kjellr** [comment]
Here's the block markup for this one: 

https://gist.github.com/kjellr/216b6b392815fc60ad2abfdf135364c5

**Comment by beafialho** [comment]
I think this one is ready to go :tada:

**Comment by kjellr** [comment]
This is live! Thanks.

https://wordpress.org/patterns/pattern/event-details/
