### ISSUE TITLE
Pattern Submission: Call to Action with Background Image pattern

### ISSUE THREAD

**Issue by beafialho** [WordPress/pattern-directory#131]
I'd like to propose this call to action pattern, it has a minimal feel and the layout with text on a rectangle is simple and efficient for a variety of use cases.

---

## Pattern Title
Call to Action with Background Image

## Pattern Categories
Call to Action

## Screenshots
![Frame 45](https://user-images.githubusercontent.com/65220155/121209918-286da280-c873-11eb-90c3-5841bf875d12.png)
Desktop

![Frame 79 Mobile-2](https://user-images.githubusercontent.com/65220155/121209940-2c99c000-c873-11eb-998c-6ec2573576bb.png)
Mobile

## Image Credits
Louis Comfort Tiffany, (American, 1848–1933). CC0
https://www.si.edu/object/vase%3Achndm_1966-55-19

**Comment by melchoyce** [comment]
This is great. I wonder if you could bring in an accent color, maybe on the link, to play off how colorful the background image is?

**Comment by beafialho** [comment]
> I wonder if you could bring in an accent color, maybe on the link, to play off how colorful the background image is?

That's a great point. Tried a few colors applied in several ways:
![Frame 45](https://user-images.githubusercontent.com/65220155/121366576-8234a200-c931-11eb-990d-ee3b945a1a1b.png)
![Frame 98](https://user-images.githubusercontent.com/65220155/121366591-8496fc00-c931-11eb-9252-f9393b4d7ee6.png)
![Frame 99](https://user-images.githubusercontent.com/65220155/121366600-85c82900-c931-11eb-9680-d74eba2a5914.png)
![Frame 100](https://user-images.githubusercontent.com/65220155/121366606-8660bf80-c931-11eb-8c97-b39af08aee82.png)
![Frame 101](https://user-images.githubusercontent.com/65220155/121366612-86f95600-c931-11eb-9800-131fc86179e9.png)

**Comment by kjellr** [comment]
I like that first one: 

![](https://user-images.githubusercontent.com/65220155/121366576-8234a200-c931-11eb-990d-ee3b945a1a1b.png)

**Comment by melchoyce** [comment]
Same!

**Comment by beafialho** [comment]
Cool! Here's the markup: https://gist.github.com/beafialho/69e9ed30e6f442b39039d1a6a7b2af45

**Comment by melchoyce** [comment]
I added this one to the directory, but it might need some more work to make it display better on smaller screens: https://wordpress.org/patterns/pattern/call-to-action-with-background-image/

**Comment by kjellr** [comment]
@melchoyce give this one a try:

```
<!-- wp:cover {"url":"https://wordpress.org/patterns/files/2021/06/CHSDM-1966-55-19EllenMcDermott-1-scaled.jpg","id":536,"dimRatio":0,"focalPoint":{"x":"0.49","y":"0.42"},"contentPosition":"center center","align":"full","style":{"spacing":{"padding":{"top":"1em","right":"1em","bottom":"1em","left":"1em"}}}} -->
<div class="wp-block-cover alignfull" style="padding-top:1em;padding-right:1em;padding-bottom:1em;padding-left:1em"><img class="wp-block-cover__image-background wp-image-536" alt="" src="https://wordpress.org/patterns/files/2021/06/CHSDM-1966-55-19EllenMcDermott-1-scaled.jpg" style="object-position:49% 42%" data-object-fit="cover" data-object-position="49% 42%"/><div class="wp-block-cover__inner-container"><!-- wp:spacer {"height":400} -->
<div style="height:400px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column {"width":"","style":{"spacing":{"padding":{"top":"1em","right":"1em","bottom":"1em","left":"1em"}},"color":{"background":"#ffffff","text":"#000000"},"elements":{"link":{"color":{"text":"#0078bb"}}}}} -->
<div class="wp-block-column has-text-color has-background has-link-color" style="background-color:#ffffff;color:#000000;padding-top:1em;padding-right:1em;padding-bottom:1em;padding-left:1em"><!-- wp:heading {"style":{"typography":{"fontSize":"48px"},"color":{"text":"#000000"}}} -->
<h2 class="has-text-color" style="color:#000000;font-size:48px"><strong>Vintage Vases</strong></h2>
<!-- /wp:heading -->

<!-- wp:spacer -->
<div style="height:100px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p><a href="http://wp.org" data-type="URL" data-id="wp.org"><strong>Shop the Collection</strong></a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"60%"} -->
<div class="wp-block-column" style="flex-basis:60%"></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div></div>
<!-- /wp:cover -->
```

**Comment by melchoyce** [comment]
Looks good to me 👍
