### ISSUE TITLE
Pattern Submission: Event Announcement and Details pattern

### ISSUE THREAD

**Issue by beafialho** [WordPress/pattern-directory#132]
I'd like to propose this Event pattern. It has a modern, edgy, poster feel which can be a good way to display information about exhibitions, concerts, conferences or events.

---

## Pattern Title
Event Announcement and Details

## Pattern Categories
Text

## Screenshots
![Frame 78](https://user-images.githubusercontent.com/65220155/121211711-9cf51100-c874-11eb-853a-6a87d63a088c.png)
Desktop

![Frame 79 Mobile-3](https://user-images.githubusercontent.com/65220155/121211719-9ebed480-c874-11eb-9805-0c446b8a772a.png)
Mobile

## Image Credits
Histoire naturelle ... [fragments] by Hélène Dumas. CC0 Public Domain
https://commons.wikimedia.org/wiki/File:Histoire_naturelle_..._-fragments-_-_Upper_cover_(C108eee15).jpg

**Comment by kjellr** [comment]
I like the all-caps text with italic mixed in. Might be worth changing the URL to `wp.org` instead, since the WordPress project owns that? We could also use `example.com`, but I think `wp.org` is nicer.

**Comment by melchoyce** [comment]
This one is stunning 👏

**Comment by beafialho** [comment]
> Might be worth changing the URL to wp.org instead, since the WordPress project owns that

Makes sense!

<img width="889" alt="Captura de ecrã 2021-06-09, às 14 24 02" src="https://user-images.githubusercontent.com/65220155/121362896-5fed5500-c92e-11eb-8a96-fdeb34a9af64.png">

**Comment by kjellr** [comment]
Looks great!

**Comment by melchoyce** [comment]
Worked on the markup for this:

```
<!-- wp:group {"align":"full","style":{"color":{"background":"#d2cdc7"}}} -->
<div class="wp-block-group alignfull has-background" style="background-color:#d2cdc7"><!-- wp:spacer {"height":50} -->
<div style="height:50px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:heading {"align":"wide","style":{"typography":{"fontSize":"46px","lineHeight":"1.1"}}} -->
<h2 class="alignwide" style="font-size:46px;line-height:1.1">HÉLÈNE DUMAS<br><em>FRAGMENTS</em></h2>
<!-- /wp:heading -->

<!-- wp:heading {"level":3,"align":"wide","style":{"typography":{"fontSize":"46px","lineHeight":"1.1"}}} -->
<h3 class="alignwide" style="font-size:46px;line-height:1.1">20/4 — 9/9/2021<br>SOUTH LONDON ART GALLERY</h3>
<!-- /wp:heading -->

<!-- wp:spacer {"height":50} -->
<div style="height:50px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column {"width":"25%"} -->
<div class="wp-block-column" style="flex-basis:25%"></div>
<!-- /wp:column -->

<!-- wp:column {"width":"75%"} -->
<div class="wp-block-column" style="flex-basis:75%"><!-- wp:image {"id":3173,"sizeSlug":"full","linkDestination":"none"} -->
<figure class="wp-block-image size-full"><img src="https://mywptesting.site/wp-content/uploads/2021/06/Histoire_naturelle_..._-fragments-_-_Upper_cover_C108eee15-1.jpg" alt="" class="wp-image-3173"/></figure>
<!-- /wp:image --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:spacer {"height":50} -->
<div style="height:50px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph {"style":{"typography":{"fontSize":"25px"}}} -->
<p style="font-size:25px">MORE INFO AT: WP.ORG · +44 21 1234 5678</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph {"align":"right","style":{"typography":{"fontSize":"25px"}}} -->
<p class="has-text-align-right" style="font-size:25px">INSTAGRAM · <a href="#">TICKETS AVAILABLE</a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:spacer {"height":50} -->
<div style="height:50px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div>
<!-- /wp:group -->
```

**Comment by kjellr** [comment]
This looks great! One small edit before we add to the directory: 

I suggest we change "TICKETS AVAILABLE" to just "TICKETS" to avoid this weird wrap on mobile: 

<img width="359" alt="Screen Shot 2021-06-10 at 12 57 51 PM" src="https://user-images.githubusercontent.com/1202812/121566488-90df8f80-c9eb-11eb-99e5-81349648f2a6.png">

Thank you both!

**Comment by melchoyce** [comment]
Awesome, this one is now live: https://wordpress.org/patterns/pattern/event-announcement-and-details/
