### ISSUE TITLE
Pattern Submission: Introduction with a big image

### ISSUE THREAD

**Issue by melchoyce** [WordPress/pattern-directory#133]
I'd like to propose this pattern, featuring a combination of columns, text, and a big image. It could be used as a website header for sites like portfolios or publications, or a section header.

## Pattern Title
Big image with headline and columns above

## Pattern Categories
Columns, text, image

## Screenshots
![image](https://user-images.githubusercontent.com/2846578/121216470-ea5e8780-c84e-11eb-9072-4af81807c8c2.png)

## Image Credits
Collinsonia canadensis 3, Stoneroot, Howard County, Md, Helen Lowe Metzman_2019-03-22-17.35.53 ZS PMax UDR, by USGS Bee Inventory and Monitoring Lab. Public Domain. 
https://www.flickr.com/photos/usgsbiml/49010049936/in/photostream/

## Block Markup
https://gist.github.com/melchoyce/60bc6f012260cbd01f8dc87138bdc665

**Comment by kjellr** [comment]
Thanks, @melchoyce! This one looks good for inclusion in the directory. I've added it here: 

https://wordpress.org/patterns/pattern/big-image-with-headline-and-columns-above/

There's something weird going on with it there though: the wide alignment for the column block doesn't appear to be picked up in either the preview or the editor, and the image is off to the left erroneously in the preview: 

Editor|Preview
---|---
<img width="1138" alt="Screen Shot 2021-06-09 at 8 17 11 AM" src="https://user-images.githubusercontent.com/1202812/121352691-19cace00-c8fb-11eb-9424-669a0163f2c4.png">|<img width="959" alt="Screen Shot 2021-06-09 at 8 17 01 AM" src="https://user-images.githubusercontent.com/1202812/121352699-1afbfb00-c8fb-11eb-859e-71d7dda96064.png">

I'll keep this open for investigation.

**Comment by kjellr** [comment]
Since some of the display issues appear to span across multiple patterns, I've opened a single issue to track them. I'll close this issue as resolved.

https://github.com/WordPress/pattern-directory/issues/156
