### ISSUE TITLE
Pattern Submission: Cover block with headline

### ISSUE THREAD

**Issue by melchoyce** [WordPress/pattern-directory#135]
I'd like to propose this Cover pattern, which shows off the Cover alignment attributes.

## Pattern Title
Full width image of space with big headline

## Pattern Categories
Cover

## Screenshots
![image](https://user-images.githubusercontent.com/2846578/121222220-568fba00-c854-11eb-8b97-01501bf12f4a.png)

## Image Credits
Star clusters in Hurcules from the Trouvelot astronomical drawings (1881-1882), E. L. Trouvelot. CC0.
https://www.rawpixel.com/image/283674/free-illustration-image-stars-etienne-leopold-trouvelot-space

## Block Markup
https://gist.github.com/melchoyce/fb2c5c2b6f87c962675fd797b931062e

**Comment by kjellr** [comment]
Thanks, @melchoyce! I've added this one to the directory. I made some minor adjustments to text size and padding in order to get it to work nicely on mobile too. 

https://wordpress.org/patterns/pattern/full-width-image-of-space-with-big-headline/
