### ISSUE TITLE
Pattern Submission: Two columns with image underneath

### ISSUE THREAD

**Issue by melchoyce** [WordPress/pattern-directory#136]
I'd like to propose this pattern, which is an elegant approach to combining images and text content. I can see it being used in any modern, visually-driven site.

## Pattern Title
Two columns with impressionist image

## Pattern Categories
Columns, image

## Screenshots
![image](https://user-images.githubusercontent.com/2846578/121224268-63ada880-c856-11eb-8840-d0029e5d96a5.png)

## Image Credits
Les Andelys, Côte d’Aval (1886), by Paul Signac. CC0.
https://www.rawpixel.com/image/2922804/free-illustration-image-illustration-sea-sea-art

## Block Markup
https://gist.github.com/melchoyce/10b15cda10dea0c800b248d4c914832b

**Comment by kjellr** [comment]
Looks great, thanks @melchoyce. I've published this one in the directory: 

https://wordpress.org/patterns/pattern/two-columns-with-image-underneath/
