### ISSUE TITLE
Pattern Submission: Three images and text

### ISSUE THREAD

**Issue by melchoyce** [WordPress/pattern-directory#137]
I'd like to propose this pattern featuring a unique gallery layout with text to the side. The vase illustrations provide a classic but timeless feel.

## Pattern Title
Three images and text

## Pattern Categories
Columns, Gallery

## Screenshots
![image](https://user-images.githubusercontent.com/2846578/121228664-049e6280-c85b-11eb-977f-fe919630bb9d.png)

## Image Credits
Design for a Vase (1880-1910), Noritake Factory. CC0. 
https://www.rawpixel.com/image/2848925/free-illustration-image-vase-flower-china

Design for a Vase (1880-1910), Noritake Factory. CC0. 
https://www.rawpixel.com/image/2848918/free-illustration-image-pattern-flower-vase-noritake

Design for a Vase (1880-1910), Noritake Factory. CC0. 
https://www.rawpixel.com/image/2849089/free-illustration-image-watercolor-noritake-flower

## Block Markup
https://gist.github.com/melchoyce/0611de8dd6228a5db4d16afa8f54911c

**Comment by kjellr** [comment]
Thanks, @melchoyce. This one looks great, so I've added it to the directory: 

https://wordpress.org/patterns/pattern/three-images-and-text/
