### ISSUE TITLE
Pattern Submission: Intro text with button and gallery

### ISSUE THREAD

**Issue by melchoyce** [WordPress/pattern-directory#139]
I'd like to propose this complex pattern combining text, button, and gallery blocks. It would be great for any shop or landing page.

## Pattern Title
Centered introduction text with button and offset images

## Pattern Categories
Text, Gallery

## Screenshots
![image](https://user-images.githubusercontent.com/2846578/121229726-53003100-c85c-11eb-9f4f-637c6360a849.png)

## Image Credits
Japanese vintage original woodblock print from Yatsuo no tsubaki, by Taguchi Tomoki. CC0.
https://www.rawpixel.com/image/525439/free-illustration-image-tomoki-japanese-chinese

Japanese vintage original woodblock print from Yatsuo no tsubaki, by Taguchi Tomoki. CC0.
https://www.rawpixel.com/image/525466/free-illustration-image-tomoki-japanese-strange

## Block Markup
https://gist.github.com/melchoyce/5a879e347473e5aa05c624373f7bdddd

**Comment by kjellr** [comment]
This looks great, thanks @melchoyce. I've added this one to the Directory:

https://wordpress.org/patterns/pattern/centered-introduction-text-with-button-and-offset-images/

cc @ryelle: Any idea why the first part of this pattern is being cut off in the front-end preview? It appears correctly in the editor, but is missing the first two blocks in the front-end: 

Editor|Front-end
---|---
<img width="1232" alt="Screen Shot 2021-06-09 at 8 08 41 AM" src="https://user-images.githubusercontent.com/1202812/121351561-ec315500-c8f9-11eb-8134-8b87e66bbc87.png">|<img width="1201" alt="Screen Shot 2021-06-09 at 8 08 25 AM" src="https://user-images.githubusercontent.com/1202812/121351562-ecc9eb80-c8f9-11eb-83af-04ed76842252.png">

**Comment by beafialho** [comment]
Love the layout, and the japanese vibes :sparkles:

**Comment by kjellr** [comment]
Since some of the display issues appear to span across multiple patterns, I've opened a single issue to track them. I'll close this issue as resolved.

https://github.com/WordPress/pattern-directory/issues/156
