### ISSUE TITLE
Pattern Submission: Two half-width cover blocks in columns

### ISSUE THREAD

**Issue by melchoyce** [WordPress/pattern-directory#141]
I'd like to propose this pattern. The two side-by-side cover blocks create an immersive feeling that's great for stores.

## Pattern Title
Two columns with full-width backgrounds

## Pattern Categories
Columns, Image

## Screenshots
![image](https://user-images.githubusercontent.com/2846578/121243280-8bf3d200-c86b-11eb-89ab-2c24cef1caf1.png)

## Image Credits
Vintage woodblock print of Japanese textile from Shima-Shima (1904), by Furuya Korin. CC0.
https://www.rawpixel.com/image/420162/free-illustration-image-pattern-japanese-patterns-furuya-korin

Vintage woodblock print of Japanese textile from Shima-Shima (1904), by Furuya Korin. CC0.
https://www.rawpixel.com/image/420225/free-illustration-image-pattern-vintage-fabric-green-pattern

## Block Markup
https://gist.github.com/melchoyce/d7de1c80b515a77fd69c467d147cff2d

**Comment by kjellr** [comment]
Looks good, thanks @melchoyce. This one is good to go. I made some minor adjustments: 

- Specified the text and button color to ensure readability.
- Decreased the font size from 72px to 64px so it's less likely to break oddly on smaller screens. 

New markup is here:
https://gist.github.com/kjellr/6c2d4d721d23547c590bf5b594eb7f06

I wish we could get rid of the gap in between these, but we can't until we can control the column gap width. For now I think it's ok: 

<img width="1342" alt="Screen Shot 2021-06-09 at 7 34 55 AM" src="https://user-images.githubusercontent.com/1202812/121347440-3237ea00-c8f5-11eb-8c79-4c576d91b18a.png">

This one's all set to add to the directory. 👍

**Comment by kjellr** [comment]
This has been added to the directory. 🎉 

https://wordpress.org/patterns/pattern/two-columns-with-full-width-backgrounds/
