### ISSUE TITLE
Pattern Submission: The Famous Quotes

### ISSUE THREAD

**Issue by anarieldesign** [WordPress/pattern-directory#144]
This pattern can be used to display quotes or testimonials.
Built with Twenty Twenty-One

## Pattern Title

The Famous Quotes

## Pattern Categories

Columns, Testimonials

## Screenshots

![Screenshot 2021-06-09 at 17 13 59](https://user-images.githubusercontent.com/20610429/121381665-35a79180-c946-11eb-8b03-17b6c54caf5f.png)

## Image Credits

https://www.rawpixel.com/image/523362/lotus-flowers-ogawa-kazumasa

## Block Markup

<div class="wp-block-columns alignwide">
<div class="wp-block-column">
<div class="wp-block-group has-background" style="background-color:#ffeddc"><div class="wp-block-group__inner-container">
<div class="wp-block-image is-style-rounded"><figure class="aligncenter size-large is-resized"><img src="https://anarieldesign.com/blockpatterns/image-from-rawpixel-id-523362-a-jpeg.jpg" alt="" class="wp-image-20434" width="300" height="450"/></figure></div>

<blockquote class="wp-block-quote has-text-align-center is-style-default"><p>"Cras sodales luctus arcu, ac placerat nunc sagittis a. In at turpis ac nibh luctus sagittis in ut est. Proin sed mi vitae velit convallis gravida imperdiet eu mauris."</p><cite>— Joya Goete</cite></blockquote>

<hr class="wp-block-separator has-text-color has-background is-style-dots" style="background-color:#bbcdd3;color:#bbcdd3"/>
</div></div>
</div>

<div class="wp-block-column">
<div class="wp-block-group has-background" style="background-color:#dbdeff"><div class="wp-block-group__inner-container">
<div class="wp-block-image is-style-rounded"><figure class="aligncenter size-large is-resized"><img src="https://anarieldesign.com/blockpatterns/image-from-rawpixel-id-523362-b-jpeg.jpg" alt="" class="wp-image-20435" width="300" height="450"/></figure></div>

<blockquote class="wp-block-quote has-text-align-center is-style-default"><p>"Cras sodales luctus arcu, ac placerat nunc sagittis a. In at turpis ac nibh luctus sagittis in ut est. Proin sed mi vitae velit convallis gravida imperdiet eu mauris."</p><cite>— Tia Love</cite></blockquote>

<hr class="wp-block-separator has-text-color has-background is-style-dots" style="background-color:#bbcdd3;color:#bbcdd3"/>
</div></div>
</div>

<div class="wp-block-column">
<div class="wp-block-group has-background" style="background-color:#dbf8ff"><div class="wp-block-group__inner-container">
<div class="wp-block-image is-style-rounded"><figure class="aligncenter size-large is-resized"><img src="https://anarieldesign.com/blockpatterns/image-from-rawpixel-id-523362-c-jpeg.jpg" alt="" class="wp-image-20436" width="300" height="450"/></figure></div>

<blockquote class="wp-block-quote has-text-align-center is-style-default"><p>"Cras sodales luctus arcu, ac placerat nunc sagittis a. In at turpis ac nibh luctus sagittis in ut est. Proin sed mi vitae velit convallis gravida imperdiet eu mauris."</p><cite>— Adele Tui</cite></blockquote>

<hr class="wp-block-separator has-text-color has-background is-style-dots" style="background-color:#bbcdd3;color:#bbcdd3"/>
</div></div>
</div>
</div>

**Comment by melchoyce** [comment]
I love these illustrations 😍 

What would you think about drawing from the illustration colors? Thinking something like this:

![image](https://user-images.githubusercontent.com/2846578/121394249-24975a00-c91f-11eb-9abb-6bea8c95e2bb.png)

Also swapped out the lorem ipsum for some fake-real text.

**Comment by anarieldesign** [comment]
@melchoyce yes that's perfect, I was playing with it and came to the same conclusion and wanted to resubmit it :)

**Comment by melchoyce** [comment]
Here's the markup, if you want to make any adjustments:

```<!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column {"verticalAlignment":"top","style":{"color":{"background":"#eee9e5"}}} -->
<div class="wp-block-column is-vertically-aligned-top has-background" style="background-color:#eee9e5"><!-- wp:cover {"customOverlayColor":"#eee9e5","contentPosition":"center center","align":"full","style":{"spacing":{"padding":{"top":"10px","right":"10px","bottom":"10px","left":"10px"}}}} -->
<div class="wp-block-cover alignfull has-background-dim" style="padding-top:10px;padding-right:10px;padding-bottom:10px;padding-left:10px;background-color:#eee9e5"><div class="wp-block-cover__inner-container"><!-- wp:image {"align":"center","id":3085,"width":200,"height":300,"sizeSlug":"large","linkDestination":"none","className":"is-style-rounded"} -->
<div class="wp-block-image is-style-rounded"><figure class="aligncenter size-large is-resized"><img src="https://mywptesting.site/wp-content/uploads/2021/06/68747470733a2f2f616e617269656c64657369676e2e636f6d2f626c6f636b7061747465726e732f696d6167652d66726f6d2d726177706978656c2d69642d3532333336322d612d6a7065672e6a7067.jpg" alt="" class="wp-image-3085" width="200" height="300"/></figure></div>
<!-- /wp:image -->

<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#4c3843"}}} -->
<p class="has-text-align-center has-text-color" style="color:#4c3843"><strong>Just an ounce of prevention makes perfect.</strong><meta charset="utf-8"></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#4c3843"},"typography":{"fontSize":"14px"}}} -->
<p class="has-text-align-center has-text-color" style="color:#4c3843;font-size:14px">— Margarit Avagyan</p>
<!-- /wp:paragraph -->

<!-- wp:separator {"customColor":"#ceaf9b","align":"wide","className":"is-style-dots"} -->
<hr class="wp-block-separator alignwide has-text-color has-background is-style-dots" style="background-color:#ceaf9b;color:#ceaf9b"/>
<!-- /wp:separator --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"top","style":{"color":{"background":"#e3ead2"}}} -->
<div class="wp-block-column is-vertically-aligned-top has-background" style="background-color:#e3ead2"><!-- wp:cover {"customOverlayColor":"#e3ead2","align":"full","style":{"spacing":{"padding":{"top":"10px","right":"10px","bottom":"10px","left":"10px"}}}} -->
<div class="wp-block-cover alignfull has-background-dim" style="padding-top:10px;padding-right:10px;padding-bottom:10px;padding-left:10px;background-color:#e3ead2"><div class="wp-block-cover__inner-container"><!-- wp:image {"align":"center","id":3087,"width":200,"height":300,"sizeSlug":"large","linkDestination":"none","className":"is-style-rounded"} -->
<div class="wp-block-image is-style-rounded"><figure class="aligncenter size-large is-resized"><img src="https://mywptesting.site/wp-content/uploads/2021/06/68747470733a2f2f616e617269656c64657369676e2e636f6d2f626c6f636b7061747465726e732f696d6167652d66726f6d2d726177706978656c2d69642d3532333336322d632d6a7065672e6a7067.jpg" alt="" class="wp-image-3087" width="200" height="300"/></figure></div>
<!-- /wp:image -->

<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#535148"}}} -->
<p class="has-text-align-center has-text-color" style="color:#535148"><strong>Curiosity is as good as a wink to a blind horse.</strong><meta charset="utf-8"></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#535148"},"typography":{"fontSize":"14px"}}} -->
<p class="has-text-align-center has-text-color" style="color:#535148;font-size:14px"><meta charset="utf-8">— Rūta Eglītis</p>
<!-- /wp:paragraph -->

<!-- wp:separator {"customColor":"#a3ba6c","align":"wide","className":"is-style-dots"} -->
<hr class="wp-block-separator alignwide has-text-color has-background is-style-dots" style="background-color:#a3ba6c;color:#a3ba6c"/>
<!-- /wp:separator --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"top","style":{"color":{"background":"#eee7ce"}}} -->
<div class="wp-block-column is-vertically-aligned-top has-background" style="background-color:#eee7ce"><!-- wp:cover {"customOverlayColor":"#eee7ce","align":"full","style":{"spacing":{"padding":{"top":"10px","right":"10px","bottom":"10px","left":"10px"}}}} -->
<div class="wp-block-cover alignfull has-background-dim" style="padding-top:10px;padding-right:10px;padding-bottom:10px;padding-left:10px;background-color:#eee7ce"><div class="wp-block-cover__inner-container"><!-- wp:image {"align":"center","id":3086,"width":200,"height":300,"sizeSlug":"large","linkDestination":"none","className":"is-style-rounded"} -->
<div class="wp-block-image is-style-rounded"><figure class="aligncenter size-large is-resized"><img src="https://mywptesting.site/wp-content/uploads/2021/06/68747470733a2f2f616e617269656c64657369676e2e636f6d2f626c6f636b7061747465726e732f696d6167652d66726f6d2d726177706978656c2d69642d3532333336322d622d6a7065672e6a7067.jpg" alt="" class="wp-image-3086" width="200" height="300"/></figure></div>
<!-- /wp:image -->

<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#54483d"}}} -->
<p class="has-text-align-center has-text-color" style="color:#54483d"><strong>Wednesday's child is certain to have nine lives.</strong><meta charset="utf-8"></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"align":"center","style":{"typography":{"fontSize":"14px"},"color":{"text":"#54483d"}}} -->
<p class="has-text-align-center has-text-color" style="color:#54483d;font-size:14px">— <meta charset="utf-8">Nevra Badem</p>
<!-- /wp:paragraph -->

<!-- wp:separator {"customColor":"#ccb974","align":"wide","className":"is-style-dots"} -->
<hr class="wp-block-separator alignwide has-text-color has-background is-style-dots" style="background-color:#ccb974;color:#ccb974"/>
<!-- /wp:separator --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->```

**Comment by anarieldesign** [comment]
I love it this way :), don't need to make any adjustments. I'll definitely submit more patterns in the next few days, playing with it at the moment. Have them many in our premium themes but trying to make ones that are not dependent on the theme styles and additional features

**Comment by melchoyce** [comment]
Yeah making them theme-agnostic has been super tough. Stoked to see more of your patterns!

**Comment by anarieldesign** [comment]
I just submitted a few more :). Hope they will be useful :)

**Comment by kellychoffman** [comment]
❤️

**Comment by kjellr** [comment]
Thanks everyone! I'll get this added to the directory.

**Comment by kjellr** [comment]
Added. Thanks again!

https://wordpress.org/patterns/pattern/three-quotes-with-images/
