### ISSUE TITLE
Pattern Submission: Three Column, Staggered Steps

### ISSUE THREAD

**Issue by richtabor** [WordPress/pattern-directory#145]
## Pattern Title
Three Column, Staggered Steps

## Pattern Categories
Text

## Screenshots
<img width="1414" alt="Screen Shot 2021-06-09 at 12 20 32 PM" src="https://user-images.githubusercontent.com/1813435/121392169-23652d80-c91d-11eb-85f7-c57fa6716855.png">

## Block Markup
https://gist.github.com/richtabor/d1526831133e82c93f816fe9d0723df4

**Comment by kjellr** [comment]
Thanks, @richtabor! For these pre-submitted patterns, we're hoping to replace lorem-ipsum text with something more real. Do you have any suggestions for what that could change out to?

**Comment by richtabor** [comment]
Yea I saw that, just submitted another - I'll tweak this a bit.

**Comment by richtabor** [comment]
> Thanks, @richtabor! For these pre-submitted patterns, we're hoping to replace lorem-ipsum text with something more real. Do you have any suggestions for what that could change out to?

I updated the text. ✅

**Comment by kjellr** [comment]
Thank you! This pattern is live. 

https://wordpress.org/patterns/pattern/three-column-staggered-steps/
