### ISSUE TITLE
Pattern Submission: Image Hero with Button

### ISSUE THREAD

**Issue by richtabor** [WordPress/pattern-directory#147]
A unique way to showcase an image, with a heading/descriptive text and a follow-up call to action focused text below.

## Pattern Title
Image Hero with Button (suppose someone could come up with a better one 🤷 )

## Pattern Categories
Gallery

## Screenshots
<img width="1445" alt="Screen Shot 2021-06-09 at 11 55 11 AM" src="https://user-images.githubusercontent.com/1813435/121388535-8e146a00-c919-11eb-9f6b-f1f885ec3b07.png">

## Image Credits
https://www.wikiart.org/en/berthe-morisot/the-garden-at-bougival-1884 (Same image used in TwentyTwenty)

## Block Markup
https://gist.github.com/richtabor/6a609bf7b43f0c72c7b7e1996761f79b

**Comment by kjellr** [comment]
Thanks! This one is live here: https://wordpress.org/patterns/pattern/image-with-two-text-areas-and-button/
