### ISSUE TITLE
Pattern Submission: Cover block with the Caption

### ISSUE THREAD

**Issue by anarieldesign** [WordPress/pattern-directory#148]
A cover block pattern with the group block 

---

## Pattern Title

Cover Block with caption

## Pattern Categories

Cover

## Screenshots

![Screenshot 2021-06-09 at 18 14 47](https://user-images.githubusercontent.com/20610429/121391399-9cc94400-c94e-11eb-89bd-bdefe8e56a34.png)

## Image Credits

https://www.rawpixel.com/image/414445/free-illustration-image-birds-mark-catesby-spring

## Block Markup

<div class="wp-block-cover alignfull" style="min-height:700px"><img class="wp-block-cover__image-background wp-image-20466" alt="" src="https://www.anarieldesign.com/blockpatterns/image-from-rawpixel-id-414445-bigjpeg-scaled.jpeg" style="object-position:69% 32%" data-object-fit="cover" data-object-position="69% 32%"/><div class="wp-block-cover__inner-container">
<p></p>

<div class="wp-block-group alignwide is-style-default has-white-background-color has-background"><div class="wp-block-group__inner-container">
<div class="wp-block-columns alignwide">
<div class="wp-block-column" style="flex-basis:33.33%">
<figure class="wp-block-image size-large is-resized is-style-rounded"><img src="https://www.anarieldesign.com/blockpatterns/bird.jpeg" alt="" class="wp-image-20468" width="201" height="201"/></figure>

<p></p>
</div>

<div class="wp-block-column" style="flex-basis:66.66%">
<h2 class="has-dark-gray-color has-text-color"><strong>A lovely day in the nature</strong></h2>

<p class="has-gray-color has-text-color">The word&nbsp;<em>nature</em>&nbsp;is borrowed from the&nbsp;<a href="https://en.wikipedia.org/wiki/Old_French">Old French</a>&nbsp;<em>nature</em>&nbsp;and is derived from the&nbsp;<a href="https://en.wikipedia.org/wiki/Latin">Latin</a>&nbsp;word&nbsp;<em>natura</em>, or "essential qualities, innate disposition", and in ancient times, literally meant "birth".</p>

<div class="wp-block-buttons">
<div class="wp-block-button"><a class="wp-block-button__link">Read More</a></div>
</div>
</div>
</div>
</div></div>
</div></div>

**Comment by melchoyce** [comment]
This is lovely 😍 

I played around with this a little bit to help bring out some of the elegance:

![image](https://user-images.githubusercontent.com/2846578/121538419-c3c95980-c9d2-11eb-8220-543f83e22a21.png)

- I made the cover block full-height , since the image feels interesting enough to support it
- I gave the left column a background color to ground it a bit more, and vertically centered the image for balance

What do you think?

Here's the markup if you want to tweak anything: https://gist.github.com/melchoyce/6c0d596ea7d434f1eb15c6f6df0dc4c8

**Comment by anarieldesign** [comment]
Love it this way :). I don't need to tweak anything, it looks great this way :).
I'm working on a new full site editing theme with this layout and images to submit it to the theme repository :)

**Comment by melchoyce** [comment]
Awesome, thanks so much @anarieldesign! This one is now live: https://wordpress.org/patterns/pattern/illustration-of-bird-with-callout/
