### ISSUE TITLE
Pattern Creation: Logged out/new user page with details about creating patterns

### ISSUE THREAD

**Issue by MichaelArestad** [WordPress/pattern-directory#15]
My prototypes do not include the login flow yet. Ideally, we would want to log in or register the user as late in the flow as possible. Is this something we can do after they have gone through the submission process as a last step?

**Comment by ryelle** [comment]
Ideally they'd log in before, so we can save the pattern as they're working on it (autosave maybe) or allow them to save drafts.

We could make it work so anyone can use the pattern editor, but nothing would save, and when they go off to log in we'd probably loose their pattern. I'm sure there's a way to make that not happen (like local storage), but it would introduce more complexity (needing two different save handlers for anon & known users).

That's not to say we can't do it, but I don't think it needs to be an early priority.

**Comment by MichaelArestad** [comment]
@ryelle that makes sense. I'll plan for an upfront login flow.

**Comment by ryelle** [comment]
When going to the "new pattern" page, users that are not logged in will be shown an informational page, TBD

**Comment by ryelle** [comment]
Current logged out page:

![Screen Shot 2021-10-20 at 14 49 17-fullpage](https://user-images.githubusercontent.com/541093/138153547-27e86422-de6b-4a99-98fb-178d6abe922d.png)

**Comment by ryelle** [comment]
We could also use this page to keep that info available regardless of logged in status: https://wordpress.org/patterns/about/

**Comment by ryelle** [comment]
Closing in favor of #394
