### ISSUE TITLE
Pattern Submission: Offset gallery with fixed background & quote

### ISSUE THREAD

**Issue by jameskoster** [WordPress/pattern-directory#154]
## Pattern Title
Offset gallery with fixed background & quote

## Pattern Categories
Gallery, Quote

## Screenshots

https://user-images.githubusercontent.com/846565/121510781-e9109480-c9df-11eb-9604-0bcda5bfda06.mp4

## Image Credits
* https://www.rawpixel.com/image/3064488/free-illustration-image-japanese-japan-japan-art
* https://www.rawpixel.com/image/3064491/free-illustration-image-japanese-japanese-art-japan
* https://www.rawpixel.com/image/3065130/free-illustration-image-japan-japanese-japanese-art
* https://www.rawpixel.com/image/3065120/free-illustration-image-landscape-japan-japanese
* https://www.rawpixel.com/image/3063951/free-illustration-image-japanese-art-japanese-mountain

## Block Markup
https://gist.github.com/jameskoster/ea5b89801ae47920019f18061d24225e

**Comment by melchoyce** [comment]
This is cool! I wonder if we could simplify it by removing the second batch of images? Might also be nice to try upping the size on that quote, I think it could shine with a little more refinement.

**Comment by kjellr** [comment]
Here's an attempt at simplifying this one. Let me know what you think!


![Screen-Shot-2021-06-10-at-14 17 02](https://user-images.githubusercontent.com/1202812/121576815-cc338b80-c9f6-11eb-8aeb-75fc7114e203.jpg)

Markup is over here: https://gist.github.com/kjellr/6faf73f4b9ad84519d6d304db411bf5f

**Comment by kellychoffman** [comment]
Love it! Ship it!

**Comment by melchoyce** [comment]
Looks great, but I don't think having the quote in the left columns works as well on mobile:

![image](https://user-images.githubusercontent.com/2846578/121587184-811f7580-ca02-11eb-8443-f6954e96945a.png)

**Comment by kjellr** [comment]
That quote issue is just because of the way TT1 displays quotes. 😕

It looks fine with themes that use a more traditional quote display: 

<img width="358" alt="Screen Shot 2021-06-10 at 3 45 36 PM" src="https://user-images.githubusercontent.com/1202812/121587529-ea06ed80-ca02-11eb-85d1-0cdeecee953f.png">

**Comment by jameskoster** [comment]
> Let me know what you think!

Yay! Looks good 😁

**Comment by melchoyce** [comment]
Ah, I meant more how the quote is sandwiched between the two images with some uneven spacing, I should have been clearer.

**Comment by kjellr** [comment]
@melchoyce good call. Here's an updated version that evens that space out: 

Desktop|Mobile
---|---
<img width="1236" alt="Screen Shot 2021-06-14 at 1 04 10 PM" src="https://user-images.githubusercontent.com/1202812/121931088-242d0380-cd11-11eb-9a82-119303d3c70b.png">|<img width="356" alt="Screen Shot 2021-06-14 at 1 04 27 PM" src="https://user-images.githubusercontent.com/1202812/121931093-24c59a00-cd11-11eb-920f-c6b3d8a42938.png">


```
<!-- wp:cover {"url":"https://jameskoster.design/wp-content/uploads/2021/06/image-from-rawpixel-id-3064488-jpeg.jpg","id":507,"hasParallax":true,"dimRatio":40,"overlayColor":"primary","contentPosition":"center center","align":"full","style":{"spacing":{"padding":{"top":"5vw","right":"5vw","bottom":"5vw","left":"5vw"}}}} -->
<div class="wp-block-cover alignfull has-background-dim-40 has-primary-background-color has-background-dim has-parallax" style="padding-top:5vw;padding-right:5vw;padding-bottom:5vw;padding-left:5vw;background-image:url(https://jameskoster.design/wp-content/uploads/2021/06/image-from-rawpixel-id-3064488-jpeg.jpg)"><div class="wp-block-cover__inner-container"><!-- wp:columns {"verticalAlignment":"top","align":"full"} -->
<div class="wp-block-columns alignfull are-vertically-aligned-top"><!-- wp:column {"verticalAlignment":"top","width":"72%","style":{"spacing":{"padding":{"right":"4vw","top":"0vw","bottom":"0vw","left":"0vw"}}}} -->
<div class="wp-block-column is-vertically-aligned-top" style="padding-top:0vw;padding-right:4vw;padding-bottom:0vw;padding-left:0vw;flex-basis:72%"><!-- wp:image {"id":508,"sizeSlug":"large","linkDestination":"none","style":{"border":{"radius":"4px"}}} -->
<figure class="wp-block-image size-large" style="border-radius:4px"><img src="https://jameskoster.design/wp-content/uploads/2021/06/image-from-rawpixel-id-3064491-jpeg-2000x1273.jpg" alt="" class="wp-image-508"/></figure>
<!-- /wp:image -->

<!-- wp:spacer {"height":40} -->
<div style="height:40px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:group {"style":{"color":{"text":"#ffffff"},"elements":{"link":{"color":{"text":"#ffffff"}}}}} -->
<div class="wp-block-group has-text-color has-link-color" style="color:#ffffff"><!-- wp:quote {"className":"is-style-default"} -->
<blockquote class="wp-block-quote is-style-default"><p><em>Aspire to be like Mt. Fuji, with such a broad and solid foundation that the strongest earthquake cannot move you, and so tall that the greatest enterprises of common men seem insignificant from your lofty perspective.</em></p><cite><strong>— Miyamoto Musashi</strong></cite></blockquote>
<!-- /wp:quote --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"top","width":"33.33%"} -->
<div class="wp-block-column is-vertically-aligned-top" style="flex-basis:33.33%"><!-- wp:spacer {"height":40} -->
<div style="height:40px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:image {"id":509,"sizeSlug":"large","linkDestination":"none","style":{"border":{"radius":"4px"}}} -->
<figure class="wp-block-image size-large" style="border-radius:4px"><img src="https://jameskoster.design/wp-content/uploads/2021/06/image-from-rawpixel-id-3065120-jpeg-1350x2000.jpg" alt="" class="wp-image-509"/></figure>
<!-- /wp:image --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div></div>
<!-- /wp:cover -->
```

**Comment by melchoyce** [comment]
Looks good to me 👍

**Comment by kjellr** [comment]
Thanks everyone! This one is live in the directory: https://wordpress.org/patterns/pattern/offset-gallery-with-fixed-background-and-quote/
