### ISSUE TITLE
Pattern display bugs

### ISSUE THREAD

**Issue by kjellr** [WordPress/pattern-directory#156]
As we continue populating the directory, we're running into some visual bugs with the pattern previews. I'm consolidating a list here of bugs.

---

- [x] **Display is cut off**

1. https://wordpress.org/patterns/pattern/centered-introduction-text-with-button-and-offset-images/
2. https://wordpress.org/patterns/pattern/title-area-with-image-and-heading/
3. https://wordpress.org/patterns/pattern/introduction-with-image-on-the-left/

Editor|Preview
---|---
![templates-editor](https://user-images.githubusercontent.com/1202812/121545710-c038d100-c9d8-11eb-84c2-5068d1321eab.gif)|<img width="1164" alt="Screen Shot 2021-06-10 at 10 42 54 AM" src="https://user-images.githubusercontent.com/1202812/121545714-c0d16780-c9d8-11eb-82b3-fecceadfd8c1.png">

<img width="1354" alt="Screen Shot 2021-06-10 at 2 22 27 PM" src="https://user-images.githubusercontent.com/1202812/121577221-50860e80-c9f7-11eb-98b2-961f6391195f.png">

<img width="1354" alt="Screen Shot 2021-06-10 at 2 22 12 PM" src="https://user-images.githubusercontent.com/1202812/121577207-4d8b1e00-c9f7-11eb-90f1-5fc5a935d8d1.png">

---

- [x] **Missing social links block**

1. https://wordpress.org/patterns/pattern/team-social-cards/
2. https://wordpress.org/patterns/pattern/contact-and-social-links/

Editor|Preview
---|---
<img width="1269" alt="Screen Shot 2021-06-10 at 10 48 30 AM" src="https://user-images.githubusercontent.com/1202812/121546620-6f75a800-c9d9-11eb-9df4-2f43a4ac43b3.png">|<img width="943" alt="121382990-1d6b4e80-c915-11eb-8fde-e3b26bbaf01a" src="https://user-images.githubusercontent.com/1202812/121546625-700e3e80-c9d9-11eb-9417-7b1c6ac7e27f.png">

Editor|Preview
---|---
<img width="841" alt="Screen Shot 2021-06-10 at 2 23 59 PM" src="https://user-images.githubusercontent.com/1202812/121577510-93e07d00-c9f7-11eb-9d3a-10ba82f5db18.png">|<img width="1354" alt="Screen Shot 2021-06-10 at 2 23 45 PM" src="https://user-images.githubusercontent.com/1202812/121577513-94791380-c9f7-11eb-8be8-8fb314f85f17.png">

---

- [x] **Wide-width images not displaying correctly**

For these patterns, wide-width images appear off to the left in the previews. 

Examples: 
1. https://wordpress.org/patterns/pattern/centered-introduction-text-with-button-and-offset-images/
2. https://wordpress.org/patterns/pattern/event-details/

Editor|Preview
---|---
<img width="1138" alt="Screen Shot 2021-06-09 at 8 17 11 AM" src="https://user-images.githubusercontent.com/1202812/121352691-19cace00-c8fb-11eb-9424-669a0163f2c4.png">|<img width="959" alt="Screen Shot 2021-06-09 at 8 17 01 AM" src="https://user-images.githubusercontent.com/1202812/121352699-1afbfb00-c8fb-11eb-859e-71d7dda96064.png">

Editor|Preview
---|---
<img width="1271" alt="Screen Shot 2021-06-10 at 10 50 29 AM" src="https://user-images.githubusercontent.com/1202812/121546962-ba8fbb00-c9d9-11eb-95bf-8d0cd5bed829.png">|<img width="1270" alt="Screen Shot 2021-06-10 at 10 50 03 AM" src="https://user-images.githubusercontent.com/1202812/121546972-bbc0e800-c9d9-11eb-8339-b912c663aaa8.png">

---

- [x] **Extra space on the left/right of full-width items**

Examples: 

1. https://wordpress.org/patterns/pattern/button-links-with-image-background/
2. https://wordpress.org/patterns/pattern/introduction-with-image-on-the-left/

<img width="1354" alt="Screen Shot 2021-06-10 at 2 33 46 PM" src="https://user-images.githubusercontent.com/1202812/121578626-deaec480-c9f8-11eb-97e3-8e0657ac6406.png">

<img width="1354" alt="Screen Shot 2021-06-10 at 2 36 06 PM" src="https://user-images.githubusercontent.com/1202812/121578902-31887c00-c9f9-11eb-8e16-5f1550069996.png">

**Comment by ryelle** [comment]
@kjellr Thanks for finding these bugs 🙂  Most of these should be fixed now, I think the only one remaining is the alignment issue, which should be fixed once #152  & #164 are merged. Let me know if anything else seems off.

**Comment by kjellr** [comment]
🙌 Thank you!

**Comment by kjellr** [comment]
Adding another bug to the list here: 

- [ ] **Buttons & social links frequently show the wrong text/icon color**

Examples: 

https://wordpress.org/patterns/pattern/introduction-with-image-on-the-left/
https://wordpress.org/patterns/pattern/contact-and-social-links/

Editor|Frontend Preview
---|---
<img width="1105" alt="Screen Shot 2021-06-21 at 8 17 17 AM" src="https://user-images.githubusercontent.com/1202812/122760514-3525c980-d269-11eb-8e4d-bd3272a7ba7a.png">|<img width="1012" alt="Screen Shot 2021-06-21 at 8 17 07 AM" src="https://user-images.githubusercontent.com/1202812/122760518-3656f680-d269-11eb-9c68-7e331a341bc6.png">

Editor|Frontend Preview
---|---
<img width="1105" alt="Screen Shot 2021-06-21 at 8 17 35 AM" src="https://user-images.githubusercontent.com/1202812/122760532-3bb44100-d269-11eb-8a6d-dde5a4bed497.png">|<img width="1020" alt="Screen Shot 2021-06-21 at 8 16 11 AM" src="https://user-images.githubusercontent.com/1202812/122760544-3e169b00-d269-11eb-9129-7f441b46f8a2.png">

**Comment by ryelle** [comment]
@kjellr Having multiple bugs in this one issue makes it hard (for me) to know what's done/what's still a problem. Could you create new issues for the things that are still valid?

**Comment by kjellr** [comment]
Sure thing. I think just that last one is valid. I'll close this and migrate that into a new issue.
