### ISSUE TITLE
Add support for all optional theme settings

### ISSUE THREAD

**Issue by melchoyce** [WordPress/pattern-directory#157]
The theme currently doesn't support things like wide/full-width alignment or line-height. Can we add support for all of the optional theme settings?

**Comment by kjellr** [comment]
Also, [custom spacing](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-support/#spacing-control) and [custom link color](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-support/#experimental-link-color-control).
