### ISSUE TITLE
Pattern Submission: Triptych with two images and a text area

### ISSUE THREAD

**Issue by kjellr** [WordPress/pattern-directory#159]
I originally designed this one to have the images edge-to-edge, but that's not possible until we can control the gutter width for the columns block. 

![Frame 13](https://user-images.githubusercontent.com/1202812/121584739-ca21fa80-c9ff-11eb-999f-92930036d436.png)

I still think it might be worth including in the meantime though: 

<img width="1440" alt="Screen Shot 2021-06-10 at 3 43 04 PM" src="https://user-images.githubusercontent.com/1202812/121587234-8e3c6480-ca02-11eb-99f3-2b8c47e4547e.png">

---

## Pattern Title

Triptych with two images and a text area

## Pattern Categories

Header, Gallery

## Image Credits

Photo from the Apollo 16 Hasselblad Mission. CC0
https://www.flickr.com/photos/136485307@N06/21512525940

Experimento de astigmatismo. CC0
https://www.flickr.com/photos/37667416@N04/4051848937
(This one is already added to the Patterns Directory site)

## Block Markup

https://gist.github.com/kjellr/e32b46894d153838405d5d3108e1e870

**Comment by melchoyce** [comment]
Aww yeah the edge-to-edge version is super trippy and fun. It's not as impactful with the spacing, but I think it's still worth including. Looks good on small screens, too.

**Comment by melchoyce** [comment]
This one's live! https://wordpress.org/patterns/pattern/triptych-with-two-images-and-a-text-area/
