### ISSUE TITLE
Add ordering support when browsing patterns

### ISSUE THREAD

**Issue by ryelle** [WordPress/pattern-directory#161]
The pattern grid archives should have an order dropdown in the top right menu area.

I think this should trigger a query string, like `?orderby=date` etc. Featured might just be a category, not an actual ordering parameter, but that's just a suggestion.

<img width="680" alt="Screen Shot 2021-06-10 at 3 57 22 PM" src="https://user-images.githubusercontent.com/541093/121588982-8bdb0a00-ca04-11eb-8aa6-44c2822f7799.png">

<img width="232" alt="Screen Shot 2021-06-10 at 3 59 20 PM" src="https://user-images.githubusercontent.com/541093/121589224-d3619600-ca04-11eb-85ba-76b2d4d79f9d.png">

Same on My Patterns & Favorites, but no Featured.

<img width="821" alt="Screen Shot 2021-06-10 at 3 57 49 PM" src="https://user-images.githubusercontent.com/541093/121589043-9c8b8000-ca04-11eb-8895-f708e3ca197b.png">

**Comment by StevenDufresne** [comment]
@ryelle @shaunandrews

Did we want to launch with the featured category? I feel like it's a nice-to-have because the management of that category adds complexity.

Also, we have a sort by "Date" but it's unidirectional. Would the label "Newest" make more sense?

**Comment by ryelle** [comment]
No, I think it's late to introduce featured for launch, but it should be added shortly after, maybe a new taxonomy like "Browse" in plugins. Not required to fix this issue.

> Also, we have a sort by "Date" but it's unidirectional. Would the label "Newest" make more sense?

That's more understandable to me 👍🏻
