### ISSUE TITLE
Link colors aren't displaying

### ISSUE THREAD

**Issue by melchoyce** [WordPress/pattern-directory#162]
**Describe the bug**
Link colors aren't being parsed on the front-end of the patterns: https://wordpress.org/patterns/pattern/event/

**To Reproduce**
1. Create a new pattern. 
2. Add a cover block with a dark background, and inside, add a link.
3. Change the link color.
4. Preview the pattern and see that the link color you chose isn't being displayed.

**Expected behavior**
The link would be the color I chose in the editor.

**Screenshots**

Editor | Front-end
------------ | -------------
![image](https://user-images.githubusercontent.com/2846578/121594633-58e84480-ca0b-11eb-8be2-c9b161a32527.png) | ![image](https://user-images.githubusercontent.com/2846578/121594674-66053380-ca0b-11eb-9f92-b755259d6c83.png)

**Comment by ryelle** [comment]
I'm pretty sure the same issue is what's causing the social links thing mentioned in #156

**Comment by ryelle** [comment]
@melchoyce is this working now? I believe #177 should have fixed it.

**Comment by melchoyce** [comment]
Yup! Thanks 👍
