### ISSUE TITLE
Pattern Directory Discoverability

### ISSUE THREAD

**Issue by bph** [WordPress/pattern-directory#163]
After I saw [Ana's tweet](https://twitter.com/Ana_Segota/status/1402714564366684163), I wanted to check out her patterns, and couldn't find just her patterns. It would be not only attractive for pattern authors, if attribution would be visible and link able. 

Use cases: 
- Sharable link `patterns/anarieldesign`
- display on author's wp.org profile next to themes and plugins. 
- Filter by on pattern directory, similar to plugin & themes
- Add author name to cards on single pattern view with link to profile page.

_It seems to be on the road map as the single page says "More from this designer"_
cc @anarieldesign

**Comment by melchoyce** [comment]
Hey @bph! This is incoming. See: https://github.com/WordPress/pattern-directory/pull/152
