### ISSUE TITLE
Creator: UI allows suggest `320px` but API min is `400px`

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/pattern-directory#167]
**Describe the bug**
Our viewport control suggests using a narrow layout at `320px` but the API restricts the value to have a minimum `400px`. 

What should happen? Do we reduce the API min down from 400 to 320 (is that an arbitrary number?) or do we update the UI?

https://github.com/WordPress/pattern-directory/blob/e69788eb194e390ecb98b78e00861028a83cf892/public_html/wp-content/plugins/pattern-creator/src/plugins/viewport-header-control.js#L24

https://github.com/WordPress/pattern-directory/blob/e69788eb194e390ecb98b78e00861028a83cf892/public_html/wp-content/plugins/pattern-directory/includes/pattern-post-type.php#L141

**Comment by StevenDufresne** [comment]
Also, the error message could use some improvement:

![](https://d.pr/i/jL4fDa.png)

**Comment by ryelle** [comment]
For what it's worth, 400 was an arbitrary number.

I don't know what realistic values are here. To figure it out, I would create a demo plugin to [register 3 or so patterns](https://developer.wordpress.org/reference/functions/register_block_pattern/) from the directory, and see how they look in the gutenberg inserter previews with different viewportWidths.
