### ISSUE TITLE
Forking a pattern

### ISSUE THREAD

**Issue by MichaelArestad** [WordPress/pattern-directory#17]
Allowing users to fork a pattern seems like a pretty cool way for patterns to evolve over time and for users to efficiently create their own patterns. I'm starting to work in this flow as it seems like a rather frictionless entry into the pattern editor.

[Try the prototype](https://www.figma.com/proto/bz4qs4jZCkqvQzPH2fmX6C/Pattern-Directory?node-id=148%3A0&viewport=198%2C842%2C0.5&scaling=min-zoom).

![2020-11-09 16 56 59](https://user-images.githubusercontent.com/1123119/98611058-62130680-22ae-11eb-8ee3-a2590bc84dfc.gif)

Note: This prototype goes right into editing, but I am planning a pattern submission intro modal to introduce the user to the process. I will address this in another issue.

## Screenshot

![remix](https://user-images.githubusercontent.com/1123119/98610859-de591a00-22ad-11eb-93fa-a3df13ba8544.jpg)

## Questions

What should the action be? Remix? Duplicate? Something else?
Should the forked pattern be referenced by the new pattern in its details page?

**Comment by tellyworth** [comment]
> Note: This prototype goes right into editing, but I am planning a pattern submission intro modal to introduce the user to the process.

Yeah anything that gives some context would help a lot. Otherwise it looks exactly like a post editor.

> What should the action be? Remix? Duplicate?

I like Remix, but that needs some discussion. There's also Adapt, Remake, or a longer phrase like "Copy and modify".

> Should the forked pattern be referenced by the new pattern in its details page?

It definitely should if the purpose of forking is to translate it. But that probably warrants a separate button. We could track forking easily enough, as long as it's made clear that it's strictly info only - there is no syncing or merging or anything like that on the cards. "Adapted from pattern xxx by yyy" or similar.

**Comment by MichaelArestad** [comment]
> We could track forking easily enough, as long as it's made clear that it's strictly info only - there is no syncing or merging or anything like that on the cards. "Adapted from pattern xxx by yyy" or similar.

Right. I don't want anything updated from the original. Just a way to see where the pattern was forked from and also give the original pattern creator some credit. Down the road, it could be interested to display how a pattern evolved.

**Comment by coreymckrill** [comment]
Now that we have a locale field (#229) for patterns, here is an idea for the flows of the two "forking" buttons:

**Translate this**

1. Click the button on the single pattern screen
2. Field or modal appears prompting the user to choose the new locale for the translated pattern
3. Confirming this choice loads a new pattern editor screen with the same pattern content but a new value in the locale picker field
4. On the back end, this would create a new pattern post with the same post content, the current user as the post author, the original pattern ID in the `post_parent`, and the post status set to `draft`

**Remix**

1. This would be the same flow as "Translate this" but without the prompt for a new locale

**Comment by ryelle** [comment]
Since we're not using the "fork" flow to translate patterns, I'm going to close this issue. If remixing is a requested feature later, we can revisit the idea.
