### ISSUE TITLE
Pattern Submission: Simple follow social adventures

### ISSUE THREAD

**Issue by karmatosed** [WordPress/pattern-directory#170]
This pattern is a very simple social media follow with a picture, header and social icons. This is all wrapped in a block that can have background set and a spacer block so it's easy to custom visually to the theme someone is using.

---

## Pattern Title
Simple social media and follow pattern with an image.

## Pattern Categories
Columns, Social Icons, Image, Heading

## Screenshots
Screenshots taken using TT1 latest build and blocks made using fresh local install so nothing fancy.

![image](https://user-images.githubusercontent.com/253067/121681175-63a9e480-cab2-11eb-8d6a-2996de38ac8e.png)

Smaller screens:
![image](https://user-images.githubusercontent.com/253067/121681283-84723a00-cab2-11eb-872c-d2f9785f57e2.png)

In content:

![image](https://user-images.githubusercontent.com/253067/121681786-209c4100-cab3-11eb-8371-61fc94f31f55.png)

## Image Credits
https://www.rawpixel.com/image/573342/stormy-seascape-drawing

## Block Markup
```
<!-- wp:group -->
<div class="wp-block-group"><div class="wp-block-group__inner-container"><!-- wp:columns {"style":{"color":{"background":"#f5f5f5"}}} -->
<div class="wp-block-columns has-background" style="background-color:#f5f5f5"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:image {"id":11,"width":256,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="http://patterns.local/wp-content/uploads/2021/06/image-from-rawpixel-id-573342-jpeg-edited.jpg" alt="" class="wp-image-11" width="256"/></figure>
<!-- /wp:image --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:spacer {"height":25} -->
<div style="height:25px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:heading {"level":5,"fontSize":"normal"} -->
<h5 class="has-normal-font-size">Follow my adventures</h5>
<!-- /wp:heading -->

<!-- wp:separator {"className":"is-style-default"} -->
<hr class="wp-block-separator is-style-default"/>
<!-- /wp:separator -->

<!-- wp:social-links {"className":"is-style-twentytwentyone-social-icons-color"} -->
<ul class="wp-block-social-links is-style-twentytwentyone-social-icons-color"><!-- wp:social-link {"url":"https://myemail.com","service":"mail"} /-->

<!-- wp:social-link {"url":"http://twitter.com/twitter","service":"twitter"} /-->

<!-- wp:social-link {"url":"http://facebook.com/facebook","service":"facebook"} /--></ul>
<!-- /wp:social-links --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div></div>
<!-- /wp:group -->
```

**Comment by melchoyce** [comment]
I like how clean and simple this is, but I wish there was a way to center the content on smaller screens :(

**Comment by karmatosed** [comment]
I sort of like the way it feels like a bookmark, but that might be my accepting of our current tools not having that ability to center.

**Comment by kjellr** [comment]
I think we can get around the centering issue if we switch to a rectangular image. What do you folks think of this? 

Desktop|Mobile
---|---
<img width="643" alt="Screen Shot 2021-06-15 at 9 06 02 AM" src="https://user-images.githubusercontent.com/1202812/122057856-0dda8280-cdb9-11eb-9968-fed0a4ee91e9.png">|<img width="359" alt="Screen Shot 2021-06-15 at 9 06 16 AM" src="https://user-images.githubusercontent.com/1202812/122057859-0e731900-cdb9-11eb-9dd8-f3cdd542d5f3.png">


```
<!-- wp:columns {"verticalAlignment":null,"style":{"color":{"background":"#fafafa"}}} -->
<div class="wp-block-columns has-background" style="background-color:#fafafa"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:image {"id":307,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large"><img src="https://patterns-demo.mystagingwebsite.com/wp-content/uploads/2021/06/boat-etching-cropped-1024x1024.png" alt="" class="wp-image-307"/></figure>
<!-- /wp:image --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center"} -->
<div class="wp-block-column is-vertically-aligned-center"><!-- wp:heading {"level":5,"fontSize":"normal"} -->
<h5 class="has-normal-font-size">Follow my adventures</h5>
<!-- /wp:heading -->

<!-- wp:separator {"className":"is-style-default"} -->
<hr class="wp-block-separator is-style-default"/>
<!-- /wp:separator -->

<!-- wp:social-links {"className":"is-style-twentytwentyone-social-icons-color"} -->
<ul class="wp-block-social-links is-style-twentytwentyone-social-icons-color"><!-- wp:social-link {"url":"https://myemail.com","service":"mail"} /-->

<!-- wp:social-link {"url":"http://twitter.com/twitter","service":"twitter"} /-->

<!-- wp:social-link {"url":"http://facebook.com/facebook","service":"facebook"} /--></ul>
<!-- /wp:social-links --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

Sea ship from Real Sailor-Songs. Collected And Edited By J. Ashton. CC0
https://www.rawpixel.com/image/572566/sailing-ship-vintage-drawing

**Comment by melchoyce** [comment]
Yeah, I think the rectangular image helps a lot. LGTM 👍

**Comment by karmatosed** [comment]
Works for me, thanks for iteration.

**Comment by melchoyce** [comment]
Added! https://wordpress.org/patterns/pattern/follow-card/
