### ISSUE TITLE
Pattern submission: Introduction cover

### ISSUE THREAD

**Issue by karmatosed** [WordPress/pattern-directory#173]
Cover images are great, but sometimes you need more. This is a cover section that takes it lead from book introduction pages. It has a title, a subtitle and then a little bit of text to lead into the post. All this wrapped in a block with a background.

---

## Pattern Title
Introduction cover

## Pattern Categories
Cover, Header

## Screenshots
![image](https://user-images.githubusercontent.com/253067/121739977-50b80400-caf4-11eb-8709-073479c1c02b.png)

![image](https://user-images.githubusercontent.com/253067/121740029-62011080-caf4-11eb-8290-d2e7e69829e4.png)

## Image Credits
https://www.rawpixel.com/image/2049906/japanese-woodcut-print-kamisaka-sekka#eyJkYXRhIjp7ImtleXMiOiJzdW4iLCJwYWdlIjoxLCJzb3J0IjoiY3VyYXRlZCIsImZyZWVjYzAiOjEsImN1cnJlbnRfdXJsIjoiL3NlYXJjaC9zdW4/

## Block Markup
```
<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"0px","bottom":"0px"}}},"backgroundColor":"white"} -->
<div class="wp-block-group alignfull has-white-background-color has-background" style="padding-top:0px;padding-bottom:0px"><div class="wp-block-group__inner-container"><!-- wp:columns {"align":"full"} -->
<div class="wp-block-columns alignfull"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:cover {"url":"http://patterns.local/wp-content/uploads/2021/06/image-from-rawpixel-id-2049906-jpeg-scaled.jpg","id":164,"dimRatio":0,"minHeight":891,"minHeightUnit":"px"} -->
<div class="wp-block-cover" style="min-height:891px"><img class="wp-block-cover__image-background wp-image-164" alt="" src="http://patterns.local/wp-content/uploads/2021/06/image-from-rawpixel-id-2049906-jpeg-scaled.jpg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"align":"center","placeholder":"Write title…","fontSize":"large"} -->
<p class="has-text-align-center has-large-font-size"></p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"style":{"spacing":{"padding":{"top":"10px","bottom":"40px"}}}} -->
<div class="wp-block-group" style="padding-top:10px;padding-bottom:40px"><div class="wp-block-group__inner-container"><!-- wp:spacer {"height":11} -->
<div style="height:11px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:heading {"fontSize":"huge"} -->
<h2 class="has-huge-font-size"><strong>1. A FABLE</strong></h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"style":{"color":{"text":"#989898"}}} -->
<p class="has-text-color" style="color:#989898">Persuasion is better than force</p>
<!-- /wp:paragraph -->

<!-- wp:spacer {"height":435} -->
<div style="height:435px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p>A dispute arose between the North Wind and the Sun, each claiming that he was stronger than the other.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div></div>
<!-- /wp:group -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph -->
```

**Comment by kjellr** [comment]
I'm not sure about this one — It feels similar to some others that we have already: 

https://wordpress.org/patterns/pattern/half-width-image-of-artistic-squares-with-text/
https://wordpress.org/patterns/pattern/introduction-with-image-on-the-left/
https://wordpress.org/patterns/pattern/title-area-with-image-and-heading/

I'm curious what other folks think.

**Comment by karmatosed** [comment]
I wasn't aware of those, however are we having a limit on patterns? For me the one I offered is different enough.

**Comment by shaunandrews** [comment]
To start, I think its best to avoid having too many similar patterns and instead favor more discrete designs. While I do like your design, I agree with Kjell that there are existing patterns that are similar.

**Comment by kjellr** [comment]
Yeah, I think we should leave this one out for now, and pursue more varied patterns for this initial collection. I'm going to close this for now. 

Thanks!
