### ISSUE TITLE
Two Image & Text sections with shared colored strip

### ISSUE THREAD

**Issue by mateuswetah** [WordPress/pattern-directory#174]
I feel like we could show everyone how _gradients are a powerful tool_. I myself enjoy playing with it to create background-color transitions and section divisions, like this one. I uploaded two groups considering that maybe we should send only one, but I like the combination of a couple. Anyways, open to suggestions and comments guys, hope you like!

---

## Pattern Title
Two Image & Text sections with shared colored strip

## Pattern Categories
Columns

## Screenshots

Desktop:
![image](https://user-images.githubusercontent.com/1184874/121749075-70ddc800-cae0-11eb-9ef8-e8c3a3ffe9b0.png)

Mobile:
![Screenshot 2021-06-11 at 18-12-05 Block Patterns](https://user-images.githubusercontent.com/1184874/121749205-a4b8ed80-cae0-11eb-9d25-1273539667a2.png)

## Image Credits
- https://www.rawpixel.com/image/547292/monet-woman-painting
- https://www.rawpixel.com/image/2680233/free-illustration-image-monet-claude-monet-painting

## Block Markup
```html
<!-- wp:group {"align":"full","style":{"color":{"gradient":"linear-gradient(180deg,rgb(209,228,221) 50%,rgb(238,234,221) 50%)"},"spacing":{"padding":{"top":"16px","right":"16px","bottom":"16px","left":"16px"}}},"textColor":"dark-gray"} -->
<div class="wp-block-group alignfull has-dark-gray-color has-text-color has-background" style="background:linear-gradient(180deg,rgb(209,228,221) 50%,rgb(238,234,221) 50%);padding-top:16px;padding-right:16px;padding-bottom:16px;padding-left:16px"><div class="wp-block-group__inner-container"><!-- wp:columns {"verticalAlignment":"center","align":"wide","textColor":"dark-gray"} -->
<div class="wp-block-columns alignwide are-vertically-aligned-center has-dark-gray-color has-text-color"><!-- wp:column {"verticalAlignment":"center","width":"20%"} -->
<div class="wp-block-column is-vertically-aligned-center" style="flex-basis:20%"><!-- wp:image {"align":"center","sizeSlug":"large","linkDestination":"none"} -->
<div class="wp-block-image"><figure class="aligncenter size-large"><img src="https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/pdproject56batch70-19-kwan_2.jpg?w=800&amp;dpr=1&amp;fit=default&amp;crop=default&amp;q=65&amp;vib=3&amp;con=3&amp;usm=15&amp;bg=F4F4F3&amp;ixlib=js-2.2.1&amp;s=8582220b6f69c69924e23bfeacc26375" alt=""/></figure></div>
<!-- /wp:image --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"3%"} -->
<div class="wp-block-column" style="flex-basis:3%"></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center"} -->
<div class="wp-block-column is-vertically-aligned-center"><!-- wp:paragraph {"textColor":"dark-gray","fontSize":"extra-large"} -->
<p class="has-dark-gray-color has-text-color has-extra-large-font-size">I look at the water<br><strong>down bellow</strong>...</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"color":{"gradient":"linear-gradient(0deg,rgb(209,228,221) 50%,rgb(238,234,221) 50%)"},"spacing":{"padding":{"top":"16px","right":"16px","bottom":"16px","left":"16px"}}},"textColor":"dark-gray"} -->
<div class="wp-block-group alignfull has-dark-gray-color has-text-color has-background" style="background:linear-gradient(0deg,rgb(209,228,221) 50%,rgb(238,234,221) 50%);padding-top:16px;padding-right:16px;padding-bottom:16px;padding-left:16px"><div class="wp-block-group__inner-container"><!-- wp:columns {"verticalAlignment":"center","align":"wide","textColor":"dark-gray"} -->
<div class="wp-block-columns alignwide are-vertically-aligned-center has-dark-gray-color has-text-color"><!-- wp:column {"verticalAlignment":"center","width":""} -->
<div class="wp-block-column is-vertically-aligned-center"><!-- wp:paragraph {"align":"right","textColor":"dark-gray","fontSize":"extra-large"} -->
<p class="has-text-align-right has-dark-gray-color has-text-color has-extra-large-font-size">...I see your reflection,<br><strong>starring me.</strong></p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"3%"} -->
<div class="wp-block-column" style="flex-basis:3%"></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center","width":"20%"} -->
<div class="wp-block-column is-vertically-aligned-center" style="flex-basis:20%"><!-- wp:image {"align":"center","sizeSlug":"large","linkDestination":"none"} -->
<div class="wp-block-image"><figure class="aligncenter size-large"><img src="https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/pdmonet-a41391.jpg?w=800&amp;dpr=1&amp;fit=default&amp;crop=default&amp;q=65&amp;vib=3&amp;con=3&amp;usm=15&amp;bg=F4F4F3&amp;ixlib=js-2.2.1&amp;s=fd13948c3395db76953dddeaf1f40878" alt=""/></figure></div>
<!-- /wp:image --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div></div>
<!-- /wp:group -->
```

**Comment by kjellr** [comment]
Cool idea! I used a gradient to similar effect for one of the [Seedlet theme](https://wordpress.org/themes/seedlet/)'s patterns: 

<img width="658" alt="Screen Shot 2021-06-15 at 2 33 00 PM" src="https://user-images.githubusercontent.com/1202812/122105362-b05d2a80-cde6-11eb-9659-1e3a33ce8348.png">

I do think that modifying this sort of gradient is a little advanced for most users, so I don't think we should use it in too many patterns to start with. But it's worth a try for one or two. I think this effect is a little more successful without having the text sit along the edges of the divider, and I've also been looking for a place to try out these weird public domain tarot images I found recently — so while this is a little different from the original proposal, what if we did something like this?

<img width="1210" alt="Screen Shot 2021-06-15 at 3 00 20 PM" src="https://user-images.githubusercontent.com/1202812/122108728-8ad22000-cdea-11eb-9a1e-74d15f01c6f2.png">

Markup for this is here: 
https://gist.github.com/kjellr/30d703b50dabb99ddffee4051994ac64

Images:
https://www.flickr.com/photos/circasassy/25929791244
https://www.flickr.com/photos/circasassy/26489969295/

**Comment by mateuswetah** [comment]
Hey @kjellr, I'm a big fan of your theme!

I agree with the suggestions, it should be used for more simple layouts

**Comment by mateuswetah** [comment]
So should I close this and you open a new one, or should I update the issue description with one using just images?

**Comment by kjellr** [comment]
We can keep using the same issue. 🙂

**Comment by beafialho** [comment]
I like the tarot one, let's do it!

**Comment by kjellr** [comment]
Thank everyone! The tarot pattern is live in the directory: 

https://wordpress.org/patterns/pattern/two-images-with-shared-colored-strip/
