### ISSUE TITLE
Chapter Opening

### ISSUE THREAD

**Issue by melchoyce** [WordPress/pattern-directory#175]
This pattern is a bold, type-driven design that can be used for blogs and storytellers.

---

## Pattern Title
Chapter Opening

## Pattern Categories
Text

## Screenshots
![image](https://user-images.githubusercontent.com/2846578/121750658-cadb8f00-cada-11eb-8886-c6b1cd589de1.png)

## Block Markup
https://gist.github.com/melchoyce/c42c931a78a1118487c326ed8eb5dd35

**Comment by kjellr** [comment]
Thanks! I've added this to the directory: 

https://wordpress.org/patterns/pattern/chapter-opening/
