### ISSUE TITLE
Poster

### ISSUE THREAD

**Issue by melchoyce** [WordPress/pattern-directory#176]
This pattern mimics a printed poster, with text inlayed inside of cover block. Its elegant design would work well for many combinations of images and text.

---

## Pattern Title
Poster

## Pattern Categories
Header, Image

## Screenshots
![image](https://user-images.githubusercontent.com/2846578/121751674-9cf74a00-cadc-11eb-854a-a0a1ef7a27a2.png)

## Image Credits
Mount Fuji from Momoyogusa–Flowers of a Hundred Generations (1909) by Kamisaka Sekka. CC0.
https://www.rawpixel.com/image/2049919/japanese-woodcut-print-kamisaka-sekka

## Block Markup
https://gist.github.com/melchoyce/46d3149a577faad969b55ce0d1e9453c

**Comment by kjellr** [comment]
Looks great, thanks @melchoyce. This one is all set to add to the directory.

**Comment by kjellr** [comment]
Added here: 

https://wordpress.org/patterns/pattern/poster-layout/
