### ISSUE TITLE
Call To Action Horizontal

### ISSUE THREAD

**Issue by schutzsmith** [WordPress/pattern-directory#181]
A common design pattern, a call to action provides a way to capture the viewers attention without being overwhelming.

---

## Pattern Title
Call to Action Horizontal

## Pattern Categories
Buttons, Header

## Screenshots
<img width="1272" alt="Screen Shot 2021-06-14 at 11 45 46 AM" src="https://user-images.githubusercontent.com/680204/121920613-39e8fb80-cd06-11eb-8399-b935443401df.png">

## Block Markup
https://gist.github.com/schutzsmith/277aad4fb03a18efbecea4b806252cae

**Comment by schutzsmith** [comment]
Updated text to better example.

**Comment by melchoyce** [comment]
Thanks @schutzsmith, added this one to the directory: https://wordpress.org/patterns/pattern/horizontal-call-to-action/

**Comment by schutzsmith** [comment]
@melchoyce Thanks!
