### ISSUE TITLE
Call To Action Vertical

### ISSUE THREAD

**Issue by schutzsmith** [WordPress/pattern-directory#182]
A common design pattern, a call to action provides a way to capture the viewers attention without being overwhelming.

---

## Pattern Title
Call To Action Vertical

## Pattern Categories
Header, Buttons

## Screenshots
<img width="707" alt="Screen Shot 2021-06-13 at 1 24 51 PM" src="https://user-images.githubusercontent.com/680204/121816641-c59d5200-cc4a-11eb-9096-1b5dcb016fda.png">

## Block Markup
https://gist.github.com/schutzsmith/46023053c44b3033a774dc2f0e9dc81a

**Comment by kjellr** [comment]
Hi @schutzsmith! Thanks for the pattern submission. For this one, I have similar feedback to what I noted in https://github.com/WordPress/pattern-directory/issues/183#issuecomment-860656295. Here's a suggested edit which pulls in more "real-world" content. I also modified one of the button styles so there's a clear primary call-to-action. Let me know what you think!

<img width="730" alt="Screen Shot 2021-06-14 at 9 17 53 AM" src="https://user-images.githubusercontent.com/1202812/121898494-6fcfb500-ccf1-11eb-9d4d-35055cd5328c.png">


```
<!-- wp:heading {"textAlign":"center"} -->
<h2 class="has-text-align-center"><strong>Jean-Michel Basquiat</strong></h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","textColor":"gray"} -->
<p class="has-text-align-center has-gray-color has-text-color">The Museum of Art is proud to present <em>Basquiat: 1981–1986</em>. This collection includes many iconic works from the artist's prolific career. The show will be on view in the Franklin gallery from June 14th through August 28th. Please reserve tickets in advance.</p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"contentJustification":"center"} -->
<div class="wp-block-buttons is-content-justification-center"><!-- wp:button {"className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link">Information</a></div>
<!-- /wp:button -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link">Buy Tickets</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->
```

**Comment by kjellr** [comment]
Actually, I just noticed this is very similar to the pattern submitted in https://github.com/WordPress/pattern-directory/issues/155#issuecomment-859767501. I suggest we close this one in favor of the existing submission there. 

Thank you for the submission!
