### ISSUE TITLE
My Patterns filter URLs can lead to broken pages

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/pattern-directory#187]
I'm able to wind up at a broken page like this:

<img width="1593" alt="image" src="https://user-images.githubusercontent.com/191598/121960675-674c9e00-cd34-11eb-88a7-a8c6f013669b.png">

To do so, head to `/my-patterns/` and then use the filter to switch between All to Drafts. Notice that your browser's address bar will now show the URL as `my-patterns/drafts/`.

Hit refresh. Or, browse to a pattern and use the back button. You'll find yourself looking at a broken page like in the screenshot above.

**Comment by ryelle** [comment]
The My Patterns code is still in progress in #152, and this was fixed in that PR about an hour ago https://github.com/WordPress/pattern-directory/pull/152#issuecomment-860976671
