### ISSUE TITLE
Improve loading state to avoid "page jumping"

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/pattern-directory#188]
When browsing through categories the page "jumps" around as patterns are loaded. Here's a quick video to show the behavior:

https://user-images.githubusercontent.com/191598/121961221-21dca080-cd35-11eb-8e22-8394f6a70456.mp4

Perhaps we can retain the height of the page with some skeleton-style placeholders while loading:

<img width="970" alt="image" src="https://user-images.githubusercontent.com/191598/121961379-5cded400-cd35-11eb-9bbf-c20427486b17.png">

**Comment by ryelle** [comment]
This is a duplicate of #101 — we haven't implemented the loading state at all yet.

**Comment by shaunandrews** [comment]
Here I am trying to be helpful and just creating more noise. Sorry about that.
