### ISSUE TITLE
Make category filter "sticky" when scrolling

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/pattern-directory#189]
Currently, when you scroll down the list of patterns the category filter and search box scroll out of view:

https://user-images.githubusercontent.com/191598/121961643-acbd9b00-cd35-11eb-9580-6b3fa78443a4.mp4

It might be nice to have the list of categories and search "stick" to the top of the viewport (below the adminbar) as you scroll.

![pattern-directory-sticky-filters](https://user-images.githubusercontent.com/191598/121962253-81877b80-cd36-11eb-877f-00aa1631e691.gif)

**Comment by ryelle** [comment]
There are only 18 items per page, so it's not that far to scroll up. I'm going to put this into the "Later" milestone, which we'll grab once the things in "Initial Launch" are done.

**Comment by shaunandrews** [comment]
> There are only 18 items per page, so it's not that far to scroll up.

Right, I guess I'm thinking it might make sense to implement some sort of infinite scrolling — the paging is fine, but really adds a lot of friction to the browsing experience.

**Comment by ryelle** [comment]
Infinite scrolling is not a good experience for accessible navigation. We had a "load more" button in an early design, we could revisit that maybe? but the data structure of the site expects pagination, so it won't be a simple change to just swap out the UI. Not impossible, but it should be taken into account.

**Comment by shaunandrews** [comment]
I like infinite scrolling, especially as the number of patterns grows — it removes all friction from the browsing experience. Its very possible I'm alone here, though.

The current page refreshing is pretty jarring. A load more button would be a much better experience, and would likely necessitate a sticky filter list. Here's a quick prototype I made to see how it could feel: https://cdpn.io/shaunandrews/debug/QWpYgRZ/VJrxxEPLxzQr
