### ISSUE TITLE
Pattern Submission: Short text surrounded with round images

### ISSUE THREAD

**Issue by webmandesign** [WordPress/pattern-directory#193]
This pattern makes a short text (such as feature description) more interesting by surrounding it with round/circular images.
Great for presenting a scientific or medical feature on a website.

---

## Pattern Title
Short text surrounded with round images

## Pattern Categories
Columns, Gallery, Text.

## Screenshots

![Short text surrounded with round images](https://user-images.githubusercontent.com/2456735/122422332-59de2080-cf8d-11eb-9e34-b631a8502aea.jpg)

## Image Credits

- https://www.rawpixel.com/image/2206375/mary-altha-nims-artwork
- https://www.rawpixel.com/image/2206377/mary-altha-nims-artwork
- https://www.rawpixel.com/image/2206380/mary-altha-nims-artwork

## Block Markup

https://gist.github.com/webmandesign/8fd00fcf59c90db372f156ec0e476255

**Comment by kjellr** [comment]
I like this one because I think users will wonder how it's built. 

Here's a slightly simplified version for consideration. In addition to some adjustments to the way the columns work, I took out the background color to lighten it up and simplified the text: 

<img width="699" alt="Screen Shot 2021-06-24 at 3 07 16 PM" src="https://user-images.githubusercontent.com/1202812/123319150-0d02c880-d4fe-11eb-9ab5-2adf71bb280d.png">

Markup: https://gist.github.com/kjellr/dc2aa7798b027e1b2deff7969b4c9fcb

I'm interested in other folks' thoughts.

**Comment by beafialho** [comment]
I like this one too, let's add it!

**Comment by beafialho** [comment]
This pattern works nicely with these specific images but I'm not sure it would hold up with others. It's also not the best layout on mobile. However, if everyone thinks it's a good addition to the directory, I do not object.

**Comment by webmandesign** [comment]
Thanks for feedback!

There are indeed multiple ways of approaching this layout and I like your approach @kjellr. In my opinion it also looks good on mobile screens. Though I'm wondering how were you able to set padding with `em` unit?

I use Twenty Twenty-One theme to build patterns for here and that theme does not allow me to choose padding unit. Is this possible only when Gutenberg plugin is active (presuming it contains the feature to choose padding unit in new plugin version)? If so, are there some guidelines for what plugins and themes can be used to build these patterns? Thanks for any info on this.

**Comment by webmandesign** [comment]
Now that I think of it, it makes sense if you use up to date Gutenberg plugin as the pattern directory will be released with WP 5.8 which will contain updated editor too.
So, does this mean I can go ahead and treat myself with Gutenberg plugin when building these patterns? :)

**Comment by kjellr** [comment]
> So, does this mean I can go ahead and treat myself with Gutenberg plugin when building these patterns? :)

Yeah, feel free to use the plugin to create these!

**Comment by melchoyce** [comment]
Published! https://wordpress.org/patterns/pattern/short-text-surrounded-by-round-images/
