### ISSUE TITLE
Pattern Submission: Skewed background feature

### ISSUE THREAD

**Issue by webmandesign** [WordPress/pattern-directory#194]
Highlights features with skewed background, leading viewer's eyes from one feature to another.

---

## Pattern Title

Skewed background feature

## Pattern Categories

Buttons, Text.

## Screenshots

![Skewed background feature](https://user-images.githubusercontent.com/2456735/122430902-45e9ed00-cf94-11eb-844c-05f180a119eb.jpg)

## Image Credits

https://jam-icons.com/

## Block Markup

https://gist.github.com/webmandesign/2ad194d67285697a4571572fb57fa7bb

**Comment by carolinan** [comment]
Here is the feedback you did not ask for =D
I like the use of gradients to create a skewed look like this (similar to Seedlet ). 

I wonder if it would be more impactful without the icons and with larger text.

**Comment by webmandesign** [comment]
@carolinan Hey Carolina! Thanks for your feedback :)

I just recently found out it is now possible to create hard-stop gradients when seeing a [pattern in directory](https://wordpress.org/patterns/pattern/two-images-with-shared-colored-strip/). Though I can imagine editing this type of gradient may prove difficult for users, I tried to test it by creating this block pattern.

I went ahead and tested your suggestion and here is the result (I haven't updated the pattern code yet):

![Skewed background feature](https://user-images.githubusercontent.com/2456735/122639110-4d2a0b80-d0f8-11eb-9f48-cf0bb9b8a4b8.png)

I'll wait for additional feedback to see where this could go.

Thanks again!

Oliver

**Comment by carolinan** [comment]
Yeah they are almost impossible to do with just dragging the handles in the gradient color tool, easier when editing the actual code.

**Comment by melchoyce** [comment]
Hey! I tried simplifying this and making it black for a more stark visual impact:

![image](https://user-images.githubusercontent.com/2846578/124308789-c6355400-db37-11eb-8bb2-3f6087360847.png)

```
<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"13em","bottom":"13em"}},"color":{"gradient":"linear-gradient(150deg,rgba(255,255,255,0) 0%,rgba(255,255,255,0) 25%,rgb(34,34,34) 25%,rgb(17,17,17) 75%,rgba(255,255,255,0) 75%,rgba(248,213,165,0) 100%)"}},"textColor":"white"} -->
<div class="wp-block-group alignfull has-white-color has-text-color has-background" style="background:linear-gradient(150deg,rgba(255,255,255,0) 0%,rgba(255,255,255,0) 25%,rgb(34,34,34) 25%,rgb(17,17,17) 75%,rgba(255,255,255,0) 75%,rgba(248,213,165,0) 100%);padding-top:13em;padding-bottom:13em"><!-- wp:heading {"textAlign":"center","style":{"typography":{"lineHeight":"1.2"}}} -->
<h2 class="has-text-align-center" style="line-height:1.2">Art &amp; Beauté</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center"} -->
<p class="has-text-align-center">Writing that influences modern culture</p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"contentJustification":"center"} -->
<div class="wp-block-buttons is-content-justification-center"><!-- wp:button {"textColor":"white","className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link has-white-color has-text-color" href="#0">Subscribe</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group -->
```

Let me know if this works okay for you :)

**Comment by kjellr** [comment]
👍 I like this simplification here.

This would be the third pattern in the pre-release collection that includes hard-stop gradients. Since they are a little difficult to modify, I think this should be the last one in the set for now.

**Comment by webmandesign** [comment]
@melchoyce Looks much more cool and makes more sense 👍

**Comment by melchoyce** [comment]
Published 🎉 https://wordpress.org/patterns/pattern/slanted-background-with-text-and-a-button/
