### ISSUE TITLE
Pattern Submission: Large call to action

### ISSUE THREAD

**Issue by webmandesign** [WordPress/pattern-directory#198]
Title says it all :)

---

## Pattern Title

Large call to action

## Pattern Categories

Buttons

## Screenshots

![Large call to action](https://user-images.githubusercontent.com/2456735/122451125-1513b300-cfa8-11eb-9ca0-eb916178a41a.jpg)

## Image Credits

https://www.rawpixel.com/image/3286706/free-photo-image-plant-free-nature-leaves-photo-plants

## Block Markup

https://gist.github.com/webmandesign/d389743dda6103f24fbc63ec6fc7caa6

**Comment by beafialho** [comment]
Lovely call to action pattern @webmandesign! My only suggestion is removing the icon to avoid having icons from a whole bunch of different icon sets in the directory. Also it may not show up correctly with some fonts.

Here's how it looks with some fake text:

<img width="1498" alt="Captura de ecrã 2021-06-21, às 16 11 17" src="https://user-images.githubusercontent.com/65220155/122785947-b2722e00-d2ab-11eb-8807-27deb74571f8.png">
<img width="577" alt="Captura de ecrã 2021-06-21, às 16 11 29" src="https://user-images.githubusercontent.com/65220155/122785966-b736e200-d2ab-11eb-8721-2f8400fcb4bd.png">

Let me know what you think.

**Comment by kjellr** [comment]
I think it might make sense to remove the word "Eco" from the headline so we don't have a short word all alone on its own line here: 

<img width="577" alt="Screen Shot 2021-06-21 at 11 29 51 AM" src="https://user-images.githubusercontent.com/1202812/122788128-0701b300-d284-11eb-8b1e-882c6e8817c1.png">

**Comment by beafialho** [comment]
Good catch @kjellr. I think it looks way better:

<img width="585" alt="Captura de ecrã 2021-06-21, às 16 34 40" src="https://user-images.githubusercontent.com/65220155/122788828-a3d94600-d2ae-11eb-9641-6fae0693cb32.png">
<img width="1502" alt="Captura de ecrã 2021-06-21, às 16 34 28" src="https://user-images.githubusercontent.com/65220155/122788845-a76ccd00-d2ae-11eb-98c5-ac97612cee61.png">

**Comment by kjellr** [comment]
Cool! My only other piece of feedback is that I think the line height for the headline seems a little tall — It might make sense to tighten that up a little bit. (I know that's supposed to correspond to the height of the text/buttons on the right, so it might be necessary to trim the copy down a little to make things line up better.) 

I'm curious how this works on smaller screens too — in the markup above, the font size looks a little big, and I know that can lead to weird line breaks.

**Comment by webmandesign** [comment]
Hi guys,

Thanks for the feedback. I've updated the gist and here is changelog:

1. Removed "ECO" text and "♺" entity.
2. Applied copy text.
3. Applied `1.1` line height on the heading.

Result:
![large-call-to-action-2](https://user-images.githubusercontent.com/2456735/122974875-13286600-d393-11eb-8429-347c337cce1b.jpg)

The line height and font size are very much theme controlled, in my opinion. That's why I didn't want to force any specific line height on the heading. I've used the "Huge" font size Twenty Twenty-One theme predefines but I'm really not sure how it's going to be translated to other themes that do not have such font size predefined: whether it falls down to default H2 size as it does not recognize the `has-huge-font-size` CSS class, or whether the actual `96px` inline style will be applied.
(BTW, do you know by any chance whether there are any font size naming standards? For example: extra small, small, medium/regular, large, extra large, giant, huge, gigantic? For theme authors it would be great to use some standardized naming so the classes are portable from a theme to theme.)

Finally, vertical alignment is actually supposed to work this way:

![large-call-to-action-3](https://user-images.githubusercontent.com/2456735/122974897-17548380-d393-11eb-9014-f402f098ce50.jpg)
**Red**: When heading text is longer/larger than the copy text, the copy text is aligned to bottom of heading.
**Blue**: When heading text is short/small and copy text is long, heading is aligned to top of copy text.

**Comment by kjellr** [comment]
👋 Thanks for the followup on this one. Unfortunately, I don't think we can get this one to work nicely on all screen sizes using just what's available in Gutenberg today: 

![responsive](https://user-images.githubusercontent.com/1202812/123968983-c4c42a00-d985-11eb-8347-a01d0967df39.gif)

The only way to get around that would be to make the text size for the headline smaller, but when we do that, I don't think it's quite as impactful: 

<img width="1185" alt="Screen Shot 2021-06-30 at 9 14 29 AM" src="https://user-images.githubusercontent.com/1202812/123968882-a9f1b580-d985-11eb-83f9-ba54dd91c7a2.png">


I think we should leave this one out of the Core pre-release collection for now as a result, but feel free to submit it after launch if you'd like! I look forward to having better responsive type options in Gutenberg someday! Thanks again for the submission.

**Comment by webmandesign** [comment]
> I look forward to having better responsive type options in Gutenberg someday! Thanks again for the submission.

I think if such huge font size is provided by a theme, it should handle its scaling.

But agree that we need responsive setup for custom font size.
