### ISSUE TITLE
Pattern Submission: Call to action with images

### ISSUE THREAD

**Issue by webmandesign** [WordPress/pattern-directory#200]
Call to action with button surrounded with images.

---

## Pattern Title

Call to action with images

## Pattern Categories

Buttons

## Screenshots

![Call to action with images](https://user-images.githubusercontent.com/2456735/122455322-8e150980-cfac-11eb-8b95-40326be3a745.jpg)

## Image Credits

- https://www.rawpixel.com/image/3064491/free-illustration-image-japanese-japan-japanese-art
- https://www.rawpixel.com/image/3064488/free-illustration-image-japanese-japan-woodblock

## Block Markup

https://gist.github.com/webmandesign/c6bdb5aeff94159ddfbe4edec0297bb8

**Comment by melchoyce** [comment]
Made some minor adjustments for balance, and to bring in thematic copy. Let me know if you think this works!

![image](https://user-images.githubusercontent.com/2846578/123445530-f7e17480-d5a5-11eb-95b8-e21a66f573a9.png)

```
<!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column {"width":"35%"} -->
<div class="wp-block-column" style="flex-basis:35%"><!-- wp:heading -->
<h2>Views of Mt. Fuji</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>An exhibition of early 20th century woodblock prints featuring the majesty of Mt. Fuji.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong><a href="#">Learn More →</a></strong></p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"66.66%"} -->
<div class="wp-block-column" style="flex-basis:66.66%"><!-- wp:gallery {"ids":[3499,3498,3506],"columns":2,"linkTo":"none"} -->
<figure class="wp-block-gallery columns-2 is-cropped"><ul class="blocks-gallery-grid"><li class="blocks-gallery-item"><figure><img src="https://mywptesting.site/wp-content/uploads/2021/06/image-from-rawpixel-id-3065130-jpeg-1-1024x1024.jpg" alt="" data-id="3499" data-full-url="https://mywptesting.site/wp-content/uploads/2021/06/image-from-rawpixel-id-3065130-jpeg-1.jpg" data-link="https://mywptesting.site/image-from-rawpixel-id-3065130-jpeg-2/" class="wp-image-3499"/></figure></li><li class="blocks-gallery-item"><figure><img src="https://mywptesting.site/wp-content/uploads/2021/06/image-from-rawpixel-id-3064488-jpeg-1-1024x1024.jpg" alt="" data-id="3498" data-full-url="https://mywptesting.site/wp-content/uploads/2021/06/image-from-rawpixel-id-3064488-jpeg-1.jpg" data-link="https://mywptesting.site/image-from-rawpixel-id-3064488-jpeg-2/" class="wp-image-3498"/></figure></li><li class="blocks-gallery-item"><figure><img src="https://mywptesting.site/wp-content/uploads/2021/06/image-from-rawpixel-id-3063921-jpeg-1024x449.jpg" alt="" data-id="3506" data-full-url="https://mywptesting.site/wp-content/uploads/2021/06/image-from-rawpixel-id-3063921-jpeg-scaled.jpg" data-link="https://mywptesting.site/2021/06/24/cta-with-images/image-from-rawpixel-id-3063921-jpeg/" class="wp-image-3506"/></figure></li></ul></figure>
<!-- /wp:gallery --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

Mount Fuji (ca.1932) print in high resolution by Hiroaki Takahashi. Original from The Los Angeles County Museum of Art. CC0.
https://www.rawpixel.com/image/3063921/free-illustration-image-japan-japanese-art-japanese

Mount Fuji From Hakone (1930) print in high resolution by Hiroaki Takahashi. Original from The Los Angeles County Museum of Art. CC0.
https://www.rawpixel.com/image/3064488/free-illustration-image-japanese-japan-japanese-art

Mount Fuji from Lake Yamanaka print in high resolution by Hiroaki Takahashi (1871–1945). Original from The Los Angeles County Museum of Art. CC0.
https://www.rawpixel.com/image/3065130/free-illustration-image-japan-japanese-japanese-art

**Comment by kjellr** [comment]
I like this iteration — I'm not sure that we have any patterns that use the gallery block actually. 😅 So this would make a great addition.

**Comment by webmandesign** [comment]
@melchoyce Thanks for the iteration! To me it feels more like #209 :)

For this one I went specifically for placing the button in between/after images. The ideal layout would be without spacing between images and button, but I was not able to achieve that with Twenty Twetnty-One theme.

Here is what I wanted to replicate originally:

![interesting-cta](https://user-images.githubusercontent.com/2456735/123509621-d00e1180-d676-11eb-9ad1-61cec56a4279.jpg)

**Comment by melchoyce** [comment]
Ah yeah, not as feasible with current layout options 😕 

For now I've gone ahead and added the gallery version, but feel free to resubmit this with your original vision once the directory opens, @webmandesign! https://wordpress.org/patterns/pattern/introduction-with-gallery/
