### ISSUE TITLE
Pattern Submission: Modern about grid

### ISSUE THREAD

**Issue by 0aveRyan** [WordPress/pattern-directory#201]
A three-column layout with wider center column to highlight a media or embed block.

---

## Pattern Title
Modern about grid

## Pattern Categories
Buttons, Columns

## Screenshots
![Screenshot 2021-06-17 at 12 52 02](https://user-images.githubusercontent.com/9565066/122463792-e75c4900-cf6a-11eb-808e-421b7348f6ed.jpg)

## Image Credits
https://search.creativecommons.org/photos/c4635ec3-7dba-416f-bf4b-b395ca19d180
"Cornet de frites" by jf2c is marked under CC0 1.0. To view the terms, visit https://creativecommons.org/licenses/cc0/1.0/

## Block Markup
https://gist.github.com/0aveRyan/f5ff06180f332971b4c8265de7519df5

**Comment by beafialho** [comment]
Hi @0aveRyan, thank you for your submission! 

@kjellr posted [a few guidelines on the Make WordPress Design blog](https://make.wordpress.org/design/2021/06/23/update-initial-patterns-for-the-patterns-directory/) and, for this initial set pre-release, we've been trying to upload patterns that draw inspiration from history, art, and nature, like the patterns that are currently bundled with Gutenberg, to share a common thread.

This is also a relatively complicated pattern, and we’ve found that limiting the number of elements makes things easier for users to edit.

I'm closing this issue for now, but feel free to re-submit your pattern once the directory launches.
