### ISSUE TITLE
Three Column (How It Works) Panel

### ISSUE THREAD

**Issue by chrislema** [WordPress/pattern-directory#202]
---

## Pattern Title
Three column (How It Works) Panel

## Pattern Categories
Columns, Images, Text

## Screenshots
<img width="791" alt="Lema-Pattern-How-It-Works" src="https://user-images.githubusercontent.com/581204/122488800-125a9300-cf93-11eb-936e-d9d16c7666ae.png">

## Image Credits
https://unsplash.com/photos/bXfQLglc81U
https://unsplash.com/photos/XJXWbfSo2f0
https://unsplash.com/photos/6lcT2kRPvnI

## Block Markup
https://gist.github.com/chrislema/b11165e5e4d7398ea45527f7af18bbac

**Comment by webmandesign** [comment]
Hey Chris!

Great to see a pattern from you here! :)
This is just a friendly reminder, not a review, as I'm just browsing by and noticed you are using images from Unsplash. Pattern images should be CC0 licence compatible and as far as I know [Unsplash images are not](https://make.wordpress.org/themes/handbook/review/resources/#restricted-websites), unfortunately.
My tip is to use images from rawpixel.com, for example you can check https://www.rawpixel.com/search/laptop?freecc0=1

Oliver

**Comment by beafialho** [comment]
Thank you for the submission @chrislema!

We already have a few patterns in this collection that aren't exactly the same as this one, but are very similar "three column" layouts:

https://wordpress.org/patterns/pattern/about-me-cards/
https://wordpress.org/patterns/pattern/three-columns-of-text-with-buttons/
https://wordpress.org/patterns/pattern/team-social-cards/
https://wordpress.org/patterns/pattern/three-quotes-with-images/

At this time, I don't think it makes sense to add more of this type in this initial pre-release collection. I'm going to close the ticket for now, but feel free to submit your pattern directly to the directory once the it has launched. Thanks for sharing!
