### ISSUE TITLE
Pattern Submission: Food menu

### ISSUE THREAD

**Issue by webmandesign** [WordPress/pattern-directory#203]
Simple text-only food menu, or food menu section/category.

---

## Pattern Title

Food menu

## Pattern Categories

Columns, Text

## Screenshots

![Food menu](https://user-images.githubusercontent.com/2456735/122516751-702cc080-d00f-11eb-80a1-9862741d5694.jpg)

## Image Credits

n/a

## Block Markup

https://gist.github.com/webmandesign/4b146be5309702b98f1077d07e6e0a28

**Comment by melchoyce** [comment]
Thanks @webmandesign! There is a similar pattern already (#168), but the brevity of your version is nice, so the original has been updated to match your layout a little more: https://wordpress.org/patterns/pattern/restaurant-menu/

**Comment by webmandesign** [comment]
Hi @melchoyce Thanks for the info.
Wow, I'm really perplexed how I missed that one and how similar it looks! I always check the current patterns in the directory before submitting new one not to duplicate, but this one really made my evening a mysterious session 😃

**Comment by melchoyce** [comment]
Haha, there's a lot of patterns to sort through now! We're going to launch with a pretty big set 🎉
