### ISSUE TITLE
Pattern Submission: Major quote with parallax background

### ISSUE THREAD

**Issue by webmandesign** [WordPress/pattern-directory#204]
Title says it all.

---

## Pattern Title

Major quote with parallax background

## Pattern Categories

Text

## Screenshots

![Major quote with parallax background](https://user-images.githubusercontent.com/2456735/122519043-4a54eb00-d012-11eb-9749-99fab4d35330.jpg)

## Image Credits

- https://www.rawpixel.com/image/3285639/free-photo-image-architecture-cityscape-people-and-landscape
- https://www.rawpixel.com/image/2545031/free-illustration-image-statue-man-face

## Block Markup

https://gist.github.com/webmandesign/e1faca072d6e1fb123828b938385f55e

**Comment by melchoyce** [comment]
Hey @webmandesign! Thanks for this submission.

We have a similar pattern featuring a parallax background, quote, and images: https://wordpress.org/patterns/pattern/offset-gallery-with-fixed-background-and-quote/

To avoid too many similar patterns in the release collection, I'm closing this issue for now, but please feel free to re-submit your pattern once the directory launches!
