### ISSUE TITLE
Pattern Submission: Text column on parallax background

### ISSUE THREAD

**Issue by webmandesign** [WordPress/pattern-directory#205]
Title says it all.

---

## Pattern Title

Text column on parallax background

## Pattern Categories

Columns, Text

## Screenshots

![Text column on parallax background](https://user-images.githubusercontent.com/2456735/122522477-4d51da80-d016-11eb-88eb-536429c94577.jpg)

## Image Credits

- https://www.rawpixel.com/image/3282993/free-photo-image-forest-astronaut-jungle
- https://jam-icons.com/

## Block Markup

https://gist.github.com/webmandesign/548365a66df0f81d82b890db53ba1fcd

**Comment by melchoyce** [comment]
Thanks @webmandesign! I took a stab at updating this to match the [topic recommendations](https://make.wordpress.org/design/2021/06/23/update-initial-patterns-for-the-patterns-directory/):

![image](https://user-images.githubusercontent.com/2846578/123444560-067b5c00-d5a5-11eb-8860-bcbe7c64e598.png)

```
<!-- wp:cover {"url":"https://mywptesting.site/wp-content/uploads/2021/06/image-from-rawpixel-id-1207192-jpeg-scaled.jpg","id":3516,"hasParallax":true,"dimRatio":30,"overlayColor":"black","minHeight":100,"minHeightUnit":"vh","contentPosition":"center center","align":"full"} -->
<div class="wp-block-cover alignfull has-background-dim-30 has-black-background-color has-background-dim has-parallax" style="background-image:url(https://mywptesting.site/wp-content/uploads/2021/06/image-from-rawpixel-id-1207192-jpeg-scaled.jpg);min-height:100vh"><div class="wp-block-cover__inner-container"><!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column -->
<div class="wp-block-column"></div>
<!-- /wp:column -->

<!-- wp:column {"width":"45%","style":{"spacing":{"padding":{"top":"9em","right":"3em","bottom":"9em","left":"3em"}}},"backgroundColor":"white"} -->
<div class="wp-block-column has-white-background-color has-background" style="padding-top:9em;padding-right:3em;padding-bottom:9em;padding-left:3em;flex-basis:45%"><!-- wp:heading {"textColor":"black"} -->
<h2 class="has-black-color has-text-color">Hello Rover</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"textColor":"black"} -->
<p class="has-black-color has-text-color">The Lunar Roving Vehicle (LRV) was designed to transport astronauts and materials on the Moon. Original from NASA.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"elements":{"link":{"color":{"text":"var:preset|color|black"}}}},"textColor":"black"} -->
<p class="has-black-color has-text-color has-link-color"><strong><a href="#">Learn More</a></strong></p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div></div>
<!-- /wp:cover -->
```

The Lunar Roving Vehicle (LRV) was designed to transport astronauts and materials on the Moon. Original from NASA. CC0.
https://www.rawpixel.com/image/1207192/moon-landing-photograph

**Comment by kjellr** [comment]
This looks great. Thanks @webmandesign for the initial pattern, and @melchoyce for the iteration!

**Comment by webmandesign** [comment]
Hey guys! Thanks for the feedback and @melchoyce for update.

I have just one additional note here:
Originally the idea was that the white stripe goes all the way through the background image. But this is not possible to achieve with Twenty Twenty-One theme that I use for creating these patterns.

Basically I wanted to recreate a pattern I've used in my [Michelle theme](https://wordpress.org/themes/michelle/) that can be previewed at https://themedemos.webmandesign.eu/michelle/home-2/ :

![michelle-cargo](https://user-images.githubusercontent.com/2456735/123509094-dea6f980-d673-11eb-9156-bc9ec33c930e.jpg)

Surely, feel free to use whatever suits you :)

**Comment by melchoyce** [comment]
Tried to get rid of the spacing and also wasn't able to — hopefully we'll have more control over that in the future!

In the meantime, added this pattern: https://wordpress.org/patterns/pattern/text-column-over-fixed-background/

**Comment by webmandesign** [comment]
Thanks for adding this!

> hopefully we'll have more control over that in the future!

I think this is actually a theme issue. Twenty Twenty-One applies its own padding on `.wp-block-cover__inner-container` while Gutenberg applies custom padding styles on `.wp-block-cover`. So you can not override the theme padding with editor here.

**Comment by webmandesign** [comment]
Hey @melchoyce!

This pattern was still on my mind and I've actually realized that it has to be possible to stretch the text column from edge to edge in the Cover block as #216 contains such layout even with Twenty Twenty-One theme.

I found out this is only possible when Cover block's content position is set. So, I've updated your pattern code to how I originally meant it to display:

```html
<!-- wp:cover {"url":"https://wordpress.org/patterns/files/2021/06/image-from-rawpixel-id-1207192-jpeg-1-scaled.jpg","id":833,"hasParallax":true,"dimRatio":30,"overlayColor":"black","minHeight":100,"minHeightUnit":"vh","contentPosition":"bottom center","align":"full","style":{"spacing":{"padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}}} -->
<div class="wp-block-cover alignfull has-background-dim-30 has-black-background-color has-background-dim has-parallax has-custom-content-position is-position-bottom-center" style="padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;background-image:url(https://wordpress.org/patterns/files/2021/06/image-from-rawpixel-id-1207192-jpeg-1-scaled.jpg);min-height:100vh"><div class="wp-block-cover__inner-container"><!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column -->
<div class="wp-block-column"></div>
<!-- /wp:column -->

<!-- wp:column {"width":"45%"} -->
<div class="wp-block-column" style="flex-basis:45%"><!-- wp:cover {"overlayColor":"white","minHeight":100,"minHeightUnit":"vh","style":{"spacing":{"padding":{"right":"3em","left":"3em"}}}} -->
<div class="wp-block-cover has-white-background-color has-background-dim" style="padding-right:3em;padding-left:3em;min-height:100vh"><div class="wp-block-cover__inner-container"><!-- wp:heading {"textColor":"black"} -->
<h2 class="has-black-color has-text-color">Hello Rover</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"textColor":"black"} -->
<p class="has-black-color has-text-color">The Lunar Roving Vehicle (LRV) was designed to transport astronauts and materials on the Moon. Original from NASA.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"elements":{"link":{"color":{"text":"var:preset|color|black"}}}},"textColor":"black"} -->
<p class="has-black-color has-text-color has-link-color"><strong><a href="#">Learn More</a></strong></p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div></div>
<!-- /wp:cover -->
```

Here is a preview:

![Text column on parallax background](https://user-images.githubusercontent.com/2456735/124714852-95239d80-df02-11eb-9edb-9a3af5b18047.jpg)

Please feel free to review and update the pattern in directory if possible and eligible :)

**Comment by melchoyce** [comment]
Awesome, updated! https://wordpress.org/patterns/pattern/text-column-over-fixed-background/
