### ISSUE TITLE
Pattern Submission: Contact information with image

### ISSUE THREAD

**Issue by webmandesign** [WordPress/pattern-directory#206]
Title says it all.

---

## Pattern Title

Contact information with image

## Pattern Categories

Columns, Text

## Screenshots

![Contact information with image](https://user-images.githubusercontent.com/2456735/122524170-1f6d9580-d018-11eb-966a-35b9bc34bb01.jpg)

## Image Credits

https://www.rawpixel.com/image/3064476/free-illustration-image-japanese-art-waterfall-graphic-japanese-design

## Block Markup

https://gist.github.com/webmandesign/bfcfaeebc04d0a2c17290863938f6f9b

**Comment by melchoyce** [comment]
Hey! Thanks for the submission.

We have a similar pattern in this collection that displays contact information on the left and an image on the right:

https://wordpress.org/patterns/pattern/contact-and-social-links/

At this time, I don't think it makes sense to add more of this type in this initial pre-release collection. I'm going to close the ticket for now, but feel free to submit your pattern directly to the directory once it has launched. Thank you for sharing!
