### ISSUE TITLE
Pattern Submission: Large text with quote and signature

### ISSUE THREAD

**Issue by webmandesign** [WordPress/pattern-directory#208]
Title says it all.

---

## Pattern Title

Large text with quote and signature

## Pattern Categories

Columns, Text

## Screenshots

![Large text with quote and signature](https://user-images.githubusercontent.com/2456735/122529237-88a3d780-d01d-11eb-9c51-cf9037ce6d12.jpg)

## Image Credits

https://pic.webmandesign.eu/PATTERNS/CC0/custom/signature-jane-doe-black.png
License: https://github.com/webmandesign/demo-content/blob/img/PATTERNS/CC0/custom/license.txt

## Block Markup

https://gist.github.com/webmandesign/69dda1c0fed7c4d122e99557ea6a4087

**Comment by webmandesign** [comment]
Updated to:

![large-text-with-quote-and-signature](https://user-images.githubusercontent.com/2456735/123511924-b07de580-d684-11eb-9aef-54eb41398c64.jpg)

**Comment by melchoyce** [comment]
Hey @webmandesign! 

Your most recent update seemed similar to #199, so I tried this one with an image instead of a quote. I've also adjusted the font sizing slightly to work better across screen sizes:

![image](https://user-images.githubusercontent.com/2846578/124015304-8729c600-d9b2-11eb-9a6a-e609ef11fcc8.png)


```
<!-- wp:heading {"align":"wide","style":{"typography":{"lineHeight":"1.1","fontWeight":"300","fontSize":"3em"}}} -->
<h2 class="alignwide" style="font-size:3em;font-weight:300;line-height:1.1">Art Nouveau is a style of art &amp; architecture known for its elegant, organic form.</h2>
<!-- /wp:heading -->

<!-- wp:spacer {"height":20} -->
<div style="height:20px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:separator {"align":"wide"} -->
<hr class="wp-block-separator alignwide"/>
<!-- /wp:separator -->

<!-- wp:spacer {"height":20} -->
<div style="height:20px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column {"width":"78%"} -->
<div class="wp-block-column" style="flex-basis:78%"><!-- wp:cover {"url":"https://mywptesting.site/wp-content/uploads/2021/06/image-from-rawpixel-id-2701188-jpeg-scaled.jpg","id":3745,"dimRatio":0,"focalPoint":{"x":"0.50","y":"0.37"},"minHeight":60,"minHeightUnit":"vh"} -->
<div class="wp-block-cover" style="min-height:60vh"><img class="wp-block-cover__image-background wp-image-3745" alt="" src="https://mywptesting.site/wp-content/uploads/2021/06/image-from-rawpixel-id-2701188-jpeg-scaled.jpg" style="object-position:50% 37%" data-object-fit="cover" data-object-position="50% 37%"/><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"align":"center","placeholder":"Write title…","fontSize":"large"} -->
<p class="has-text-align-center has-large-font-size"></p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:cover -->

<!-- wp:spacer {"height":20} -->
<div style="height:20px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"22%"} -->
<div class="wp-block-column" style="flex-basis:22%"><!-- wp:paragraph {"dropCap":true,"fontSize":"extra-small"} -->
<p class="has-drop-cap has-extra-small-font-size">The first Art Nouveau houses and interior decoration appeared in Brussels in the 1890s. It moved quickly to Paris, where it was adapted for the entrances of the new Paris Métro.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"fontSize":"extra-small"} -->
<p class="has-extra-small-font-size">Art Nouveau reached its peak at the 1900 Paris International Exposition, which introduced the movement's work of artists such as Louis Tiffany. It appeared in graphic arts in the posters of Alphonse Mucha.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"fontSize":"extra-small"} -->
<p class="has-extra-small-font-size">From Belgium and France, it spread to the rest of Europe, taking on different names and characteristics in each country.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

Panel Entitled “Femme à marguerite” or Woman with Daisy (ca. 1898 or 1900) by Alphonse Maria Mucha. Original from The Art Institute of Chicago. CC0.
https://www.rawpixel.com/image/2701188/free-illustration-image-mucha-art-nouveau-goddess

One note: the copy here is still coming from Wikipedia, so we'll need to paraphrase/change it up before publishing the pattern.

**Comment by kjellr** [comment]
This is cool. I like that it's using a dropcap — I don't think we have any patterns that use that feature. My only comment is that the column widths seem a little random. Maybe try using 75% / 25% instead of 78% / 22%?

**Comment by webmandesign** [comment]
@melchoyce Yes, sorry for obvious heavy inspiration from your iteration of #199 But again you nailed it here :)

**Comment by melchoyce** [comment]
Updated the widths, and swapped out the copy for some written by @courtneydawn:

https://wordpress.org/patterns/pattern/heading-with-image-and-text-columns/

Thanks!
