### ISSUE TITLE
Pattern Submission: Partners logos – alternative layout

### ISSUE THREAD

**Issue by webmandesign** [WordPress/pattern-directory#209]
Title says it all.

---

## Pattern Title

Partners logos – alternative layout

## Pattern Categories

Gallery

## Screenshots

![Partners logos – alternative layout](https://user-images.githubusercontent.com/2456735/122532256-9f97f900-d020-11eb-9bbb-0a65eb850acd.jpg)

## Image Credits

- https://www.rawpixel.com/image/556745/vintage-typewriter-illustration
- https://www.rawpixel.com/image/556608/vintage-turtle-illustration
- https://www.rawpixel.com/image/572898/fish-creature-vintage-drawing
- https://www.rawpixel.com/image/573354/antique-binoculars-drawing
- https://www.rawpixel.com/image/572412/antique-lantern-vintage-drawing
- https://www.rawpixel.com/image/556578/vintage-violin-illustration

## Block Markup

https://gist.github.com/webmandesign/aa638176d8d2b72f031b4f43bf265f55

**Comment by kjellr** [comment]
Closing in favor of #207.
