### ISSUE TITLE
Pattern Submission: Parallax products

### ISSUE THREAD

**Issue by webmandesign** [WordPress/pattern-directory#210]
3 promotion sections with parallax background. Great for displaying features or products.

---

## Pattern Title

Parallax products

## Pattern Categories

Columns, Buttons

## Screenshots

![Parallax products](https://user-images.githubusercontent.com/2456735/122574287-ca4d7600-d04f-11eb-880c-360e8dfeba55.jpg)

## Image Credits

https://www.rawpixel.com/image/2049905/japanese-woodcut-print-kamisaka-sekka

## Block Markup

https://gist.github.com/webmandesign/e11b75513d600d2644d1afced09abe3e

**Comment by melchoyce** [comment]
Hey @webmandesign! I started looking at updating some of this content, and realized we have a couple other three-column patterns already in the directory:

- https://wordpress.org/patterns/pattern/call-to-action-with-columns-of-text/
- https://wordpress.org/patterns/pattern/about-me-cards/
- https://wordpress.org/patterns/pattern/team-social-cards/

Based on that, I'd recommend closing this issue for now, but please do submit this pattern once the directory opens for personal submissions.
