### ISSUE TITLE
Pattern Submission: Page intro with large image

### ISSUE THREAD

**Issue by webmandesign** [WordPress/pattern-directory#214]
Full width page title section with large presentation image.

---

## Pattern Title

Page intro with large image

## Pattern Categories

Header

## Screenshots

![Page intro with large image](https://user-images.githubusercontent.com/2456735/122582661-ae020700-d058-11eb-9bc8-3351418e7ac9.jpg)

## Image Credits

https://www.rawpixel.com/image/2776944/free-illustration-image-flower-japanese-hydrangea

## Block Markup

https://gist.github.com/webmandesign/8c68a97740b9c54f38c86fc4d783c297

**Comment by melchoyce** [comment]
What do you think about removing the text? I love how the image feels framed:

![image](https://user-images.githubusercontent.com/2846578/123652448-4d15c400-d7fa-11eb-85c5-447a899c9b2b.png)

**Comment by kjellr** [comment]
Yeah, I like that. It's simple and works well without any text. Let's add it!

**Comment by melchoyce** [comment]
Published! https://wordpress.org/patterns/pattern/image-framed-by-a-cover-block/
