### ISSUE TITLE
Pattern Submission: Page intro with background and presentation image

### ISSUE THREAD

**Issue by webmandesign** [WordPress/pattern-directory#215]
Title says it all.

---

## Pattern Title

Page intro with background and presentation image

## Pattern Categories

Header

## Screenshots

![Page intro with background and presentation image](https://user-images.githubusercontent.com/2456735/122584678-eb679400-d05a-11eb-879f-acb859a2548e.jpg)

## Image Credits

- https://www.rawpixel.com/image/3286706/free-photo-image-plant-free-nature-leaves-photo-plants
- https://www.rawpixel.com/image/1054577/post-impressionism-artwork-henri-rousseau

## Block Markup

https://gist.github.com/webmandesign/402f8ae5eeb2a357c5edf5ef016f53ee

**Comment by melchoyce** [comment]
Hey @webmandesign, since we have a couple other patterns using media & text like this, I'm going to close this one. You know the drill though, please submit it once the directory is open :)
