### ISSUE TITLE
Pattern Submission: Team

### ISSUE THREAD

**Issue by webmandesign** [WordPress/pattern-directory#217]
Gallery of 4 team members with information about the team.

---

## Pattern Title

Team

## Pattern Categories

Columns, Gallery

## Screenshots

![Team](https://user-images.githubusercontent.com/2456735/122588993-038de200-d060-11eb-8d6f-80aacaec9a83.jpg)

## Image Credits

- https://www.rawpixel.com/image/2545031/free-illustration-image-statue-man-face
- https://www.rawpixel.com/image/2751330/free-photo-image-vintage-greek-sculpture
- https://www.rawpixel.com/image/2554041/free-illustration-image-vintage-art-woman
- https://www.rawpixel.com/image/2562544/free-illustration-image-statue-sculpture-stone

## Block Markup

https://gist.github.com/webmandesign/2c6ed73a551885394012ab7840eae058

**Comment by webmandesign** [comment]
Updated copy text:
![team](https://user-images.githubusercontent.com/2456735/123510980-f5068280-d67e-11eb-9ca1-134c70480617.jpg)

**Comment by melchoyce** [comment]
I think with https://wordpress.org/patterns/pattern/team-social-cards/ and your two-column team pattern https://wordpress.org/patterns/pattern/two-columns-with-images-text-and-social-icons/ we have teams covered, so I'm going to close this one for now. Please resubmit once the directory is open!
