### ISSUE TITLE
Pattern Submission: Page intro with 2 images and description

### ISSUE THREAD

**Issue by webmandesign** [WordPress/pattern-directory#218]
Title says it all.

---

## Pattern Title

Page intro with 2 images and description

## Pattern Categories

Header

## Screenshots

![Page intro with 2 images and description](https://user-images.githubusercontent.com/2456735/122589861-12c15f80-d061-11eb-8486-9ff44eea28e4.jpg)

## Image Credits

- https://www.rawpixel.com/image/3063917/free-illustration-image-japan-vintage-japanese
- https://www.rawpixel.com/image/3065120/free-illustration-image-landscape-japan-japanese-art

## Block Markup

https://gist.github.com/webmandesign/c725223cb746b47e508dce678e9d6a16

**Comment by webmandesign** [comment]
I've updated the pattern copy text:
![page-intro-with-2-images-and-description](https://user-images.githubusercontent.com/2456735/123510515-5aa53f80-d67c-11eb-8429-207c7fadf5e1.jpg)

**Comment by melchoyce** [comment]
This is great. I made some color adjustments, swapped in two matching images, and adjusted the layout so it works a little better on mobile. What do you think?

![image](https://user-images.githubusercontent.com/2846578/124800638-e1330a00-df23-11eb-9dee-7c6853ed626a.png)
```
<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"150px","bottom":"150px","right":"50px","left":"50px"}},"color":{"background":"#f4f3ef","text":"#3d3d48"}}} -->
<div class="wp-block-group alignfull has-text-color has-background" style="background-color:#f4f3ef;color:#3d3d48;padding-top:150px;padding-right:50px;padding-bottom:150px;padding-left:50px"><!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column {"verticalAlignment":"top","width":"50%"} -->
<div class="wp-block-column is-vertically-aligned-top" style="flex-basis:50%"><!-- wp:image {"align":"wide","id":3851,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image alignwide size-large"><img src="https://mywptesting.site/wp-content/uploads/2021/07/image-from-rawpixel-id-3063927-jpeg-449x1024.jpg" alt="" class="wp-image-3851"/></figure>
<!-- /wp:image -->

<!-- wp:spacer {"height":150} -->
<div style="height:150px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"bottom","width":"50%"} -->
<div class="wp-block-column is-vertically-aligned-bottom" style="flex-basis:50%"><!-- wp:heading {"level":1,"style":{"typography":{"fontWeight":"900","fontSize":"50px","lineHeight":"1.1"}}} -->
<h1 style="font-size:50px;font-weight:900;line-height:1.1">Works of Hiroaki Takahashi</h1>
<!-- /wp:heading -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column {"width":"70%"} -->
<div class="wp-block-column" style="flex-basis:70%"><!-- wp:paragraph {"style":{"typography":{"lineHeight":"1.4"}},"fontSize":"small"} -->
<p class="has-small-font-size" style="line-height:1.4"><meta charset="utf-8"><em>A 20th-century Japanese woodblock artist in the shin-hanga art movement.</em></p>
<!-- /wp:paragraph -->

<!-- wp:image {"align":"left","id":3850,"sizeSlug":"large","linkDestination":"none"} -->
<div class="wp-block-image"><figure class="alignleft size-large"><img src="https://mywptesting.site/wp-content/uploads/2021/07/image-from-rawpixel-id-3064481-jpeg-scaled-e1625673608791-594x1024.jpg" alt="" class="wp-image-3850"/></figure></div>
<!-- /wp:image --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"30%"} -->
<div class="wp-block-column" style="flex-basis:30%"></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:spacer {"height":50} -->
<div style="height:50px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->
```

Snow at Asakusa, Yedo, Musashi Province print in high resolution by Hiroaki Takahashi (1871–1945). CC0.
https://www.rawpixel.com/image/3063927/free-illustration-image-japan-japanese-vintage

Snowy Evening on a Mountain Path print in high resolution by Hiroaki Takahashi (1871–1945). CC0.
https://www.rawpixel.com/image/3064481/free-illustration-image-japan-mountain-japanese

**Comment by kjellr** [comment]
This looks great — I like the snowy images, and it works nicely on mobile. 👍

**Comment by webmandesign** [comment]
@melchoyce Again, you've pushed it to the next level :)
Just a reminder: I've left a [comment about potential improvement](https://github.com/WordPress/pattern-directory/issues/205#issuecomment-875345217) of already closed issue with published pattern. I've basically found a way to stretch the column full-height of container Cover block.

**Comment by melchoyce** [comment]
Thanks! Published this one 🎉  https://wordpress.org/patterns/pattern/two-offset-images-with-description/
