### ISSUE TITLE
Simple columns of multiple calls to action

### ISSUE THREAD

**Issue by circlecube** [WordPress/pattern-directory#219]
This is a simple pattern to display three columns of images paired with centered simple text and a button. The columns will stack on mobile too. It is a familiar design pattern found on many sites.

---

## Pattern Title
Columns of Call to Actions

## Pattern Categories
Buttons, Columns, Text, Images

## Screenshots
Desktop:
<img width="720" alt="desktop screenshot for block pattern" src="https://user-images.githubusercontent.com/698049/122607916-51e3b680-d049-11eb-8d09-d666459afdcc.png">
Mobile (stacked): 
<img width="375" alt="mobile screenshot for block pattern" src="https://user-images.githubusercontent.com/698049/122608482-4a70dd00-d04a-11eb-9c1d-6b156bd18314.png">

## Image Credits
“Brick-moji: Smiling face with smiling eyes” by Ochre Jelly is marked with CC PDM 1.0 https://search.creativecommons.org/photos/ca491265-e697-4d1e-896f-c9f10f1bd2ed. 
“Brick-moji: Thinking face” by Ochre Jelly is marked with CC PDM 1.0 https://search.creativecommons.org/photos/31427ee0-d0ee-4bd0-929e-a06937089e7f.
“Brick-moji: Face with stuck-out tongue and winking eye” by Ochre Jelly is marked with CC PDM 1.0 https://search.creativecommons.org/photos/87cf6754-91a7-4650-8460-2043cf1d2836

## Block Markup
https://gist.github.com/circlecube/c016a3e1851d86247ff80093dc77e007

**Comment by kjellr** [comment]
Hey there! Thanks for the submission. 

We already have a few patterns in this collection that aren't exactly the same as this one, but are similar "three column" layouts: 

https://wordpress.org/patterns/pattern/about-me-cards/
https://wordpress.org/patterns/pattern/three-columns-of-text-with-buttons/
https://wordpress.org/patterns/pattern/team-social-cards/
https://wordpress.org/patterns/pattern/three-quotes-with-images/

At this time, I don't think it makes sense to add more of this type in this initial pre-release collection. I'm going to close the ticket for now, but feel free to submit your pattern directly to the directory once the it has launched. Thank you for sharing!

**Comment by circlecube** [comment]
Yea, I can see how this is similar to these other 3 col layouts. It seemed distinct enough to be unique and useful. It keeps the pattern simple with centered images, text and buttons. No background colors or text styled links or social links, this seemed to be the most generic use case and still be useful.
