### ISSUE TITLE
Podcast Subscription Box

### ISSUE THREAD

**Issue by jcasabona** [WordPress/pattern-directory#220]
With more people getting into podcasting, there should be an easy way to add a podcast subscription box to posts and pages. This block group includes a header, Spotify embed, and 5 common buttons for podcast subscription links, including RSS.

---

## Pattern Title

Podcast Subscription Box

## Pattern Categories

Buttons

## Screenshots

<img width="1333" alt="Screen Shot 2021-06-23 at 9 29 29 AM" src="https://user-images.githubusercontent.com/344910/123105184-96829f80-d405-11eb-9749-ab92f398caec.png">

## Block Markup

```
<!-- wp:group {"align":"wide","backgroundColor":"black","textColor":"white"} -->
<div class="wp-block-group alignwide has-white-color has-black-background-color has-text-color has-background"><!-- wp:spacer {"height":25} -->
<div style="height:25px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:heading {"textAlign":"center"} -->
<h2 class="has-text-align-center">Subscribe to my podcast!</h2>
<!-- /wp:heading -->

<!-- wp:embed {"url":"https://open.spotify.com/episode/1sRLIYiOafheKMZhhcEIPM","type":"rich","providerNameSlug":"spotify","responsive":true,"align":"center","className":"wp-embed-aspect-21-9 wp-has-aspect-ratio"} -->
<figure class="wp-block-embed aligncenter is-type-rich is-provider-spotify wp-block-embed-spotify wp-embed-aspect-21-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">
https://open.spotify.com/episode/1sRLIYiOafheKMZhhcEIPM
</div></figure>
<!-- /wp:embed -->

<!-- wp:buttons {"contentJustification":"center","align":"wide"} -->
<div class="wp-block-buttons alignwide is-content-justification-center"><!-- wp:button {"textColor":"white","style":{"color":{"background":"#9c52d0"}}} -->
<div class="wp-block-button"><a class="wp-block-button__link has-white-color has-text-color has-background" style="background-color:#9c52d0">Apple Podcasts</a></div>
<!-- /wp:button -->

<!-- wp:button {"textColor":"white","style":{"color":{"background":"#03a300"}}} -->
<div class="wp-block-button"><a class="wp-block-button__link has-white-color has-text-color has-background" style="background-color:#03a300">Spotify</a></div>
<!-- /wp:button -->

<!-- wp:button {"textColor":"white","style":{"color":{"background":"#d4690c"}}} -->
<div class="wp-block-button"><a class="wp-block-button__link has-white-color has-text-color has-background" style="background-color:#d4690c">Overcast</a></div>
<!-- /wp:button -->

<!-- wp:button {"textColor":"white","style":{"color":{"background":"#da352f"}}} -->
<div class="wp-block-button"><a class="wp-block-button__link has-white-color has-text-color has-background" style="background-color:#da352f">PocketCasts</a></div>
<!-- /wp:button -->

<!-- wp:button {"textColor":"white","style":{"color":{"background":"#f09001"}}} -->
<div class="wp-block-button"><a class="wp-block-button__link has-white-color has-text-color has-background" style="background-color:#f09001">RSS</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->

<!-- wp:spacer {"height":25} -->
<div style="height:25px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div>
<!-- /wp:group -->
```

**Comment by carolinan** [comment]
What are the requirements for embeds like the Spotify link above?
Can it use an existing item like above, or does it have to be a placeholder?

**Comment by jcasabona** [comment]
Hi @carolinan! For the Spotify link, you can copy any link to a Spotify episode and change it with the pencil icon. I chose Spotify because it's seemingly the more universal embed, though any embed (Audio, YouTube, etc) could go there. I'm open to suggestions on what can/should be used! 

(as an aside, I did it for this tutorial, if that helps provide context: https://www.youtube.com/watch?v=0shZtNFwyQY)

**Comment by aaroncampbell** [comment]
@jcasabona I edited the issue to add some backticks around your block markup so you can see it (I thought it was missing until I watched your YouTube video and saw that you had pasted it there). Since a lot of the markup is inside html comments, it doesn't show in the issue without the backticks around it.

**Comment by carolinan** [comment]
I was trying not to be rude. I will be less subtle.
I am not asking how the block works. I am asking if self-promotion is allowed in the block pattern directory.

**Comment by jcasabona** [comment]
Thanks @aaroncampbell! 

@carolinan I don't think asking if the block is too self-promotional is rude, especially since that was not my intention. 

If the problem is the podcast is my personal podcast, I can change it to use a different one, perhaps from Matt's or Josepha's (I recon Josepha's would be most appropriate). 

The block, as far as I can tell, will not render properly without a valid link. So we cannot use a placeholder.

**Comment by aaroncampbell** [comment]
> If the problem is the podcast is my personal podcast, I can change it to use a different one, perhaps from Matt's or Josepha's (I recon Josepha's would be most appropriate).
> 
> The block, as far as I can tell, will not render properly without a valid link. So we cannot use a placeholder.

Ultimately I think this is something that will need to be addressed clearly in the documentation for submitting patterns - along with what kinds of images are acceptable, etc - but for now I would 100% advocate that embeds be something that is project-owned. In this case that would be [WP Briefing](https://wordpress.org/news/feed/podcast).

It's not that I have any problem with promoting quality work from members of our community, or have any worries about you @jcasabona, but if _How I Built It_ one day belongs to someone else I wouldn't be as sure.

**Comment by jcasabona** [comment]
@aaroncampbell Totally understand! A clear policy is key and I definitely wouldn't want this to be an example of how people can use the Block Pattern directory to promote their own work in some way. 

I've updated the markup and the screenshot to reflect using the first episode from WP Briefing instead.

**Comment by melchoyce** [comment]
I think it should be okay to use WP Briefing, since WordPress "owns" that content. I took a stab at updating the pattern to match the podcast branding:

<img width="1292" alt="Screen Shot 2021-06-23 at 10 28 22 AM" src="https://user-images.githubusercontent.com/2846578/123115551-2fb5b400-d40e-11eb-8c44-2ec8621d82eb.png">

```
<!-- wp:group {"align":"wide","style":{"color":{"background":"#06090d"}},"textColor":"white"} -->
<div class="wp-block-group alignwide has-white-color has-text-color has-background" style="background-color:#06090d"><!-- wp:spacer {"height":25} -->
<div style="height:25px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:heading {"textAlign":"center"} -->
<h2 class="has-text-align-center">Listen &amp; Subscribe</h2>
<!-- /wp:heading -->

<!-- wp:separator {"customColor":"#ffffff","className":"is-style-dots"} -->
<hr class="wp-block-separator has-text-color has-background is-style-dots" style="background-color:#ffffff;color:#ffffff"/>
<!-- /wp:separator -->

<!-- wp:embed {"url":"https://open.spotify.com/show/6BxgmE9Qg2TZA8EKZLJ4zS","type":"rich","providerNameSlug":"spotify","responsive":true,"className":"wp-embed-aspect-21-9 wp-has-aspect-ratio"} -->
<figure class="wp-block-embed is-type-rich is-provider-spotify wp-block-embed-spotify wp-embed-aspect-21-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">
https://open.spotify.com/show/6BxgmE9Qg2TZA8EKZLJ4zS
</div></figure>
<!-- /wp:embed -->

<!-- wp:buttons {"contentJustification":"center"} -->
<div class="wp-block-buttons is-content-justification-center"><!-- wp:button {"width":50,"style":{"color":{"background":"#fec7b2","text":"#06090d"},"border":{"radius":8}}} -->
<div class="wp-block-button has-custom-width wp-block-button__width-50"><a class="wp-block-button__link has-text-color has-background" href="https://podcasts.apple.com/us/podcast/wp-briefing/id1551691710" style="border-radius:8px;background-color:#fec7b2;color:#06090d">Apple Podcasts</a></div>
<!-- /wp:button -->

<!-- wp:button {"width":50,"style":{"color":{"background":"#fec7b2","text":"#06090d"},"border":{"radius":8}}} -->
<div class="wp-block-button has-custom-width wp-block-button__width-50"><a class="wp-block-button__link has-text-color has-background" href="https://podcasts.google.com/feed/aHR0cHM6Ly93b3JkcHJlc3Mub3JnL25ld3MvZmVlZC9wb2RjYXN0" style="border-radius:8px;background-color:#fec7b2;color:#06090d">Google Podcasts</a></div>
<!-- /wp:button -->

<!-- wp:button {"width":50,"style":{"color":{"background":"#fec7b2","text":"#06090d"},"border":{"radius":8}}} -->
<div class="wp-block-button has-custom-width wp-block-button__width-50"><a class="wp-block-button__link has-text-color has-background" href="https://open.spotify.com/show/6BxgmE9Qg2TZA8EKZLJ4zS" style="border-radius:8px;background-color:#fec7b2;color:#06090d">Spotify</a></div>
<!-- /wp:button -->

<!-- wp:button {"width":50,"style":{"color":{"background":"#fec7b2","text":"#06090d"},"border":{"radius":8}}} -->
<div class="wp-block-button has-custom-width wp-block-button__width-50"><a class="wp-block-button__link has-text-color has-background" href="https://pca.st/uqvvmt8t" style="border-radius:8px;background-color:#fec7b2;color:#06090d">PocketCasts</a></div>
<!-- /wp:button -->

<!-- wp:button {"width":50,"style":{"color":{"background":"#fec7b2","text":"#06090d"},"border":{"radius":8}},"className":"is-style-fill"} -->
<div class="wp-block-button has-custom-width wp-block-button__width-50 is-style-fill"><a class="wp-block-button__link has-text-color has-background" href="https://www.stitcher.com/show/wp-briefing" style="border-radius:8px;background-color:#fec7b2;color:#06090d">Stitcher</a></div>
<!-- /wp:button -->

<!-- wp:button {"width":50,"style":{"color":{"background":"#fec7b2","text":"#06090d"},"border":{"radius":8}}} -->
<div class="wp-block-button has-custom-width wp-block-button__width-50"><a class="wp-block-button__link has-text-color has-background" href="https://wordpress.org/news/feed/podcast" style="border-radius:8px;background-color:#fec7b2;color:#06090d">RSS</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->

<!-- wp:spacer {"height":25} -->
<div style="height:25px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div>
<!-- /wp:group -->
```

One question I have, though, is that this particular pattern doesn't match the overall aesthetics of the launch collection we're currently curating. However, this is a really useful pattern. Since we're relying on embedded content, if we need to "own" that content, we can't go for a nature or art history podcast. Should we ignore the collection aesthetics in this case? Is there anything we can do to make it match the collection better?

**Comment by kjellr** [comment]
>  Should we ignore the collection aesthetics in this case? Is there anything we can do to make it match the collection better?

I think using this podcast is perhaps our only real option if we want to use a spotify podcast embed block in one of the core patterns. I do share the concern about the aesthetics not really matching the rest of the patterns though. A couple small suggestions: 

- Maybe remove the title and separator, to keep this simpler. 
- Maybe try adding some sort of art pattern in the background to help this relate more to the art/nature/history theme. 

In general though, if we can't make it clearly fit in with the other patterns in the pre-release collection, there's no pressure to include it. At this point we have a lot of patterns, so I think we can put a higher focus on consistency in the collection. Any pattern will be allowed in after launch, regardless of whether it fits with this group or not.

**Comment by melchoyce** [comment]
Maybe something like this, then?

![image](https://user-images.githubusercontent.com/2846578/123153220-6eaa3080-d433-11eb-8119-f62f6fc32af0.png)

```
<!-- wp:cover {"url":"https://mywptesting.site/wp-content/uploads/2021/06/image-from-rawpixel-id-2369452-jpeg-scaled.jpg","id":3447,"dimRatio":90,"customOverlayColor":"#072641","focalPoint":{"x":"0.48","y":"0.22"},"contentPosition":"center center","align":"wide","style":{"spacing":{"padding":{"top":"5em","bottom":"5em","right":"2em","left":"2em"}}}} -->
<div class="wp-block-cover alignwide has-background-dim-90 has-background-dim" style="padding-top:5em;padding-right:2em;padding-bottom:5em;padding-left:2em;background-color:#072641"><img class="wp-block-cover__image-background wp-image-3447" alt="" src="https://mywptesting.site/wp-content/uploads/2021/06/image-from-rawpixel-id-2369452-jpeg-scaled.jpg" style="object-position:48% 22%" data-object-fit="cover" data-object-position="48% 22%"/><div class="wp-block-cover__inner-container"><!-- wp:embed {"url":"https://open.spotify.com/show/6BxgmE9Qg2TZA8EKZLJ4zS","type":"rich","providerNameSlug":"spotify","responsive":true,"className":"wp-embed-aspect-21-9 wp-has-aspect-ratio"} -->
<figure class="wp-block-embed is-type-rich is-provider-spotify wp-block-embed-spotify wp-embed-aspect-21-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">
https://open.spotify.com/show/6BxgmE9Qg2TZA8EKZLJ4zS
</div></figure>
<!-- /wp:embed -->

<!-- wp:buttons {"contentJustification":"center"} -->
<div class="wp-block-buttons is-content-justification-center"><!-- wp:button {"width":50,"style":{"color":{"background":"#fec7b2","text":"#06090d"},"border":{"radius":8}}} -->
<div class="wp-block-button has-custom-width wp-block-button__width-50"><a class="wp-block-button__link has-text-color has-background" href="https://podcasts.apple.com/us/podcast/wp-briefing/id1551691710" style="border-radius:8px;background-color:#fec7b2;color:#06090d">Apple Podcasts</a></div>
<!-- /wp:button -->

<!-- wp:button {"width":50,"style":{"color":{"background":"#fec7b2","text":"#06090d"},"border":{"radius":8}}} -->
<div class="wp-block-button has-custom-width wp-block-button__width-50"><a class="wp-block-button__link has-text-color has-background" href="https://podcasts.google.com/feed/aHR0cHM6Ly93b3JkcHJlc3Mub3JnL25ld3MvZmVlZC9wb2RjYXN0" style="border-radius:8px;background-color:#fec7b2;color:#06090d">Google Podcasts</a></div>
<!-- /wp:button -->

<!-- wp:button {"width":50,"style":{"color":{"background":"#fec7b2","text":"#06090d"},"border":{"radius":8}}} -->
<div class="wp-block-button has-custom-width wp-block-button__width-50"><a class="wp-block-button__link has-text-color has-background" href="https://open.spotify.com/show/6BxgmE9Qg2TZA8EKZLJ4zS" style="border-radius:8px;background-color:#fec7b2;color:#06090d">Spotify</a></div>
<!-- /wp:button -->

<!-- wp:button {"width":50,"style":{"color":{"background":"#fec7b2","text":"#06090d"},"border":{"radius":8}}} -->
<div class="wp-block-button has-custom-width wp-block-button__width-50"><a class="wp-block-button__link has-text-color has-background" href="https://pca.st/uqvvmt8t" style="border-radius:8px;background-color:#fec7b2;color:#06090d">PocketCasts</a></div>
<!-- /wp:button -->

<!-- wp:button {"width":50,"style":{"color":{"background":"#fec7b2","text":"#06090d"},"border":{"radius":8}},"className":"is-style-fill"} -->
<div class="wp-block-button has-custom-width wp-block-button__width-50 is-style-fill"><a class="wp-block-button__link has-text-color has-background" href="https://www.stitcher.com/show/wp-briefing" style="border-radius:8px;background-color:#fec7b2;color:#06090d">Stitcher</a></div>
<!-- /wp:button -->

<!-- wp:button {"width":50,"style":{"color":{"background":"#fec7b2","text":"#06090d"},"border":{"radius":8}}} -->
<div class="wp-block-button has-custom-width wp-block-button__width-50"><a class="wp-block-button__link has-text-color has-background" href="https://wordpress.org/news/feed/podcast" style="border-radius:8px;background-color:#fec7b2;color:#06090d">RSS</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></div>
<!-- /wp:cover -->
```

Decorative Paper from page 49 of Four Picturesque Views in North Wales, engraved in aquatinta by Alken, from drawings made on the spot, by the Rev. B. Broughton (1801). CC0.
https://www.rawpixel.com/image/2369452/free-illustration-image-pattern-texture-abstract

**Comment by jcasabona** [comment]
Hey @melchoyce! I just want to say this looks absolutely fantastic - much better than my design skills would allow. I'd be happy if this made it into the directory as shown. 

I would like to state my reasoning for multicolor buttons: the colors for the buttons I chose (more or less) match the brand colors for each podcast service (Purple for Apple Podcasts, Green for Spotify, etc). I felt this was a much more show-agnostic approach. I don't think I noted that outside the video, which I wouldn't expect anyone here to watch to get context for the block.

With respects to the theming / launch day motif, I would say if we can't make it work, no harm no foul. Or if we want to launch this one that works, and then the original one (maybe punched up a little bit to look nicer), I'm perfectly fine with that as well. Happy to contribute in the way that works best!

**Comment by kjellr** [comment]
Thanks both of you! I think that revised version looks great. Let's add that to the collection. One small final note — let's embed the first episode of the podcast, since that's a better introduction than this episode. 

Thanks again!

**Comment by melchoyce** [comment]
> I would like to state my reasoning for multicolor buttons: the colors for the buttons I chose (more or less) match the brand colors for each podcast service (Purple for Apple Podcasts, Green for Spotify, etc).

Yeah, my concern here was contrast — making sure all those brand colors have AA contrast against white or black text is a challenge, and I also feel a little weird about referencing the brand colors while using off-brand shades.

> Let's add that to the collection. One small final note — let's embed the first episode of the podcast, since that's a better introduction than this episode.

Done, and added! https://wordpress.org/patterns/pattern/podcast-subscription-box/

Thanks for your contribution, @jcasabona.

**Comment by jcasabona** [comment]
Ah I hadn't considered that - makes sense! Thanks all. Happy to see this in the directory. I'll keep all of this in mind for my next pattern 😄
