### ISSUE TITLE
Unable to report pattern

### ISSUE THREAD

**Issue by carolinan** [WordPress/pattern-directory#221]
**Describe the bug**

I tried to report a pattern in the .org pattern directory.
When I click on the link "report pattern", the modal is showing, and I can enter text.

But nothing happens when I click on the report button. 
If the report is submitted, then there is no feedback about this action visible to the reporter.

-------------

### The report:

https://wordpress.org/patterns/pattern/call-to-action-with-columns-of-text/, "Native American art"

Block validation errors in the editor and 30 JS errors in the console:

Among others:
```
<div class="wp-block-button"><a class="wp-block-button__link has-text-color has-background" style="background-color:#ffffff;color:#d83630">Learn more →</a></div>

Content retrieved from post body:

<div class="wp-block-button"><a class="wp-block-button__link has-text-color has-background no-border-radius" style="background-color:#ffffff;color:#d83630">Learn more →</a></div>
```

```
Block validation: Block validation failed for `core/button` 

Content generated by `save` function:

<div class="wp-block-button alignnone has-custom-width wp-block-button__width-100 is-style-fill"><a>View details</a></div>

Content retrieved from post body:

<div class="wp-block-button has-custom-width wp-block-button__width-100 is-style-fill"><a class="wp-block-button__link has-text-color has-background no-border-radius" style="background-color:#d83630;color:#ffffff">View details</a></div>
```

----

The text color for the linked button in the media and text block is white, so it is white text on white background.

----
WordPress version: 5.7.2 Gutenberg is not installed.

**Comment by coreymckrill** [comment]
I was able to replicate the issue and then discovered it's because we hadn't set up any taxonomy terms yet for the possible reasons for the flag. The idea was to have reasons like "inappropriate", "trademark violation", etc. but I'm not sure what the exact wording should be for them. In the mean time, I added just the term "Other" and now submitting the report is working for me. @carolinan can you see if this fixes it for you too?

**Comment by StevenDufresne** [comment]
@coreymckrill Are we able to close this after #277? 

The live site looks correct now.

**Comment by coreymckrill** [comment]
Yep, I think this is fixed.
