### ISSUE TITLE
Image + Calendar Pattern

### ISSUE THREAD

**Issue by critterverse** [WordPress/pattern-directory#225]
I thought that this could be a fun play on a traditional hanging calendar layout and that it could be nice to have something timely that coincides with the release of the amazing new pattern directory 🔥

Hopefully users will be comfortable changing the image, colors, etc to represent different months/seasons, the image is also using the Duotone feature to make the colors easy to customize. One thing to note is that a transparent PNG cutout image is currently being used in the Image block but the design also works with regular, not cutout images :)

<details>
<summary>Edit: Image replaced with a slightly tidier version.</summary>
  
![july-cutout-v3](https://user-images.githubusercontent.com/77359364/124516560-f6872780-ddaf-11eb-8426-5b8f665076b5.png)
</details>

## Pattern Categories
Images, Navigation

## Screenshots
![calendar-screenshot-v2](https://user-images.githubusercontent.com/77359364/123333186-6a534580-d50f-11eb-9e8c-82a177d58efa.jpg)

## Image Credits
https://www.rawpixel.com/image/3014332/free-illustration-image-vintage-poster-vintage-vintage-old-poster

## Block Markup
https://gist.github.com/critterverse/2afb2ba94c75cf37069dd944c7ac93f0

**Comment by melchoyce** [comment]
This is cool! Could you try a slightly less vibrant color? I think that would help it blend in better with the existing patterns in the collection.

**Comment by critterverse** [comment]
For sure! How about something like this?

![calendar-screenshot-v3](https://user-images.githubusercontent.com/77359364/124516305-516c4f00-ddaf-11eb-807f-16a15c1419b7.jpg)

I've updated the markup in the original description above. Also please feel free to ignore this if I’ve missed the window for inclusion in the launch set :) Thanks @melchoyce!

**Comment by melchoyce** [comment]
Added, though there seems to be an issue with displaying posts: https://wordpress.org/patterns/pattern/image-and-calendar/

I'll troubleshoot 👍
