### ISSUE TITLE
Two Column 404 Pattern

### ISSUE THREAD

**Issue by critterverse** [WordPress/pattern-directory#226]
This design was created for one of the previous [FSE calls for testing](https://make.wordpress.org/test/2021/03/30/fse-program-custom-404-page-testing-summary/) and could potentially work as a 404 pattern in the directory. Here's a slightly simplified version.

Note: This pattern was originally shared in https://github.com/WordPress/gutenberg/issues/28921#issuecomment-849900911

---

## Pattern Categories
Columns, Images, 404

## Screenshots
![ship-404](https://user-images.githubusercontent.com/77359364/123263579-23416200-d4c7-11eb-826c-90fc31c0e0a7.jpg)

## Image Credits
https://search.creativecommons.org/photos/5ff95701-a72b-4c91-af80-4869eb58d50f

## Block Markup
https://gist.github.com/critterverse/9d7f49cc230e6be3ae54a6686595a001

**Comment by melchoyce** [comment]
This is fun. What would you think about tinting the image to fit better with that blue background color?

**Comment by critterverse** [comment]
Oh good call, that looks way better. Thanks for the suggestion @melchoyce!

Edit: Replaced below with a slightly cleaner, slightly brighter version.

![ship-404_v3](https://user-images.githubusercontent.com/77359364/123310843-85648c00-d4f4-11eb-8d86-fd9da1bb02f3.jpg)

<details>
  <summary>Here's the revised image asset</summary>
  
![ship-linocut-v3](https://user-images.githubusercontent.com/77359364/123310770-72ea5280-d4f4-11eb-87a3-16499e81172e.jpg)
</details>

**Comment by melchoyce** [comment]
What would you think about also removing the torn paper texture at the bottom of the background, and just having the grid? I think it would also help it tie better into our existing pattern collection.

**Comment by critterverse** [comment]
Looks good to me:

![404-updated](https://user-images.githubusercontent.com/77359364/124517473-0d2e7e00-ddb2-11eb-93b2-5daac053c072.jpg)

<details>
  <summary>Here’s the updated background image asset</summary>
  
![grid](https://user-images.githubusercontent.com/77359364/124517546-39e29580-ddb2-11eb-8e23-fa3309b495c2.jpg)
</details>

Also please feel free to ignore this if I’ve missed the window for inclusion in the launch set :) Thanks @melchoyce!

**Comment by melchoyce** [comment]
Published! https://wordpress.org/patterns/pattern/two-column-404/

**Comment by critterverse** [comment]
Awesome, thanks! 🎉
