### ISSUE TITLE
Cover with Audio Pattern

### ISSUE THREAD

**Issue by critterverse** [WordPress/pattern-directory#227]
This pattern could be a stylish way to present an Audio block. I imagine the Audio block could be easily swapped for all different kinds of media and embedded content!

---

## Pattern Categories
Images, Media

## Screenshots
![mountain-screenshot](https://user-images.githubusercontent.com/77359364/123264685-44568280-d4c8-11eb-8c7c-1c59458a7605.jpg)

## Image Credits

- https://www.rawpixel.com/image/441573/free-photo-image-satellite-plankton-nasa
- https://www.rawpixel.com/image/3311413/free-photo-image-glacier-mountain-snow-mountain

## Block Markup
https://gist.github.com/critterverse/bfa85ba5ea8626d6634e2aeab785cbc1

**Comment by melchoyce** [comment]
Love this idea, @critterverse!

I don't think this particular images matches [the existing aesthetic](https://wordpress.org/patterns/) of the directory — what would you think about something like this image and copy instead?

![Screenshot 2021-06-29 at 10-25-53 Cover with Audio – I love WordPress](https://user-images.githubusercontent.com/2846578/123815636-a3e7d000-d8c4-11eb-9b45-cdbd06ac2ec4.png)

Project Apollo Archive by NASA. Public Domain.
https://www.flickr.com/photos/136485307@N06/21512671998

"One Small Step" from NASA, Public Domain.
https://www.nasa.gov/mission_pages/apollo/apollo11_audio.html

**Comment by kjellr** [comment]
Looks great. Cool idea to use the NASA audio as well. 👍

**Comment by melchoyce** [comment]
Awesome, added this: https://wordpress.org/patterns/pattern/cover-with-title-and-audio/

Thanks @critterverse!

**Comment by critterverse** [comment]
Love it, thanks @melchoyce 🎉
