### ISSUE TITLE
Revise existing patterns to better fit the pre-release collection

### ISSUE THREAD

**Issue by kjellr** [WordPress/pattern-directory#228]
In the interest of [curating the current set of pre-release patterns into more of a collection](https://make.wordpress.org/design/2021/06/23/update-initial-patterns-for-the-patterns-directory/), I'd like to use this issue as a place to record some intended revisions for patterns the team has previously added to the directory:

- [x] **[Call to action with columns of text](https://wordpress.org/patterns/pattern/call-to-action-with-columns-of-text/)** / I feel like this one could still use some iteration. It's more complicated than most of our patterns, in that it includes four separate content areas. Maybe we trim that down to three? I'm also second-guessing the colors and use of an image now that I've been looking at it for a while. 
- [x] **[Follow Card](https://wordpress.org/patterns/pattern/follow-card/)** / I suggest we use a solid color for the icons (maybe make them icon-only too?) for a more refined look. A second look at the visual hierarchy might be good too — the image feels much larger than I remember it being when we first added it. 
- [x] **[How it Works](https://wordpress.org/patterns/pattern/how-it-works/)** / We should consider changing the color used here — it feels bright compared to other patterns in the collection. We should also think about removing the white background for greater compatibility across themes. Maybe some additional padding too?
- [x] **[Pricing Table](https://wordpress.org/patterns/pattern/pricing-table/)** / This one has some unfortunate line breaks in the headings. We should see if we can avoid that. Maybe also consider removing the second line of text ("Enrich our growing community..." etc.) to simplify these. 
- [x] **[Social Gallery](https://wordpress.org/patterns/pattern/social-gallery/)** / This one might feel more "real" if we added a user icon to the top of it. Let's give that a try and see if it makes sense. 
- [x] **[Recipe](https://wordpress.org/patterns/pattern/recipe/)** / Consider adjusting the background color behind the Ingredients list, so that it relates more clearly to the image. Maybe it's a dark red or green? Maybe there's a background color for the Instructions section too?
- [x] **[Full-width author card with social links](https://wordpress.org/patterns/pattern/full-width-author-card-with-social-links/)** / This one still [breaks poorly on middle breakpoints](https://cloudup.com/cnGB4Ht-uYw). I think it might make sense to cut this one until that issue can be fixed via Gutenberg. 
- [x] **[Illustration of bird with callout](https://wordpress.org/patterns/pattern/illustration-of-bird-with-callout/)** / Let's try simplifying this one. The background is generally not very visible, so should we consider removing it?
- [x] **[Three column staggered steps](https://wordpress.org/patterns/pattern/three-column-staggered-steps/)** / We should revise this one so the copy fits the common thread of history/art/nature more closely.

**Comment by ryelle** [comment]
@kjellr Do you think these will be updated before the release of 5.8?

**Comment by kjellr** [comment]
@ryelle definitely.

**Comment by kjellr** [comment]
**Follow Card**

Just finished updating this one. The icon colors weren't being picked up because they were using a Twenty Twenty-One block style, rather than the built-in block style properties. When I changed that, the icons were no longer left-aligned (since they include some extra padding). So I centered them to even things out. Before and after:

<img width="639" alt="Screen Shot 2021-06-28 at 9 38 24 AM" src="https://user-images.githubusercontent.com/1202812/123645966-c90d0d80-d7f4-11eb-8170-c0a594535400.png">

**Comment by beafialho** [comment]
**Call to action with columns of text**

I've updated this pattern to be simpler and shorter, also changed the image. It's live [here](https://wordpress.org/patterns/pattern/call-to-action-with-columns-of-text/).

<img width="1510" alt="Captura de ecrã 2021-06-28, às 15 12 48" src="https://user-images.githubusercontent.com/65220155/123651495-6e3eda80-d823-11eb-8c33-1a786f9f0dfe.png">

**Comment by kjellr** [comment]
**Pricing Table**

This one is updated. I shortened the name of the membership levels so they don't break in the preview, and I moved the price down to the button for simplicity. 

<img width="1116" alt="Screen Shot 2021-06-28 at 10 14 26 AM" src="https://user-images.githubusercontent.com/1202812/123651896-d7a9f380-d7f9-11eb-9ac3-615518d682be.png">

**Comment by kjellr** [comment]
**How it Works**

This one's been simplified too. The button color will now be the theme defaults: 

<img width="1440" alt="Screen Shot 2021-06-28 at 10 21 21 AM" src="https://user-images.githubusercontent.com/1202812/123652937-b8f82c80-d7fa-11eb-8976-7f7ef25d1d28.png">

**Comment by kjellr** [comment]
**Three column staggered steps**

I've updated the text in this one to fit with the Nature theme: 

<img width="1468" alt="Screen Shot 2021-06-28 at 11 25 58 AM" src="https://user-images.githubusercontent.com/1202812/123663553-818e7d80-d804-11eb-8614-ae6dd8e544df.png">

**Comment by melchoyce** [comment]
> Full-width author card with social links / This one still breaks poorly on middle breakpoints. I think it might make sense to cut this one until that issue can be fixed via Gutenberg.

I agree we should cut this for now — the responsive columns behavior here makes the pattern feel broken 😕 Hopefully we can figure out a fix in Gutenberg for better responsive column control, or a better way to control the width of the inside box without columns.

**Comment by kjellr** [comment]
Thanks — I've removed that one for now. 

> Hopefully we can figure out a fix in Gutenberg for better responsive column control, or a better way to control the width of the inside box without columns.

https://github.com/WordPress/gutenberg/pull/32502 might eventually help us control the width there. I'm keeping my fingers crossed. 🙂

**Comment by kjellr** [comment]
**Illustration of bird with callout**

I'm not sure how to best revise this one. My hesitation around it mostly lies in the large number of differently-proportioned rectangles in the layout. Here's an attempt to simplify it down: 

<img width="1167" alt="Screen Shot 2021-06-28 at 12 59 33 PM" src="https://user-images.githubusercontent.com/1202812/123675591-e6e86b80-d810-11eb-8c1f-13a96c0447cf.png">

I'm also not sure about the duplicated image. It's kind of interesting, but I'm not sure it's working in its current form. I might try iterating on it a little more unless someone has other ideas.

**Comment by kjellr** [comment]
**Recipe**

I've updated this to a simpler version, and revised the image and text a little bit: 

<img width="549" alt="Screen Shot 2021-06-28 at 3 27 59 PM" src="https://user-images.githubusercontent.com/1202812/123693013-81eb4080-d825-11eb-8e36-83bd00aa8970.png">

**Comment by beafialho** [comment]
**Social Gallery**

Added user icon and name to make the pattern feel more real and updated it in the directory.

![screencapture-blockpatterndesigns-mystagingwebsite-2021-06-28-social-gallery-2021-06-29-18_20_47](https://user-images.githubusercontent.com/65220155/123840958-ea5e1e80-d906-11eb-9b6a-c244c87a250a.png)

**Comment by melchoyce** [comment]
**Illustration of bird with callout**

Tried an alternate approach:

![image](https://user-images.githubusercontent.com/2846578/123970557-33ee4e00-d987-11eb-9138-b3ef8d27802e.png)

**Comment by kjellr** [comment]
@melchoyce that looks great — let's update that, and then we can close out this issue.

**Comment by melchoyce** [comment]
Updated! https://wordpress.org/patterns/pattern/callout-over-a-patterned-background/
