### ISSUE TITLE
Round the precision of the viewport width control

### ISSUE THREAD

**Issue by javierarce** [WordPress/pattern-directory#233]
The current control that shows the viewport width is currently showing numbers with high precision, which I don't think is very useful to the users.

<img width="1125" alt="Screenshot 2021-06-28 at 15 33 25" src="https://user-images.githubusercontent.com/4933/123645010-38e7bc00-d826-11eb-8d87-45a429fd046e.png">

I think we could just round the number with `Math.floor` or `Math.round` to get an number that is easier to read and use.

**Comment by ryelle** [comment]
😆  Yeah, that's not necessary. What OS/browser are you using? (asking because I don't see that in firefox or safari)

**Comment by javierarce** [comment]
Oh, sorry, I forgot to have a look at other browsers and assumed it was happening in all of them 🙈… I found this bug using the last version of Chrome and macOS Big Sur.

**Comment by dd32** [comment]
Can confirm in Chrome on Big Sur too.

Additionally, you can resize it down past the minimum width, and into the negatives (ie. -1500px)
The following screen capture shows it better than words :)

https://user-images.githubusercontent.com/767313/124050557-22c44080-da5e-11eb-8445-0541c182bafd.mov
