### ISSUE TITLE
Pattern preview: Cover background image is stretched

### ISSUE THREAD

**Issue by kjellr** [WordPress/pattern-directory#242]
When previewing this pattern, the images appear stretched out vertically. This is particularly noticeable on the middle image, which is supposed to be a set of concentric circles.

https://wordpress.org/patterns/pattern/triptych-with-two-images-and-a-text-area/

Pattern Preview|Expected
---|---
<img width="1016" alt="Screen Shot 2021-06-29 at 10 15 13 AM" src="https://user-images.githubusercontent.com/1202812/123813568-063fd100-d8c3-11eb-83e3-7a684e0ac391.png">|<img width="1137" alt="Screen Shot 2021-06-29 at 10 15 05 AM" src="https://user-images.githubusercontent.com/1202812/123813616-0f30a280-d8c3-11eb-9115-67bfdaf308b4.png">

**Comment by ryelle** [comment]
What browser & OS are you using? I see it cropped correctly (your expected screenshot) in firefox.

**Comment by kjellr** [comment]
Sorry — I should've included that. Looks like it's only happening in Safari (both on iOS 14.6 and MacOS 11.4 with Safari 14.1.1)

**Comment by coreymckrill** [comment]
@kjellr is this still happening for you? I just tried it on MacOS 10.15 with Safari 14.1.1 and I'm seeing the correct crop instead of the stretch. Could be that some other recent change also happened to fix this... (maybe [this](https://github.com/WordPress/pattern-directory/pull/266)?)

**Comment by ryelle** [comment]
@melchoyce confirmed this is no longer an issue - I bet #266 did fix it, we removed a bunch of unnecessary styles there.
