### ISSUE TITLE
Consider separating out Core patterns

### ISSUE THREAD

**Issue by TimothyBJacobs** [WordPress/pattern-directory#243]
When browsing the patterns directory, it isn't immediately clear what patterns I should be able to find in the Block Editor, and which ones can only be found by browsing the pattern directory.

I think it'd be helpful to be able to browse all the Core patterns on the directory since the patterns you'll find in your install both come from .org, but could also be coming from plugins, themes, etc...

**Comment by kjellr** [comment]
Yeah, we still need to figure out which patterns to highlight in the editor directly, and how best to highlight them. The current set of patterns that are bundled in the editor is not intended to be in there long-term. It would serve us well to have an ever-changing set. There's a Gutenberg issue here to discuss: https://github.com/WordPress/gutenberg/issues/33046.

I do think we can better clarify which patterns are from your theme/plugins, but I think we'll need to figure that out in the editor UI too.

**Comment by ryelle** [comment]
The core patterns are now filtered out by the "curated" dropdown (default on home & categories).
