### ISSUE TITLE
In the pattern search API, use the client locale when querying

### ISSUE THREAD

**Issue by iandunn** [WordPress/pattern-directory#244]
See #223 / #224

Pulls locale from post meta, see #229 

# Pre-launch

- [x] Use `locale` param when querying patterns (`WP_Query`)
- [x] Add e2e test -- https://meta.trac.wordpress.org/changeset/11082/

# Post-launch

- [ ] After, #28 is done, switch to ES to mitigate performance issues w/ meta queries. Do for front-end too, like #273
- [x] Prioritize search based on locale (ala Learn), rather than simple include/exclude. Do for the API, but also for the front end (related #273)

**Comment by dd32** [comment]
d75ca62a870e111d7d55666cae760fc34d2a2702 causes a bit of a shortcoming, in that patterns without a translation become inaccessible.

Instead, I think we need to prioritise translated patterns but not skip not-localised.

**Comment by iandunn** [comment]
Do you mean that requests for `es_MX` patterns won't include `en_US` "parent" patterns that don't have a `es_MX` "child/translated" variant/fork yet?

That seems good enough for launch, since all the "core/featured" patterns will be translated.

We might want to wait until after #28 too, since ES might make that prioritization easier. On the other hand, Learn already does that kind of sorting w/ `WP_Query`, so we could just copy that 🤔

**Comment by iandunn** [comment]
Removing this from the milestone since the pre-launch tasks are done.

**Comment by ryelle** [comment]
It looks like all the linked PRs have been merged, so I'm going to close this issue.
