### ISSUE TITLE
Pattern Previews: All patterns appear full width, even if they're not full-width

### ISSUE THREAD

**Issue by kjellr** [WordPress/pattern-directory#247]
**Describe the bug**

All patterns in the directory previews are currently appearing full-width, regardless of their alignment settings. This can be confusing since it's unclear to users which patterns are actually full-width. 

For example, all of these appear full-width, but they're actually (from left-to-right) wide, wide, and standard-width:

<img width="1011" alt="Screen Shot 2021-06-30 at 11 35 12 AM" src="https://user-images.githubusercontent.com/1202812/123989892-4f615500-d997-11eb-868a-a9b2c68ce635.png">
 
At some point earlier, we had the option of specifying a `viewportWidth` in the editor to help with this, but that doesn't appear possible anymore? Is this something we can adjust somehow?

_I'm not sure wether to label this as a bug, since it technically works right now. But I think this could definitely be improved._

**Comment by ryelle** [comment]
I think this was due to the previous theme & editor styles that were loaded, and after #266 this has been fixed. @kjellr let me know if you're still seeing the issue.

**Comment by kjellr** [comment]
It appears to be fixed. Thanks!
