### ISSUE TITLE
Gutenberg block patterns - Three columns text with image

### ISSUE THREAD

**Issue by mahvash-fatima** [WordPress/pattern-directory#251]
This gutenberg block pattern has three columns in which first column has heading, second column has text and the third column has text and an image. I feel it should be included in Gutenberg block because it has a simple three columns layout that can be used for multipurpose things like company goals, branding, about the company and much more.

---

## Pattern Title
Three columns text with image.

## Pattern Categories
Columns, Heading, Text, Image.

## Screenshots
![image](https://user-images.githubusercontent.com/12367607/124082566-7a68a900-da6a-11eb-93e0-aa9ae9d55676.png)

## Image Credits
https://commons.wikimedia.org/wiki/File:Aeotec_brand_logo.svg

## Block Markup
https://gist.github.com/mahvash-fatima/249c2a333a0a67f8613b581573a71827

**Comment by melchoyce** [comment]
Hi @mahvash-fatima! Thanks for your submission.

Just checking, have you had a chance to read through https://make.wordpress.org/design/2021/06/23/update-initial-patterns-for-the-patterns-directory/? It has some suggestions for pattern content.

We have a couple three-column layouts already in the directory:
- https://wordpress.org/patterns/pattern/three-columns-of-text-with-buttons/
- https://wordpress.org/patterns/pattern/three-columns-of-text/
- https://wordpress.org/patterns/pattern/three-column-staggered-steps/

This is similar, so I'm going to close it, but please feel free to submit your pattern when the directory is open!
