### ISSUE TITLE
Improve Pattern-Thumbnail Rendering/Loading

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/pattern-directory#255]
We use iframes to render previews for patterns in the pattern grid.  

Our current implementation has 2 drawbacks:

- Assets are loaded for every iframe (although they are all the same)
- We display them immediately resulting in numerous layout shifts which freezes the browser

<hr/>

## Screenshots

![Loading](https://d.pr/i/5HdgnR.gif)
![](https://d.pr/i/s4V6i9.png)

## Assets are loaded multiple times
We inject the editor styles into every `iframe` which forces the browser to redownload them for each preview:

**Code**: 
https://github.com/WordPress/pattern-directory/blob/841f5a9beb1106bd23a76a6cd0e313ccd07c2f56/public_html/wp-content/themes/pattern-directory/src/components/pattern-preview/canvas.js#L19

####  Ideas
Could we maybe grab all the styles and inject them directly? 

<hr/>

## We display them immediately resulting in numerous layout shifts which freezes the browser

This is partly worsened by the asset problem mentioned above because there is a lot of requests for assets that come in at different times and cause each `iframe` to update their view at different times.

####  Ideas

1. Only load the iframe if it's visible. (Adding `loading=lazy` will not work in this case)
2. Obfuscate the view until all the assets have loaded in the iframe.
   - I tested this by just adding an overlay and removing it after 2 seconds and it helps. We obviously wouldn't want an arbitrary timeout controlling this.

**Comment by ryelle** [comment]
> Obfuscate the view until all the assets have loaded in the iframe. 

Could we do this by listening to the iframe's `onload` event? I _think_ this would wait for all assets to load before being fired. Maybe we could use `filter: blur(…)` on the thumbnail, to have each pattern still seem unique until the iframe assets load.

> Could we maybe grab all the styles and inject them directly?

One idea I had for this issue https://github.com/WordPress/pattern-directory/issues/143 is the idea of creating our own mini-theme base for displaying patterns - a set of styles that use the bare minimum needed to render nicely, and get injected directly into the preview without the request off to the themes site. But that's a bigger task :)

Does the browser not cache the CSS file after it's been loaded once? it _shouldn't_ be doing requests for each iframe, but I'm not sure if the nature of iframes change how browsers cache files.

**Comment by StevenDufresne** [comment]
> > Obfuscate the view until all the assets have loaded in the iframe.
> 
> Could we do this by listening to the iframe's `onload` event? I _think_ this would wait for all assets to load before being fired. Maybe we could use `filter: blur(…)` on the thumbnail, to have each pattern still seem unique until the iframe assets load.

I quickly played with this but wasn't able to get it to work. But hopefully, this approach would work.


> > Could we maybe grab all the styles and inject them directly?
> 
> One idea I had for this issue #143 is the idea of creating our own mini-theme base for displaying patterns - a set of styles that use the bare minimum needed to render nicely, and get injected directly into the preview without the request off to the themes site. But that's a bigger task :)

Yeah, this would nice. 

> Does the browser not cache the CSS file after it's been loaded once? it _shouldn't_ be doing requests for each iframe, but I'm not sure if the nature of iframes change how browsers cache files.

It does use a cached version provided it has been loaded by the parent. So styles like `editor/style.css` will get served from the cache, but `twentynineteen` is only loaded in the iframes, so it will make new requests for all iframes. If our parent theme stylesheets diverge from the iframes we'll also see new requests for those as well.

**Comment by ryelle** [comment]
I ended up switching to Twenty Twenty-One for the solution in #143, but in doing so I realized we don't need most of the files that are loaded there, since it's not meant to be an "editor preview", but a frontend preview. That brings down the files loaded for each iframe to just two - `wp-block-library` and the theme styles. We can still look into injecting the theme style, but I think that's a good start.

> It does use a cached version provided it has been loaded by the parent. So styles like editor/style.css will get served from the cache, but twentynineteen is only loaded in the iframes, so it will make new requests for all iframes. 

I meant that it would be pulled from the browser cache, so it'll make the request, but grab the file locally if it's been seen before. I briefly investigated this in Safari & Chrome, starting with an empty cache, and it looks like Safari will make a single network request for the file, and then subsequent pages/categories will use the file from memory.  Chrome initially makes a request for each iframe on the page, but when you navigate to another page/category, it uses the file from disk cache. 

(Firefox keeps iframe requests separate and I can't easily see what happens here. 🤷🏻 )

Would [`preload`](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload) help with this, maybe? I'm not too familiar with the uses/any drawbacks to it.

**Comment by StevenDufresne** [comment]
> I meant that it would be pulled from the browser cache, so it'll make the request, but grab the file locally if it's been seen before. I briefly investigated this in Safari & Chrome, starting with an empty cache, and it looks like Safari will make a single network request for the file, and then subsequent pages/categories will use the file from memory. Chrome initially makes a request for each iframe on the page, but when you navigate to another page/category, it uses the file from disk cache.

Yep, that matches my experience. I am more trying to optimize the initial load and I think your changes have improved that. We can cycle back.

> Would [`preload`](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload) help with this, maybe? I'm not too familiar with the uses/any drawbacks to it.

Same, not super familiar but definitely worth a try.

**Comment by ryelle** [comment]
Closing this issue for now, if we find something actionable to improve performance (or get more reports of it being slow), we can revisit.

**Comment by jonoalderson** [comment]
Can we revisit? The current performance is pretty appalling from an SEO, usability, accessibility and general marketing/reputation perspective. I'd still like us to [_noindex_ the whole patterns directory](url) until we can address this.
