### ISSUE TITLE
Translate Category Names

### ISSUE THREAD

**Issue by dd32** [WordPress/pattern-directory#256]
**Describe the bug**
Category names should be translatable when used via a translated UI such as http://ja.wordpress.org/patterns/

**To Reproduce**
1. Go to https://ja.wordpress.org/patterns/
2. The section titles should be translated

**Expected behavior**
I expected to see a language I could not understand, instead, I saw English.

**Additional context**
https://wordpress.slack.com/archives/C02RP50LK/p1625195316084600

**Comment by coreymckrill** [comment]
We could do this the same way we did it [for Learn](https://github.com/WordPress/learn/pull/205). I'm happy to take a crack at it.
