### ISSUE TITLE
Add RTL Styling

### ISSUE THREAD

**Issue by dd32** [WordPress/pattern-directory#257]
**Describe the bug**
https://ar.wordpress.org/patterns/ has no CSS Styles.

**To Reproduce**
1. Go to https://ar.wordpress.org/patterns/ or set your locale to an RTL language.

**Expected behavior**
A beautiful website should appear.

**Comment by coreymckrill** [comment]
A symptom of using the `wporg` parent theme, I suspect. [This was the fix for Learn.](https://github.com/WordPress/learn/commit/5946a99cc6344c19aa80cb01cef9979971181fb4)
