### ISSUE TITLE
?name=* queries do not 404

### ISSUE THREAD

**Issue by dd32** [WordPress/pattern-directory#258]
**Describe the bug**
When visiting a URL such as https://wordpress.org/patterns/?name=random-post-name or https://wordpress.org/patterns/random-post-name/ the request should 404, and use a 404 template.

Requests to 404 patterns do work though: https://wordpress.org/patterns/pattern/random-pattern-doesnt-exist/

The URI for patterns is currently https://wordpress.org/patterns**/pattern/**$pattern_name/, it might be worth removing that extra subdirectory as part of this to make queries simpler.

**To Reproduce**
1. Visit the quoted URIs above

**Expected behavior**
A 404 HTTP status and 404 template.

**Comment by ryelle** [comment]
This was fixed in #280, with the removal of `bypass_404_page`. The 404 pages are working correctly again 👍🏻
