### ISSUE TITLE
Replace backtick quotes

### ISSUE THREAD

**Issue by vlad-timotei** [WordPress/pattern-directory#260]
**Describe the bug**
This line uses backtick instead of single quotes:
https://github.com/WordPress/pattern-directory/blob/841f5a9beb1106bd23a76a6cd0e313ccd07c2f56/public_html/wp-content/plugins/pattern-creator/src/plugins/viewport-header-control.js#L117

This (I can't think of another reason why) makes GlotPress to fail importing the string - instead it imports the textdomain:
https://translate.wordpress.org/projects/meta/pattern-directory/ro/default/?filters%5Boriginal_id%5D=12101839

**Expected behavior**
See `Width (%spx)` string in GP, not `wporg-patterns`

**Comment by ocean90** [comment]
GlotPress is not to blame here. It's WP-CLI parsing the line not correctly as this it the output:

```pot
#. translators: %s viewport width as css, ie: 100%
#: src/plugins/viewport-header-control.js:117
msgid "wporg-patterns"
msgstr ""
```

Should probably be reported to https://github.com/wp-cli/i18n-command.

**Comment by vlad-timotei** [comment]
Thanks for clearing that up, @ocean90 🙌🏻 
I'll report it there for a long term solution (I imagine some developers use backticks for their strings..) but for now, I think a quick short term solution is to use single quotes here.

**Comment by swissspidy** [comment]
Note that there's also an ESLint rule that helps prevent unnecessary use of template literals like in this case.

**Comment by ocean90** [comment]
@vlad-timotei Looks like you forgot to submit a PR for https://github.com/vlad-timotei/pattern-directory/commit/678bb12b8ea137d86ae71d16920fe7d15ab3cfb4?
