### ISSUE TITLE
Improve navigating between page results

### ISSUE THREAD

**Issue by annezazu** [WordPress/pattern-directory#270]
**Describe the bug**

At the bottom of the pattern directory, there's a list of page numbers that you can flip between. It seems to show the first and last two pages at all times. Due to this logic, you're only able to navigate to the third page of results if you select "Next" as the third page isn't listed for example. The "..." also isn't clickable. This seems to be isolated just to the third page selection.  Shout out to @shaunandrews who found this :) Just reporting. 

**To Reproduce**
1. Go to https://wordpress.org/patterns/
2. Scroll to the bottom of the page
3. Select the second page
4. Notice the 3 isn't visible and try to select "..." to see more options
5. Notice you can only select Next to be moved to the next page results. 

**Expected behavior**

Expect to be able to see the option to select directly the third page results without needing to click next. 

**Screenshots**

https://user-images.githubusercontent.com/26996883/124635233-6e069680-de44-11eb-9c9e-a9b76aea13ed.mov

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 89.0.4389.128

**Comment by ryelle** [comment]
Thanks for creating the issue! The missing "3" bug has been annoying me 🙂  I've fixed it over in #271.

**Comment by annezazu** [comment]
Oh incredible! Thank you :D
