### ISSUE TITLE
Merge two strings

### ISSUE THREAD

**Issue by tobifjellner** [WordPress/pattern-directory#274]
While translating strings for the pattern directory, I stumbled upon two similar strings that probably could be merged to use exactly the same string:
The description is used to help users of assistive technology understand the content of your pattern.
Ref: https://github.com/WordPress/pattern-directory/blob/trunk/public_html/wp-content/plugins/pattern-directory/src/pattern-post-type/details.js#L52

and
The description is used to help users of assistive technology better understand the contents of your pattern.
https://github.com/WordPress/pattern-directory/blob/trunk/public_html/wp-content/plugins/pattern-creator/src/components/publish-modal/submit.js#L98

**Comment by StevenDufresne** [comment]
@ryelle How do we usually handle strings like this in other @wordpress projects?

**Comment by ryelle** [comment]
The two strings in question:

> The description is used to help users of assistive technology understand the content of your pattern.
> The description is used to help users of assistive technology better understand the contents of your pattern.

The differences are added "better", and "content" vs "contents". I think we can stick with the shorter string.

> How do we usually handle strings like this in other projects?

By merging them like this - there's no reason these should be different phrases.

**Comment by StevenDufresne** [comment]
> By merging them like this - there's no reason these should be different phrases.

I should have been more specific. I meant functionally when 2 strings are shared across 2 different components. Do we add them to a `utils.js` like file and export?

**Comment by ryelle** [comment]
Oh no, just use the same string in both places - because they're both using the same textdomain and are imported into the same GlotPress project, using the same string will create just one record to translate, and will be used in both places.
