### ISSUE TITLE
Patterns: Use revisions to track pattern changes

### ISSUE THREAD

**Issue by ryelle** [WordPress/pattern-directory#279]
The revisions were disabled on the pattern post type to disable the Revisions UI in the creator (because it's broken), but we actually need revisions to track changes to patterns.

We should re-enable revisions for now, and find another solution for disabling them in the Pattern Creator.

**Comment by coreymckrill** [comment]
Do we need to be able to view/compare revisions on the front end, or just in WP Admin?

**Comment by ryelle** [comment]
I would say just in wp-admin, I think it's more useful as a moderation/history tool.

**Comment by coreymckrill** [comment]
👍 That's good, the script the generates the visual diffs between revisions is very tightly coupled to the admin.
