### ISSUE TITLE
Pattern Creator: Preview a pattern while editing it

### ISSUE THREAD

**Issue by ryelle** [WordPress/pattern-directory#29]
Pulling this task out of #14.

The mockups have a preview button:
![Screen Shot 2020-12-01 at 12 16 28 PM](https://user-images.githubusercontent.com/541093/100773623-2364fd80-33cf-11eb-96e5-f7abc4eeb621.png)

When clicked, it would show a dropdown like post previews https://github.com/WordPress/pattern-directory/issues/14#issuecomment-725496310

> I added the preview link as a possible location for both desktop/mobile preview as well as maybe theme switching. 

Post screen example, probably something like this but instead of "Preview in a new tab", it could have some themes to apply. Maybe just the Twenty*s?

![Screen Shot 2020-12-01 at 12 16 38 PM](https://user-images.githubusercontent.com/541093/100773625-24962a80-33cf-11eb-8509-6bd9e3a05161.png)

Option from mockups:
<img width="201" alt="Screen Shot 2021-02-15 at 4 55 26 PM" src="https://user-images.githubusercontent.com/541093/107996536-9df4f080-6fae-11eb-84fa-cd95734844d4.png">

**Comment by ryelle** [comment]
@shaunandrews What do you expect happens when someone clicks the "View" text here? Should it be a separate preview, or the pattern details page?

<img width="412" alt="Screen Shot 2021-03-30 at 12 45 36 PM" src="https://user-images.githubusercontent.com/541093/113025325-d400c500-9155-11eb-92f5-271c16d3e6a5.png">

**Comment by shaunandrews** [comment]
Ah, sorry for any confusion; There was a PR/issue in the Gutenberg repo that mentioned updating the "Preview" button to just "View," and my mockups reflect that change. But, the button just opens a menu that lets you adjust the editor's viewport size along with a link to open in a new tab:

<img width="221" alt="image" src="https://user-images.githubusercontent.com/191598/113759989-bac2c000-96e3-11eb-9495-33b0fd7d4517.png">

I don't think we need to do anything different for the pattern editor immediately. We could definitely offer different themes to apply, but it seems out of scope for v1 of the directory.

**Comment by StevenDufresne** [comment]
@ryelle I think this can be closed since we implemented an "in-editor" preview tool in #115.
