### ISSUE TITLE
Theme: Choosing a new page should move to top of the page.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/pattern-directory#297]
When a user interacts with the pagination control, the browser should scroll to the top of the page.

**To Reproduce**
1. Go to `/`
2. Scroll to button select [2]
3. Notice you are still located at the bottom of the page.

**Screenshots**
[ Watch GIF here](https://d.pr/i/P0EDtH)

**Comment by ryelle** [comment]
This could also address the accessibility focus issues too - a focus change should also move the browser window up. Right now, if you click a new page or category, there is no screen-reader indication that new content is loaded, and your key focus stays on the element just clicked.

I think focus should move to the first pattern/grid container when the query changes - pagination & categories too, with an announcement that new content has loaded - "Page 2 of Gallery patterns", "Page 2 of Gallery patterns", "Page 5 of All patterns", etc.

Alternately, we can move focus back up to the "skip to content" link - it would be more consistent across all pages, but would require tabbing back through the blue nav bar and category list before getting to the patterns.
