### ISSUE TITLE
Stub Core endpoint

### ISSUE THREAD

**Issue by iandunn** [WordPress/pattern-directory#3]
Get rough version working w/ api.w.org, see #2 .

**Comment by ryelle** [comment]
Not a formalized schema, but these are the assumptions I've been working with:

- An index endpoint that returns all core patterns
- (Eventually) a search endpoint returning matching patterns
- (Eventually) an endpoint returning patterns in a given category

The response should be an array of objects, each pattern should match:

- name: string slug
- title: string, human-friendly, possibly translated
- content: string with blocks & HTML, possibly translated
- viewportWidth: int
- categories: array of strings

Categories are core-defined, but plugins can add specific categories… for the start I think we can restrict to the core list ("buttons, columns, gallery, header, text"). These could also be translated, but the slugs in the API should remain the same

**Comment by iandunn** [comment]
Rough draft at https://github.com/WordPress/gutenberg/pull/26578

**Comment by iandunn** [comment]
This was just created so we'd have something in the Project, https://github.com/WordPress/gutenberg/pull/26578 is the main PR. 

Closing since we can just use a "note" in the Project to track instead.
