### ISSUE TITLE
Search: Result not found page layout & pattern display issues

### ISSUE THREAD

**Issue by naokomc** [WordPress/pattern-directory#300]
The search result page's error message layout is off and it shows patterns even when there is no match.

**To Reproduce**
1. Go to https://wordpress.org/patterns/
2. Search for something that doesn't have any results, e.g. abcdefg
3. The error message is all the way to the left edge of the page. 6 patterns are displayed even though the page also says "0 patterns found for..." (see: https://wordpress.org/patterns/search/abcdefg/)

**Expected behavior**
See the "No results found" header and the following text in the correct layout without any patterns.

**Screenshots**
![image](https://user-images.githubusercontent.com/34067/126088302-f9811b6a-64b2-4692-a169-967ce7ef6dcc.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.2
 - Browser: Chrome 91.0.4472.114

**Comment by StevenDufresne** [comment]
I think this should be fixed by #302.

**Comment by StevenDufresne** [comment]
I think this should be resolved now, we'll re-open if we see the issue again. Thanks!
