### ISSUE TITLE
Search: Non-ASCII characters garbled

### ISSUE THREAD

**Issue by naokomc** [WordPress/pattern-directory#301]
Maybe this is still being worked on, but when non-ASCII characters are used for search, they are displayed with character entity references. This is not the highest priority either – but would be nice if it's fixed at some point.

**To Reproduce**
Search for `画像` on any site (English or Rosetta site in any language). It means "image" or "images" in Japanese.

Depending on which site you are on, you get a different number of matches:

- https://wordpress.org/patterns/search/%E7%94%BB%E5%83%8F/ (76 matches)
- https://ja.wordpress.org/patterns/search/%E7%94%BB%E5%83%8F/ (74 matches)
- https://ar.wordpress.org/patterns/search/%E7%94%BB%E5%83%8F/ (18 matches)

Also, some of the matched patterns in Japanese may not be correct. This "[Three Buttons](https://ja.wordpress.org/patterns/pattern/three-buttons-ja/)" pattern is matched ([English version here](https://wordpress.org/patterns/pattern/three-buttons/)) but I don't think it includes the keyword (it has no image reference).

**Expected behavior**
See "画像" instead of "%E7%94%BB%E5%83%8F" as the searched keyword.
See "not found" result on sites other than ja.wordpress.org.

**Screenshots**
![image](https://user-images.githubusercontent.com/34067/126089163-0fb6219b-4f0e-4a21-86fa-39d10be0c6d8.png)

**Desktop (please complete the following information):**

**Comment by StevenDufresne** [comment]
I've added a PR for the output problem, in #303.
We'll need to address the result set which does appear incorrect for non-ASCII searches.

**Comment by ryelle** [comment]
> We'll need to address the result set which does appear incorrect for non-ASCII searches.

Once the PR in #303 is applied, the search result set appears correct. Searching for "画像" only returns 18 results, and it does not include the 3 buttons pattern. There are no results for that search on the `wordpress.org/patterns` or `ar.wordpress.org/patterns` sites.
