### ISSUE TITLE
Localize page title

### ISSUE THREAD

**Issue by ocean90** [WordPress/pattern-directory#318]
**Describe the bug**
First reported in https://meta.trac.wordpress.org/ticket/5831

> Localized versions of the Pattern Directory (for instance Swedish, https://sv.wordpress.org/patterns/ ) has their Title attribute set to a string in English: `<title>Block Pattern Directory &#124; Beautifully designed patterns ready to go with a simple copy/paste &mdash; WordPress.org</title>`
>
> Instead of being grabbed from the site's attributes, this should be included as a string that can be translated.

**Additional context**
* https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/themes/pub/wporg-plugins/functions.php?rev=10860#L235
* https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/themes/pub/wporg-themes/functions.php?rev=11134#L228
* https://github.com/WordPress/pattern-directory/issues/310

**Comment by ryelle** [comment]
Thanks for moving the report over here. This should be fixed now 🙂
