### ISSUE TITLE
Header graphic is composed of patterns that aren't in the directory

### ISSUE THREAD

**Issue by kjellr** [WordPress/pattern-directory#320]
The pattern directory header graphic depicts three pattern mockups that aren't actually patterns in the pattern directory: 

<img width="1028" alt="Screen Shot 2021-07-21 at 3 46 41 PM" src="https://user-images.githubusercontent.com/1202812/126550931-21c39e51-7376-4583-9614-3dbbc091acad.png">

Not sure where those came from, but I suggest we replace them with some from the initial set of live patterns instead. 

cc @shaunandrews

**Comment by javierarce** [comment]
I'd also like to offer [this interactive prototype ](https://javierarce.github.io/patterns/) I made (also based on one of the @shaunandrews's ideas) as a way to spice the header up a little bit.

https://user-images.githubusercontent.com/4933/126627399-680fbf01-08fe-4828-a22e-3ec5fa940954.mp4

The header would showcase a curated selection of some of the best patterns, and we could organize thematically or just include a random selection of high-quality patterns.

In the prototype, it's possible to click on a card and have a closer look at the pattern, but this probably is not the best idea, and the main action could be just opening the pattern page.

In terms of accessibility, besides adjusting the speed to make it smoother, we could use [Reduced Motion Media Query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) to detect if the user doesn't want to trigger animations and deactivate it and offer a play button instead.

**Comment by shaunandrews** [comment]
I grabbed a few of the most favorited patterns in the directory and wound up with this:

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/191598/126698408-a2b78f5b-64b6-4190-aadd-4dfcec8a3e10.png">

Here's the hi-res images we can use if we like it:
[header-pattern-screenshots.zip](https://github.com/WordPress/pattern-directory/files/6864786/header-pattern-screenshots.zip)

**Comment by ryelle** [comment]
For a quick fix we can replace the image with the one @shaunandrews posted. @shaunandrews, could you make an image [like this one](https://wordpress.org/patterns/wp-content/themes/pub/wporg-patterns/images/masthead-bg.png) with the three images? That'll be easiest to swap. It only needs to be 1100ish x 700ish.

If we do need the animated header, we can make another issue for it, and work on it maybe after pattern creation is in a better place.

**Comment by shaunandrews** [comment]
![pattern-bg](https://user-images.githubusercontent.com/191598/126817562-7d1d1226-d8a6-44c1-86a6-51d1a50762e3.jpg)

**Comment by shaunandrews** [comment]
![masthead-bg](https://user-images.githubusercontent.com/191598/126817683-f9107075-c657-4d88-8e64-a139980a3ab7.png)
