### ISSUE TITLE
Typo in original pattern string

### ISSUE THREAD

**Issue by nextdoorpanda** [WordPress/pattern-directory#324]
**Describe the bug**
There is a typo in the string `This pasta is one of our most famous dishes, served with king cran and chilli pepper.`
It should read `king crab` instead of `king cran`.

**Additional context**
Pattern URL: https://wordpress.org/patterns/pattern/restaurant-menu/

**Comment by kjellr** [comment]
Thanks! I've updated the english version of the pattern. @ryelle do you know if we need to do anything else before closing this out?

**Comment by ryelle** [comment]
That should be it - it'll sync into the translation project sometime today.
