### ISSUE TITLE
Template string correction (redundancy)

### ISSUE THREAD

**Issue by nextdoorpanda** [WordPress/pattern-directory#325]
**Describe the bug**
The phrase `of trees` in string `The sun setting through a dense forest of trees.` is redundant.

**Additional context**
Pattern URL: https://wordpress.org/patterns/pattern/three-columns-with-images-and-text/

**Comment by StevenDufresne** [comment]
I don't see this text in the pattern provided in the link. Reopen if necessary.

**Comment by ryelle** [comment]
It's in the alt text of the first photo.

**Comment by ryelle** [comment]
I just removed "of trees" & synced the translations so the new string is available to be updated.

**Comment by nextdoorpanda** [comment]
> I just removed "of trees" & synced the translations so the new string is available to be updated.

Thank you :)
