### ISSUE TITLE
Header: Update favorites link when not logged in

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/pattern-directory#327]
<img width="522" alt="image" src="https://user-images.githubusercontent.com/191598/126682923-36339cd3-c605-43b2-8ed3-6b0392858eba.png">

The pattern directory homepage shows a link to "My favorites", but it only works if you're logged in. Perhaps it would make sense to hide this link for visitors who aren't logged in to an account.

**Comment by ryelle** [comment]
That was left there intentionally, since the My Favorites page has login instructions, see https://github.com/WordPress/pattern-directory/pull/288

**Comment by shaunandrews** [comment]
I don't think its relevant if you're not signed in, and its a little awkward by itself. The design intended to show the "Build your own patterns" CTA if you're logged out:

<img width="450" alt="image" src="https://user-images.githubusercontent.com/191598/126696870-f8dbcc82-fef7-4d18-b0dd-d2cef5e4d969.png">

Since we don't have the editor ready, perhaps we can replace the "My favorites" link with a CTA to sign in? Clicking the link could take you directly to the log in screen, rather than an interstitial detour to an empty page.

<img width="450" alt="image" src="https://user-images.githubusercontent.com/191598/126697032-899edd11-878c-4c76-811c-f092f45d667b.png">

**Comment by StevenDufresne** [comment]
Assuming we get the editor ready, how do you get to your favorites if we only have "Build your own patterns" when not logged in?
