### ISSUE TITLE
Duplicate "My Favorite" items in the top bar

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/pattern-directory#331]
When viewing the "My Favorites" screen the top, blue bar has some duplicated text:

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/191598/126696389-e55572e6-5161-4048-8ac8-d935f32cc59c.png">

I don't think we should include the bolded breadcrumb indicator. Instead we should bold the button near the search input:

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/191598/126696521-99cfcd61-c38f-488f-84ed-b9bc57ec3788.png">

**Comment by ryelle** [comment]
Does anything change for you when we eventually add in the My Patterns/Create Pattern link to the left? And would this apply to the My Patterns page too? Like…

<img width="977" alt="Screen Shot 2021-07-23 at 12 44 07 PM" src="https://user-images.githubusercontent.com/541093/126814604-c5e7e3ae-f4df-4416-8289-80b9434495e2.png">

<img width="993" alt="Screen Shot 2021-07-23 at 12 41 33 PM" src="https://user-images.githubusercontent.com/541093/126814313-9d983a07-194e-4e2c-b455-ed1bd54dcbfa.png">

What about for the Category & Author archives, those would keep the breadcrumbs?

<img width="984" alt="Screen Shot 2021-07-23 at 12 44 50 PM" src="https://user-images.githubusercontent.com/541093/126814695-1c8952f2-602a-4469-8744-7000b213700d.png">

<img width="987" alt="Screen Shot 2021-07-23 at 12 46 14 PM" src="https://user-images.githubusercontent.com/541093/126814851-739f334b-cc35-4577-9bcf-58ea87437843.png">

**Comment by jasmussen** [comment]
Hopping in from outside, Kelly you're suggesting that if you go to my favorites, you could also filter by Headers a level deeper than that? I.e. All Patterns / My Favorites / Category: Header?

I've not yet been able to compile the directory (working on that), so the following should not be considered a very strong or too informed opinion. But initially I'd simply echo Shaun's suggestion, that we don't show the breadcrumb bar for favorites. If the filtering pills (All, Buttons, Columns, Gallery) remain on your favorites page, they can serve as breadcrumbs for the favorites section.

For the more granular filtering of your favorites by author or category, the gray notice at the top can help indicate your location, but I'd suspect the need for breadcrumbs on your favorites page to be a rare necessity for only those who favorite a great amount of patterns. And if that indeed happens, it seems like we could revisit.

**Comment by ryelle** [comment]
> I've not yet been able to compile the directory

You can click around on the live site, that should give you an idea of how it works: https://wordpress.org/patterns/

> you're suggesting that if you go to my favorites, you could also filter by Headers a level deeper than that?

You can, but that's not what I'm talking about here. The original issue is that "Favorites" appears twice in the header on the Favorites page:

<img width="1195" alt="Screen Shot 2022-02-23 at 11 44 28 AM" src="https://user-images.githubusercontent.com/541093/155365906-78416e23-de4f-43c0-a42f-0900daac59aa.png">

I was trying to ask about consistency, especially once the menu is updated — when pattern creation launches, we'll definitely add "My Patterns" to that menu, maybe "Create a Pattern"/"New Pattern" too.

For example, would we still want to remove "Favorites" on the left here?

<img width="1195" alt="Screen Shot 2022-02-23 at 11 46 19 AM" src="https://user-images.githubusercontent.com/541093/155366924-67fd3cc5-802f-42ce-bd8a-4c705dbf5e2f.png">

What about My Patterns on the left here?

<img width="1195" alt="Screen Shot 2022-02-23 at 11 49 26 AM" src="https://user-images.githubusercontent.com/541093/155366922-5498e464-80d7-48d2-8683-c446c6f04ac3.png">

My comment about the Author and Category breadcrumbs was mostly meant to confirm whether we still wanted _those_, if we're getting rid of other breadcrumbs.

**Comment by jasmussen** [comment]
Thanks for the clarification, catching up!

To be clear, I don't see this issue as the biggest issue in the world. Not that it doesn't need fixing, but that it probably doesn't need a very elaborate fix. From just browsing around, it doesn't seem like you'd have additional breadcrumbs under "Favorites", i.e. `All Patterns / Favorites / Buttons`. In that light, can we just not show "Favorites" as a breadcrumb?

That is: when browsing all patterns, show breadcrumbs as usual:
<img width="1392" alt="Screenshot 2022-02-24 at 10 01 36" src="https://user-images.githubusercontent.com/1204802/155492869-11a3b38a-b0e6-44b9-8a29-d27fc87f1d84.png">

When browsing favorites, omit that part from the breadcrumbs, and make the item on the right bold/active. Inspector mockup:

<img width="1392" alt="Screenshot 2022-02-24 at 10 05 11" src="https://user-images.githubusercontent.com/1204802/155493014-b5a3595b-c1d8-4b89-b880-2e2217db41fc.png">

**Comment by ryelle** [comment]
Closing this issue to clean up the repo - there will be a new design for this navigation bar, so it's not worth making any big changes here now.
