### ISSUE TITLE
Rename "My favorites" to "Favorites"

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/pattern-directory#332]
The "My" part of "My favorites" feels unnecessary. We should rename the page to simply "Favorites," and it's URL to `/favorites/`.

<img width="451" alt="image" src="https://user-images.githubusercontent.com/191598/126699920-12cb180e-eeb7-46a7-b904-122020aa9ccb.png">

<img width="412" alt="image" src="https://user-images.githubusercontent.com/191598/126699951-722fa85a-9603-4575-9c04-1fc0c62c2d8e.png">

<img width="257" alt="image" src="https://user-images.githubusercontent.com/191598/126699977-cd84bdf4-8c66-462f-a889-97c5f57d94da.png">

**Comment by ryelle** [comment]
This was renamed to "My favorites"/`my-favorites` to match the "My Patterns" page. See https://github.com/WordPress/pattern-directory/pull/284#discussion_r670052529

**Comment by ryelle** [comment]
Also noting that if we change this, now that the page has been "launched", we'll need to make sure there's a redirect.

**Comment by shaunandrews** [comment]
The "My" in "My Patterns" is necessary to denote the difference between all patterns and patterns you've created. We don't have the same need for Favorites.

**Comment by StevenDufresne** [comment]
> The "My" in "My Patterns" is necessary to denote the difference between all patterns and patterns you've created. We don't have the same need for Favorites.

As the one who originally made the comment, I'll do it again for completeness. :)

The favorites are specific to the user. I think the URLs should be predictable. If my patterns are `my-patterns`, I would expect the same for my favorites.

**Comment by kjellr** [comment]
The theme directory uses "Favorites", but the plugin directory uses "My Favorites". If we're going to try to start making these consistent, I'd prefer we settled on the shorter, more concise one. I'm not sure that this needs the word "My" anyway.

**Comment by StevenDufresne** [comment]
I think `favorites` seems like a consensus. I won't stand in the way :).

**Comment by ryelle** [comment]
Should we also drop "My" in the link in the header?

<img width="526" alt="Screen Shot 2021-07-26 at 6 05 00 PM" src="https://user-images.githubusercontent.com/541093/127065283-60c921a8-fc89-4849-a8fc-9f583305a292.png">

**Comment by StevenDufresne** [comment]
Should we also consider changing the label from `Favorites` to `Favorited` in the sorting dropdown? It could be misinterpreted as on my favorites.

![](https://d.pr/i/YRHt3o.png)

**Comment by shaunandrews** [comment]
Yes to the link in the header, but I think the sort by drop down is fine as "Favorites."
