### ISSUE TITLE
Link in Bio Pattern Template

### ISSUE THREAD

**Issue by scottwyden** [WordPress/pattern-directory#339]
This pattern is intended to be a starter Link in Bio page for sites who do not want to pay for a third-party Link in Bio service.

---

## Pattern Title
Link in Bio Page

## Pattern Categories
Page

## Screenshots
![Screen Shot 2021-07-26 at 2 57 00 PM](https://user-images.githubusercontent.com/402384/127043492-7fdc7bf0-69ce-4834-9a8f-a0270b58d473.jpg)

## Image Credits
CC0

## Block Markup
https://gist.githubusercontent.com/scottwyden/b050192198ca3aa02320fc9290ba23c8/raw/4143475876ccfefc6ab813131937eec2e98ac230/gistfile1.txt

**Comment by kjellr** [comment]
Hey @scottwyden, thanks for the submission. My apologies for not communicating this last week, but now that the directory has launched, [we're all set with new submissions for the time being](https://make.wordpress.org/design/2021/07/29/initial-patterns-for-the-patterns-directory-launched/). 

The next phase of the pattern directory work is going to allow anyone to submit patterns directly, without having to jump through these GitHub hoops. So I recommend holding onto your pattern idea for that! In the meantime, we did include a few other Link in Bio-style patterns in the initial pre-launch set: 

https://wordpress.org/patterns/pattern/button-links-with-gradient-background/
https://wordpress.org/patterns/pattern/button-links-with-image-background/
https://wordpress.org/patterns/pattern/podcast-subscription-box/

I'll close this ticket for now, but thank you for the submission! I look forward to seeing this in the directory once the next phase of work is complete.
