### ISSUE TITLE
Pattern translations & i18n

### ISSUE THREAD

**Issue by ryelle** [WordPress/pattern-directory#34]
Breaking out from #9: "Translations and i18n will need to be solved."

**Comment by ryelle** [comment]
I have in my notes:

- Fork pattern into `[locale].wordpress.org/patterns`?
  - What about when the parent pattern updates?
- GlotPress probably makes more sense, but how should we mark what text needs translation?

**Comment by ryelle** [comment]
A method for remixing patterns to translate content has been described in #224.

**Comment by iandunn** [comment]
What's the difference between this and #224?

**Comment by ryelle** [comment]
I guess it's not specifically, but I saw this as more of a tracking issue for i18n -- #224 has the "how to do it", but we haven't really discussed how to make localized patterns available to people browsing the directory.
