### ISSUE TITLE
Remove pattern submission issue template

### ISSUE THREAD

**Issue by kjellr** [WordPress/pattern-directory#343]
Now that the initial set of patterns have been added to the directory, [we're done with this phase or pre-release patterns](https://make.wordpress.org/design/2021/07/29/initial-patterns-for-the-patterns-directory-launched/). 

As a follow up to that, let's remove the [pattern submission template](https://github.com/WordPress/pattern-directory/blob/trunk/.github/ISSUE_TEMPLATE/pattern-submission.md). I think it's ok to keep the `[Status] Needs Design Feedback` and `[Type] Pattern Submission` tags in place, since the design team may periodically revise or add patterns in the future. 

Thanks!

**Comment by ryelle** [comment]
Removed in https://github.com/WordPress/pattern-directory/commit/1d28c48b87a3793e25cad56e77da9381bf06a66b
