### ISSUE TITLE
Creator: `TypeError` when inserting Classic block

### ISSUE THREAD

**Issue by iandunn** [WordPress/pattern-directory#35]
I get `TypeError: can't access property "tinymce", window.wpEditorL10n is undefined` when trying to insert the Classic block

**Comment by ryelle** [comment]
What do you think about disallowing the Classic block? If the goal of a pattern directory is to show cool things you can do with blocks, allowing the Classic block seems counterproductive.

**Comment by iandunn** [comment]
That works for me 👍🏻

**Comment by ryelle** [comment]
The classic block was removed in 14ce49c019af1344288a96aee70e063767468d9e
