### ISSUE TITLE
Our Service Block

### ISSUE THREAD

**Issue by khushhali-saeculum** [WordPress/pattern-directory#351]
It can clearly divide specific groups from other texts. It has a fixed image background so, It helps you to present information in an attractive way. 
---

## Pattern Title

Our Services

## Pattern Categories

Columns, Text,

## Screenshots
![our-service](https://user-images.githubusercontent.com/77092268/130054372-2cbbea9e-0595-450b-9264-ce710aa64cd7.png)

## Image Credits

https://imgbb.com/

## Block Markup

<div class="wp-block-cover alignfull has-background-dim has-parallax is-style-default" style="padding-top:60px;padding-right:60px;padding-bottom:60px;padding-left:60px;background-image:url(https://i.ibb.co/7kWf43D/pexels-linkedin-sales-navigator-2182971.jpg)"><div class="wp-block-cover__inner-container">
<h2 class="has-text-align-center">Our Services</h2>

<div style="height:40px" aria-hidden="true" class="wp-block-spacer"></div>

<div class="wp-block-columns is-style-default">
<div class="wp-block-column" style="padding-top:20px;padding-right:20px;padding-bottom:20px;padding-left:20px">
<p class="has-text-align-center" style="font-size:16px"><strong>LOREM IPSUM</strong></p>

<div style="height:20px" aria-hidden="true" class="wp-block-spacer"></div>

<p class="has-text-align-center has-small-font-size"><strong>Lorem Ipsum</strong>&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type</p>
</div>

<div class="wp-block-column" style="padding-top:20px;padding-right:20px;padding-bottom:20px;padding-left:20px">
<p class="has-text-align-center" style="font-size:16px"><strong>LOREM IPSUM</strong></p>

<div style="height:20px" aria-hidden="true" class="wp-block-spacer"></div>

<p class="has-text-align-center has-small-font-size"><strong>Lorem Ipsum</strong>&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type</p>
</div>

<div class="wp-block-column" style="padding-top:20px;padding-right:20px;padding-bottom:20px;padding-left:20px">
<p class="has-text-align-center" style="font-size:16px"><strong>LOREM IPSUM</strong></p>

<div style="height:20px" aria-hidden="true" class="wp-block-spacer"></div>

<p class="has-text-align-center has-small-font-size"><strong>Lorem Ipsum</strong>&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type</p>
</div>
</div>
</div></div>

**Comment by kjellr** [comment]
👋 Thanks for sharing your pattern — we've actually closed submissions for the time being though. [You can find more details here](https://make.wordpress.org/design/2021/07/29/initial-patterns-for-the-patterns-directory-launched/#comments). The next phase of work on the pattern directory will allow you to submit patterns directly to the repository yourself, so please hold onto your pattern for then!
