### ISSUE TITLE
ElasticSearch: website results should include non-core patterns

### ISSUE THREAD

**Issue by iandunn** [WordPress/pattern-directory#352]
Latin locales seem to work:

* https://es.wordpress.org/patterns/search/ejemplo/
* https://fr.wordpress.org/patterns/search/avec/

but non-Latin ones don't appear to:

* https://ja.wordpress.org/patterns/search/%E3%82%AE%E3%83%A3%E3%83%A9%E3%83%AA%E3%83%BC%E3%81%AE%E7%B4%B9%E4%BB%8B/
* https://ru.wordpress.org/patterns/search/%D0%BD%D0%B0%D0%B2%D0%B8%D0%B3%D0%B0%D1%86%D0%B8%D0%B5%D0%B9/

The next step is probably to test the corresponding raw ES queries in Sense to see if they work there. If they don't, that likely means it's a problem w/ the index, so ping `robfelty` or `gibrown`. If they do then it's probably something in Jetpack, or our custom code.

**Comment by iandunn** [comment]
Ah, nevermind, it doesn't have anything to do with locales. `смещенными` works for Russian.

I think what's happening is that the ES query filters to only `core` patterns, but we don't want that for the website, just for Core API requests. So we just need to distinguish the two, and add that filter conditionally.

Or, do we even want that filter anymore, since Core isn't even requesting these yet, and the "core" concept is being deprecated? @ryelle , @kjellr

**Comment by ryelle** [comment]
I'm not sure if I follow here - core _does_ request patterns from the API, and that result set should be restricted to the patterns with the "core" keyword. But the API request sets that keyword, so I don't understand why the ES query itself is filtering the results.

So as long as the API request can still respect that keyword, it sounds like removing the filter from the ES query is okay.

**Comment by iandunn** [comment]
I meant that Core doesn't make `api.w.org/patterns/?search=foo` requests right now; it only makes _browse_ requests, and then searches the local cache of that. The code for searches is there on the PHP side, but never called from the JS side AFAICT.

That's a great point that Core will just add the `core` keyword to the request when it eventually does start searching the directory, though, so it can always be conditional when building the ES query 👍🏻

**Comment by iandunn** [comment]
the examples in the OP work now, and so does ["large"]( https://wordpress.org/patterns/search/large) for `en_US`.

I discovered another issue while testing, though: #354
