### ISSUE TITLE
Front-end taxonomy views show all patterns

### ISSUE THREAD

**Issue by iandunn** [WordPress/pattern-directory#353]
https://wordpress.org/patterns/pattern-keywords/core/ appears to shows all patterns, instead of just core ones

**Comment by ryelle** [comment]
Yes, that route was not created for the app. I suppose creating it could also fix the issue at #243. Are you having trouble with all taxonomies? Can you see different patterns at https://wordpress.org/patterns/categories/columns/, https://wordpress.org/patterns/categories/buttons/, etc?

**Comment by iandunn** [comment]
I haven't checked, @tellyworth noticed it while testing, so i wanted to document it

if we don't link to that URL, then it's probably not a priority, since only power users would try it.
