### ISSUE TITLE
Search: patterns without explicit `locale` value are ignored

### ISSUE THREAD

**Issue by iandunn** [WordPress/pattern-directory#354]
Patterns that don't have an explicit `en_US` locale in the database are ignored, because the ElasticSearch query for locales doesn't match non-existent/null values. The `default` fallback we have for the REST API doesn't help, since Jetpack syncs the DB, and ES indexes that.

Examples:
* https://wordpress.org/patterns/search/calendar/ - should match post `2082`
* https://wordpress.org/patterns/search/round - should match post `2078`
* https://wordpress.org/patterns/search/framed - should match post `1856`

At one point @dd32 and i both backfilled existing posts with explicit `en_US` values, thinking that new posts would be created with an explicit locale entry, but it doesn't appear like they are.

The two solutions I see are:
* update the ES query with something like `{requested locale} OR en_US OR not exists )`. 
* Update the Creator so that new patterns have explicit metadata set, and then backfill the existing posts again.

At first glance, it seems like the ES solution would be a bit clunky because, AFAICT, the DSL requires a nested `bool` query for the latter two conditions. Since we don't deal w/ ES much, keeping the queries simple seems like the better approach to me.

In general, it also seems bad to rely on a default value that's generated on the fly, since that has to be implemented in every context where the data is used.

**Comment by ryelle** [comment]
As of https://github.com/WordPress/pattern-directory/commit/95d569d50095e6069c90a8ce5c112892fde29428, new patterns are created with a locale set, so this shouldn't be an issue anymore. There haven't been any new patterns created since the original backfill, so everything should be working as expected now 👍🏻
