### ISSUE TITLE
Three Column Testimonials on a Background 

### ISSUE THREAD

**Issue by rraventos** [WordPress/pattern-directory#355]
The use of testimonials helps establish credibility. This pattern includes in a background two header sections and three columns to add the photo and the review of each of the three testimonials.
---

## Pattern Title

Three Column Testimonials on a Background 

## Pattern Categories

Columns

## Screenshots

<img width="1310" alt="testimonials-pattern" src="https://user-images.githubusercontent.com/73739571/130593741-609a18ea-be8d-4a6d-b0aa-e45493fd8ac5.png">

## Image Credits

Image by <a href="https://pixabay.com/users/clker-free-vector-images-3736/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=296990">Clker-Free-Vector-Images</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=296990">Pixabay</a>.

## Block Markup

<div class="wp-block-group alignfull has-medium-padding has-white-color has-text-color has-background" style="background-color:#f9f9f9">
<div style="height:1px" aria-hidden="true" class="wp-block-spacer"></div>

<h3 class="has-text-align-center has-black-color has-text-color">What Our Customers Say About Us</h3>

<p class="has-text-align-center has-black-color has-text-color">Our customers love us because...</p>

<div class="wp-block-columns alignwide has-3-columns has-horizontal-padding">
<div class="wp-block-column">
<div class="wp-block-group has-medium-padding has-black-color has-text-color">
<div class="wp-block-image is-style-rounded"><figure class="aligncenter size-full is-resized"><img src="https://neliosoftware.com/es/wp-content/uploads/sites/3/2021/08/female-296990_1280.png" alt="Imagen de un perfil de mujer" class="wp-image-35745" width="100" height="100"/></figure></div>

<p class="has-text-align-center has-black-color has-text-color has-small-font-size">⭐️⭐️⭐️⭐️⭐️<br><strong>WOW This really works</strong><br>By far this plugin is the best tool that we have used. All of our clients are delighted working with this plugin. Easy to use and nice UI.</p>

<p class="has-text-align-center has-black-color has-text-color has-small-font-size"><strong>Name Surname</strong> – Position<br></p>
</div>
</div>

<div class="wp-block-column">
<div class="wp-block-group has-medium-padding has-black-color has-text-color">
<div class="wp-block-image is-style-rounded"><figure class="aligncenter size-full is-resized"><img src="https://neliosoftware.com/es/wp-content/uploads/sites/3/2021/08/female-296990_1280.png" alt="Imagen de un perfil de mujer" class="wp-image-35745" width="100" height="100"/></figure></div>

<p class="has-text-align-center has-black-color has-text-color has-small-font-size">⭐️⭐️⭐️⭐️⭐️<br><strong><meta charset="utf-8"><strong>WOW This really works</strong></strong><br><meta charset="utf-8">By far this plugin is the best tool that we have used. All of our clients are delighted working with this plugin. Easy to use and nice UI.</p>

<p class="has-text-align-center has-black-color has-text-color has-small-font-size"><strong><meta charset="utf-8"><strong>Name Surname</strong> </strong>– Position<br></p>
</div>
</div>

<div class="wp-block-column">
<div class="wp-block-group has-medium-padding has-black-color has-text-color">
<div class="wp-block-image is-style-rounded"><figure class="aligncenter size-full is-resized"><img src="https://neliosoftware.com/es/wp-content/uploads/sites/3/2021/08/female-296990_1280.png" alt="Imagen de un perfil de mujer" class="wp-image-35745" width="100" height="100"/></figure></div>

<p class="has-text-align-center has-black-color has-text-color has-small-font-size">⭐️⭐️⭐️⭐️⭐️<br><strong><meta charset="utf-8"><strong><strong>WOW This really works</strong></strong></strong><br><meta charset="utf-8">By far this plugin is the best tool that we have used. All of our clients are delighted working with this plugin. Easy to use and nice UI.</p>

<p class="has-text-align-center has-black-color has-text-color has-small-font-size"><strong><meta charset="utf-8"><strong><strong>Name Surname</strong> </strong></strong>– Position</p>
</div>
</div>
</div>
</div>

**Comment by melchoyce** [comment]
Hey @rraventos, thanks for sharing your pattern! We've actually closed submissions for the time being — [you can find more details here](https://make.wordpress.org/design/2021/07/29/initial-patterns-for-the-patterns-directory-launched/#comments). The next phase of work on the pattern directory will allow you to submit patterns directly to the repository yourself, so please hold onto your pattern for then!
