### ISSUE TITLE
Improve Focus Indicator

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/pattern-directory#363]
When tabbing through the list of patterns some elements have a nice blue focus indicator, and others seem to have the default dotted outline. Maybe we can update the focus state for elements to all use the blue outline. Here's how that could look with elements in the pattern grid and with the category buttons:

<img width="2254" alt="image" src="https://user-images.githubusercontent.com/191598/135487830-5ad68fad-7452-448e-b46a-79849ea6af1a.png">

<img width="736" alt="image" src="https://user-images.githubusercontent.com/191598/135487863-eeddd277-1399-4fb7-8b92-7d83e4e97ae2.png">

**Comment by ryelle** [comment]
Fixed by the site refresh & new parent theme styles.
