### ISSUE TITLE
Curate a collection of patterns to be featured in the pattern inserter

### ISSUE THREAD

**Issue by kjellr** [WordPress/pattern-directory#365]
Related Gutenberg PRs: 

- https://github.com/WordPress/gutenberg/issues/33046
- https://github.com/WordPress/gutenberg/pull/35115

To coincide with efforts to showcase Pattern Directory patterns inside of the inserter by default, there's [a new "Featured" category](https://wordpress.org/patterns/categories/featured/) in the directory. This directory includes a couple patterns for now, but we should fill it up with some favorites from the initial set the community has added. 

Since the pattern directory shows patterns in rows of 3, I think 12 or 18 patterns seems like a decent target for now. 

Let's use this thread to discuss which ones to include in this collection.

**Comment by melchoyce** [comment]
Some favorites:
- https://wordpress.org/patterns/pattern/two-images-with-text-and-buttons/
- https://wordpress.org/patterns/pattern/triptych-with-two-images-and-a-text-area/
- https://wordpress.org/patterns/pattern/callout-over-a-patterned-background/
- https://wordpress.org/patterns/pattern/event-announcement-and-details/
- https://wordpress.org/patterns/pattern/image-on-solid-color-with-description/
- https://wordpress.org/patterns/pattern/image-with-headline-and-description/
- https://wordpress.org/patterns/pattern/header-with-hatched-pattern/
- https://wordpress.org/patterns/pattern/three-images-and-text/
- https://wordpress.org/patterns/pattern/cover-with-title-and-audio/
- https://wordpress.org/patterns/pattern/offset-images-with-descriptions/
- https://wordpress.org/patterns/pattern/event-details/
- https://wordpress.org/patterns/pattern/media-text-with-image-on-the-left/
- https://wordpress.org/patterns/pattern/heading/
- https://wordpress.org/patterns/pattern/partner-logos/

**Comment by beafialho** [comment]
I selected some from each pattern type, not necessarily with similar looking visuals:

https://wordpress.org/patterns/pattern/heading/
https://wordpress.org/patterns/pattern/introduction-with-gallery/
https://wordpress.org/patterns/pattern/callout-over-a-patterned-background/
https://wordpress.org/patterns/pattern/offset-images-with-descriptions/
https://wordpress.org/patterns/pattern/title-area-with-image-and-heading/
https://wordpress.org/patterns/pattern/text-column-over-fixed-background/
https://wordpress.org/patterns/pattern/three-columns-with-offset-images/
https://wordpress.org/patterns/pattern/contact-and-social-links/
https://wordpress.org/patterns/pattern/call-to-action-with-testimonial/
https://wordpress.org/patterns/pattern/social-gallery/

**Comment by kjellr** [comment]
Thank you both! Here's a set that includes many of your choices plus a few of my own. There are 12 total. What do you think of this as the initial set? 

https://wordpress.org/patterns/pattern/event-announcement-and-details/
https://wordpress.org/patterns/pattern/image-on-solid-color-with-description/
https://wordpress.org/patterns/pattern/header-with-hatched-pattern/
https://wordpress.org/patterns/pattern/offset-images-with-descriptions/
https://wordpress.org/patterns/pattern/event-details/
https://wordpress.org/patterns/pattern/media-text-with-image-on-the-left/
https://wordpress.org/patterns/pattern/heading/
https://wordpress.org/patterns/pattern/pricing-table/
https://wordpress.org/patterns/pattern/image-with-description-below-and-to-the-right/
https://wordpress.org/patterns/pattern/image-with-description-on-the-bottom-right/
https://wordpress.org/patterns/pattern/large-header-with-left-aligned-text/
https://wordpress.org/patterns/pattern/three-columns-of-text/

**Comment by melchoyce** [comment]
> https://wordpress.org/patterns/pattern/image-with-description-below-and-to-the-right/
> https://wordpress.org/patterns/pattern/image-with-description-on-the-bottom-right/

These two feel very similar — is there another we can swap in for one of them?

**Comment by kjellr** [comment]
Good call. How about this one? It's incredibly simple, and I can imagine it being used often:
https://wordpress.org/patterns/pattern/simple-call-to-action/

**Comment by beafialho** [comment]
Yeah, that one looks great to me!

**Comment by kjellr** [comment]
Thank you! [These are all live now](https://wordpress.org/patterns/categories/featured/). Seeing them all together, I noticed that they're all pretty light. 😄 Maybe we can pick a few more colorful ones to include as well?

**Comment by beafialho** [comment]
You're right. Here are a few colourful ones we could include:

https://wordpress.org/patterns/pattern/event/
https://wordpress.org/patterns/pattern/image-and-quote-on-a-background/
https://wordpress.org/patterns/pattern/large-background-image-with-title-and-description/
https://wordpress.org/patterns/pattern/three-columns-with-images-and-text/

**Comment by kjellr** [comment]
Thanks! I added three of those. I'll close this issue as resolved for now, though I'm sure we'll re-evaluate this list over time.
