### ISSUE TITLE
Create a library of media and only allow that to be used in patterns

### ISSUE THREAD

**Issue by ryelle** [WordPress/pattern-directory#37]
We have #23 for the idea of setting up asset placeholders (cover block, images, etc) where the end user would add in their own image, but it's also likely that pattern authors will want to add their own assets as part of the pattern (a cover block with a highly designed background image).

- Should we allow asset (image, video, audio, …?) uploads to w.org through the creator?
- Maybe only allow the "Insert from URL", with users uploading media elsewhere?
- Safelist the allowed URLs?
- What if the content at the URL changes/disappears?

Checking for inappropriate material & licensing will be tracked in #22, but could also be part of the upload step here

**Comment by ryelle** [comment]
This is [the list of approved sites for stock photos](https://make.wordpress.org/themes/handbook/review/resources/#recommended-websites-for-images) from the theme review guidelines.

I was thinking about integrating a stock photo site & disallowing uploads, but that wouldn't help the hypothetical person who designs a custom background or header image for the pattern.

**Comment by shaunandrews** [comment]
I think we need to restrict uploads and provide a collection of worry-free assets (images, videos, audio, files) in the media library. We can highlight this in the welcome guide and in media block placeholders:

<img width="389" alt="image" src="https://user-images.githubusercontent.com/191598/113932326-786fb080-97c1-11eb-97b7-bb295e2249f8.png">

<img width="653" alt="image" src="https://user-images.githubusercontent.com/191598/113933191-4579ec80-97c2-11eb-902f-56ed3e886b6d.png">

A good next step would be to integrate some sort of search with a worry-free stock provider, like the approved list you linked to.

**Comment by zackkrida** [comment]
Just chiming in that [Openverse](wordpress.org/openverse) seems like a natural fit well-suited for this task! The only caveat there is that we support _all_ Creative Commons licenses, even those that require attribution. Users would need to be sure to include these attributions (which we make easy with a 1-click copy/paste attribution tool) or use CC0 images exclusively.

We have some dramatic improvements to search result quality coming live in the following week, particularly as related to stock photography search terms (nature, flowers, wallpapers, background, love, and so on) but that affect _all_ searches. I'll send out a ping here when those are live.

Additionally, we currently only support images, but will be launching audio by the end of the year, with plans for video and 3d models next year.

**Comment by ryelle** [comment]
@zackkrida The long-term plan has been to use Openverse, so that's great to hear. Is there an integration in gutenberg that we can use?

> Users would need to be sure to include these attributions (which we make easy with a 1-click copy/paste attribution tool) or use CC0 images exclusively.

Would it be possible to restrict the results to just the CC0 assets? There won't be any validation to check that pattern authors are correctly attributing things, so it would be easier for moderation if we can stick with just CC0.

**Comment by zackkrida** [comment]
@ryelle No Gutenberg integration yet. Results could however definitely be limited to `CC0`. This kind of filtering is avaliable in both the UI:

- https://wordpress.org/openverse/search/?q=warbler&license=cc0

and through Openverse's public API:

- https://api.openverse.engineering/v1/images?format=json&license=cc0&q=warbler

There's some prior art on using Openverse (back when it was CC Search) as part of the Jetpack "External Media Library" feature (the code was written but it was never implemented) so that could be a fast track to integration, otherwise I think what _exactly_ Openverse will look like _within_ core is a very open question.
