### ISSUE TITLE
Pattern Moderation: Show a user-facing reason for why a pattern was declined

### ISSUE THREAD

**Issue by ryelle** [WordPress/pattern-directory#371]
In the modal to learn more if your pattern is unlisted (declined), there should be a string explaining why the pattern was removed. For example:

<img width="498" alt="Screen Shot 2021-10-20 at 2 55 01 PM" src="https://user-images.githubusercontent.com/541093/138154326-bd60824c-9571-4ccf-88c7-1c1bd9433f0b.png">

**Comment by ryelle** [comment]
For copy review, maybe @angelasjin can help, or point me to someone who can?

> WordPress.org has chosen to remove your pattern from the directory for the following reason:

Should this be passive voice instead?

For the reason strings, we have the following "buckets" of reasoning, which can show a generic user-facing explanation. Here are some proposals.

**Rude, crude, or inappropriate**

> This pattern contains content deemed inappropriate for a general audience.

**Copyrighted or trademark issue**

> This pattern contains copyrighted material or uses a trademark without permission.

**Broken or unusable**

> This pattern is broken or does not display correctly.

**Other**

I have no idea for this one, not sure what it would be used for in reality.

**Comment by angelasjin** [comment]
Thanks @ryelle! I think this looks good, I just have some minor edits. 

> WordPress.org has removed your pattern from the directory for the following reason:

The reasoning for **Rude** and **Copyrighted** look good to me.

For **Broken or unusable**, does "does not display correctly" cover "unusable" well enough, or does any further elaboration help? 

For **Other**, what is being flagged here? We could use something generic like:

> This pattern has been flagged for additional review. If you have more questions, please contact _____

**Comment by ryelle** [comment]
> For Broken or unusable, does "does not display correctly" cover "unusable" well enough, or does any further elaboration help?

I thought so, but maybe not? Do you think it needs more explanation?

> For Other, what is being flagged here?

Really anything else, I don't know — I'm going off the flagging reasons when reporting a pattern.

> <i>This pattern has been flagged for additional review. If you have more questions, please contact _____</i>

Who should be contacted?

**Comment by angelasjin** [comment]
For **Broken or unusable**, what you suggested works!

I was thinking through whether we needed the **Other** category, as seems to be a catch all for patterns we don't expect. When a pattern is flagged for **Other**, can a reason be submitted for why it was flagged?

In any event, I like having a catch-all, just in case. Let's keep the explanation real simple, how about: 

> Additional review has been requested for this pattern.

Thanks @ryelle!

**Comment by ryelle** [comment]
> When a pattern is flagged for Other, can a reason be submitted for why it was flagged?

When unlisting a pattern, [the modal](https://user-images.githubusercontent.com/541093/141346796-03174f71-22ec-44fd-b214-0d62ec271454.png) requires an internal note, so the moderator/admin should add details there. That's meant to be for mod use only, not public-facing. It can help us track why patterns are unlisted as Other though, and we can revisit the reasons later.
