### ISSUE TITLE
Pattern Details: Remove restricted height or increase max-height

### ISSUE THREAD

**Issue by shaunandrews** [WordPress/pattern-directory#381]
Currently, the preview on the pattern detail page (i.e. https://wordpress.org/patterns/pattern/large-background-image-with-title-and-description/) has set height of `50vh`, which for many patterns causes an additional scrollbar:

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/191598/142906493-17e1e258-f312-40ac-9ce6-4dd92ab6fa89.png">

It would be better if we could display the entire pattern without needing to scroll _within_ the overall page. Instead of a fixed height, maybe we can switch to a `max-height` with a much larger value like `200vh`.

This might introduce some issues with the drag handles; With the current behavior the drag handles could render outside the viewport. To fix this, I think we'd have to add some logic to ensure the drag handles always appear inside the viewport.

**Comment by ryelle** [comment]
I think this would be fixed by switching to the component suggested in #380, but I'll leave this open too just to make sure.

**Comment by ryelle** [comment]
Closing this, after much discussion with the site refresh (https://github.com/WordPress/pattern-directory/issues/635#issuecomment-1986101759 & https://github.com/WordPress/pattern-directory/pull/650), it's required that we have a fixed-height viewport for previews. https://github.com/WordPress/pattern-directory/issues/672 is open to potentially update this on smaller screens.
