### ISSUE TITLE
Editing & creating patterns on a Rosetta site?

### ISSUE THREAD

**Issue by ryelle** [WordPress/pattern-directory#386]
Currently, it's possible to view a pattern you own on a rosetta site (you stay the author when it's translated). Since you own it, you have permissions to edit it.

<img width="1010" alt="Screen Shot 2021-12-01 at 3 48 22 PM" src="https://user-images.githubusercontent.com/541093/144311579-94b79da6-55ab-4863-8cf6-914efceee86b.png">

Any edits done would not be run through the official translation process, and would be overridden the next time the translations sync. This menu item should actually take you to the parent `en_US` version of the pattern.

----

It's also possible to view the New Pattern editor on rosetta sites. Patterns created here won't go through the translation process either. Should all new pattern creation be disabled? Or should new patterns be allowed, but the content must be English and it goes through the GlotPress translation same as something created on the main site? This last option would let people use the Creator in the language of their choice.

**Comment by naokomc** [comment]
In a similar way to how we request plugin and theme authors to go through it even if they speak another language, I think the author of Patterns should only have permission/ability to translate it through the standard process (suggesting translations on translate.wordpress.org and having reviewed). This can simplify the overall process and reduce confusion. Also, if any inappropriate language is used, locale team translation editors have an easy way to prevent it from being public or fix it after the fact.

Also, I'm leaning toward the idea of requiring new Patterns to be in English. One downside is that it will suppress the number of well-localized Patterns created, but for now, I don't think locale teams have enough resources to review Patterns. Some non-English locale-specific themes and plugins exist on plugins/theme directories, and following the model makes sense.

**Comment by varlese** [comment]
Adding a +1 to Nao's comments (on both points).

In terms of requiring new patterns to be in `en_US` by default, I remember some previous discussion about encouraging the use of non-unique content (i.e. lorem ipsum, quotes from items in the public domain, etc.) to help make it easier to re-use translations and/or translation memory. This is tangential to the actual development, but perhaps some Make teams (Polyglots?) could compile resources with sample text to help make it more accessible to create patterns in `en_US` until other locales are directly supported.

**Comment by ryelle** [comment]
Yep, the patterns are already required to be in English, and all will go through GlotPress for translations (see #224 for that discussion, including the lorem-ipsum suggestion).

> perhaps some Make teams (Polyglots?) could compile resources with sample text 

That's a good idea. There won't be any technical solution in place at launch, but even just a separate page for reference could be helpful, and then it would be in place for when/if we have resources for building the tool itself.

**Comment by ryelle** [comment]
oh, and of course thanks @naokomc & @varlese for thinking about this 😁

**Comment by ryelle** [comment]
As of https://github.com/WordPress/pattern-directory/pull/393 & https://github.com/WordPress/pattern-directory/commit/538635307ab4d3cda0ccb0faf874c96216ad2adf, the "edit" links load the original English pattern, so it's not possible for regular users to edit the translated patterns outside of glotpress. Admins & moderators still can in wp-admin, but that's needed for moderation tools.
