### ISSUE TITLE
Styles are not 1:1 between the editor and front-end

### ISSUE THREAD

**Issue by richtabor** [WordPress/pattern-directory#388]
**Describe the bug**
I created this pattern [here](https://wordpress.org/patterns/?post_type=wporg-pattern&p=9244), but have found that the front-end view of it is very different from what I've made. Is it possible to have consistent styling between the two? It looks like there's stuff missing on the front-end, as the pattern looks fine in the editor, but rough otherwise. 

**Expected behavior**
The editor view of a pattern should be consistent with the front-end view that is rendered on the directory. 

**Screenshots**

Editor: 
<img width="1684" alt="CleanShot 2022-01-06 at 09 02 54@2x" src="https://user-images.githubusercontent.com/1813435/148394600-15face29-7364-49e4-aa5e-8b8e4d6b1b29.png">

End result: 
<img width="1062" alt="CleanShot 2022-01-06 at 09 02 24@2x" src="https://user-images.githubusercontent.com/1813435/148394515-397782a2-55a0-4c18-acfb-ebbbed1f9cd7.png">

**Comment by ryelle** [comment]
That editor screenshot is from wp-admin, but it's even more divergent in the frontend editor:

<img width="881" alt="Screen Shot 2022-01-06 at 10 56 21 AM" src="https://user-images.githubusercontent.com/541093/148411309-bd14e7e1-f8ee-49e3-88ca-7e46c9106974.png">
