### ISSUE TITLE
Unable to set full/wide width for a pattern

### ISSUE THREAD

**Issue by richtabor** [WordPress/pattern-directory#389]
**Describe the bug**
Within the /new-pattern/ experience, I am unable to set a pattern align attribute to wide/full. Is this intentional? 

For [this pattern](https://wordpress.org/patterns/?post_type=wporg-pattern&p=9244), I believe I built it in the post.php view, and copy/pasted it in (which maintained the fullwidth value). 

**Screenshot**
<img width="599" alt="This is a test pattern" src="https://user-images.githubusercontent.com/1813435/148395799-6f3321fb-da0f-4b0b-8396-148e6bb715d1.png">

**Comment by StevenDufresne** [comment]
Just clarifying, in the new-pattern editor you are not seeing this alignment button?.. although copy and pasting seems to apply the setting properly?

![](https://d.pr/A68S2O.png)

**Comment by richtabor** [comment]
I went to double-check but `https://wordpress.org/patterns/new-pattern/` doesn't seem to be correct anymore — did that change? 

![CleanShot 2022-02-21 at 07 04 05@2x](https://user-images.githubusercontent.com/1813435/154951866-39ad3fc5-3af6-4bad-8346-1ac5ddea3803.png)

**Comment by StevenDufresne** [comment]
It should be working for you now.

**Comment by richtabor** [comment]
Thanks, that worked. 

So yea, I'm not able to set blocks as wide or full in this experience — though I can paste in blocks that have the alignment already set to those (although I can't change it).

<img width="969" alt="CleanShot 2022-02-22 at 09 27 53@2x" src="https://user-images.githubusercontent.com/1813435/155152435-99d03847-2151-411a-a3b6-4fedf28bcf58.png">

**Comment by StevenDufresne** [comment]
This is because the image block is the root block. If you were to wrap it in a group, your controls will appear as expected.

@ryelle Why don't we allow alignments on the root?
https://github.com/WordPress/pattern-directory/blob/e53161aec62882a027ce12007a80c9dbc6c7e561/public_html/wp-content/plugins/pattern-creator/src/components/block-editor/index.js#L31

**Comment by ryelle** [comment]
TBH, it's something we inherited from [the site editor](https://github.com/WordPress/gutenberg/blob/0b1df8882563ca8f68086955ccbd3ba3bea78110/packages/edit-site/src/components/block-editor/index.js#L40), I would need to investigate why it's needed there.

**Comment by StevenDufresne** [comment]
I tracked down the code and it appears it was added in [30079](https://github.com/WordPress/gutenberg/pull/30079):

> Remove the alignments from the top level of the site editor because at that point there's no defined layout, so they won't do anything.

So I think we can remove `alignments: []` safely. Not sure yet if the whole `Layout` object can be removed yet.
