### ISSUE TITLE
I should only be able to unlist a pattern if the pattern is listed

### ISSUE THREAD

**Issue by richtabor** [WordPress/pattern-directory#390]
"Unlist" should not be an option, unless the pattern is listed. 

<img width="530" alt="Preview" src="https://user-images.githubusercontent.com/1813435/148395889-657aba4e-0dbc-4d2c-a4b4-d3b0fdb3f397.png">

**Comment by ryelle** [comment]
Only moderators will see this screen, and it's possible we would need to unlist a submitted (pending) pattern if it violates the guidelines.
