### ISSUE TITLE
Layout when viewing my own pattern.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/pattern-directory#398]
## Describe the bug
When I visit my own pattern logged in, the layout feels a bit awkward. The [Options] select seems out of place.

## Screenshot
<img src="https://d.pr/i/LDxeMX.png" width=50% height=50%>

## Potential Solutions

| Option  A | Option B |
| --- | --- |
| Right aligned | No favorites? Do users need the ability to favorite their own patterns? |
| ![](https://d.pr/i/wwn69u.png) |  ![](https://d.pr/i/qWpXcF.png) |

**To Reproduce**
1. Log in
2. Create a pattern
3. Visit your own pattern

**Comment by ryelle** [comment]
cc @shaunandrews

**Comment by jasmussen** [comment]
Putting the Options button on the right seems like a fairly decent solution that would not preclude further enhancements in the future.

**Comment by ryelle** [comment]
Closing after the switch to the new theme. This was discussed in #635 with the design posted in #643.
