### ISSUE TITLE
Media Uploads: Cover block

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/pattern-directory#399]
**Describe the bug**
- The cover block utilizes the `BlockControls` slot and inserts `<MediaReplaceFlow>`([Ref](https://github.com/WordPress/gutenberg/blob/314c9844055220833692bd08c4d1735aca136784/packages/block-library/src/cover/edit.js#L464)). 
- The [`<MediaReplaceFlow>`](https://github.com/WordPress/gutenberg/blob/ebbc7d849776ac4f4a1a4f72d0ec3c84bf688809/packages/block-editor/src/components/media-replace-flow/index.js#L174) adds the ability upload assets if the user has upload permissions detemined in [`<MediaUploadCheck>`](https://github.com/WordPress/gutenberg/blob/3da717b8d0ac7d7821fc6d0475695ccf3ae2829f/packages/block-editor/src/components/media-upload/check.js#L11)

**Question:** Will be modifying upload permissions or do we need to hide this functionality?

**Screenshot**
<img src="https://d.pr/i/TcB9bo.png" width="500px" >

**Comment by ryelle** [comment]
Uploads should already be prevented from #373  (see #37), this sounds like a regression.

**Comment by StevenDufresne** [comment]
Aha. My apologies, works as expected in editor mode. Closing.
