### ISSUE TITLE
Countinue loading svg loader

### ISSUE THREAD

**Issue by sumitsinghwp** [WordPress/pattern-directory#403]
Hi,
i through if result not found then show no found or somthing insted of loading loading curcle.link - https://wordpress.org/patterns/favorites/categories/buttons/
more information see quick video - https://www.loom.com/share/6c628d5000444a18935845b5570879c1

**Comment by ryelle** [comment]
Thanks for the report. This issue is already being tracked here: https://github.com/WordPress/pattern-directory/issues/362
