### ISSUE TITLE
Title management should not remove locale name

### ISSUE THREAD

**Issue by jonoalderson** [WordPress/pattern-directory#404]
Patterns URLs like https://fr.wordpress.org/patterns/ (correctly) append a localization string to the `<title>` elem, but this is removed via JavaScript.

This behaviour should be removed; the title should not be altered.

**Comment by ryelle** [comment]
Thanks for flagging this issue. The title needs to be managed in JS so it can be updated while navigating pages, but I see the difference:

- Index: "Répertoire de compositions de blocs &#124; WordPress.org", and it should be "Répertoire de compositions de blocs &#124; WordPress.org Français"
- Category: "Compositions de blocs : Boutons &#124; WordPress.org", and it should be "Compositions de blocs : Boutons &#124; WordPress.org Français"

So we're missing the locale name "Français".
