### ISSUE TITLE
You can't submit a pattern until it has a title.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/pattern-directory#409]
**Describe the bug**
When you modify content in the editor for a Page/Posts, the `Submit` button becomes active without adding a title. When you are creating a pattern, adding content does not activate the submit button until you create a title. 

**To Reproduce**
1. Go to `new-pattern`
2. Add some content to your pattern
3. Verify that the button is not active
4. Add a title
5. Verify that the button is now active

**Expected behavior**
Any modification to the content or title should turn on the `Submit` button and bring up the submit dialog.
It isn't clear why I can't submit the pattern, even though the title is technically staring me right in the face.

**Screenshots**
![](https://d.pr/i/k83XzZ.png)

**Comment by ryelle** [comment]
A title is required, but I see how that's not clear here.

If we enable the submit button with no title, the modal should still prevent submission until a title is provided, but IMO this is more clear - what do you think?

<img width="626" alt="Screen Shot 2022-02-24 at 10 42 30 AM" src="https://user-images.githubusercontent.com/541093/155557307-36af87e2-3cf5-44a9-9351-44eaa3fa01e0.png">

**Comment by StevenDufresne** [comment]
> A title is required, but I see how that's not clear here.
> 
> If we enable the submit button with no title, the modal should still prevent submission until a title is provided, but IMO this is more clear - what do you think?


Yep, that's what I had in mind. 👍
