### ISSUE TITLE
Tools: Add Internal Notes plugin to composer dependencies

### ISSUE THREAD

**Issue by ryelle** [WordPress/pattern-directory#411]
The [Internal Notes plugin](https://github.com/WordPress/wporg-internal-notes/) is used on the Patterns site, but is not installed in the local environment. Other plugin dependencies are installed with composer, so Internal Notes should get added that way too.

**Comment by coreymckrill** [comment]
Waiting to get [this](https://github.com/WordPress/wporg-internal-notes/pull/8) merged to make adding this as a dependency simpler.
