### ISSUE TITLE
Alignment & spacing is not passed to the frontend preview

### ISSUE THREAD

**Issue by ryelle** [WordPress/pattern-directory#416]
Pulled out of #388. When styles are applied using the custom `wp-container-*` classes, these are not applied to the preview content. This is most obvious if you try to add & center a button:

Editor:
![](https://user-images.githubusercontent.com/541093/156041186-2507d7e0-622c-4ed2-a260-7dddb957083a.png)

Frontend preview:
![](https://user-images.githubusercontent.com/541093/156041187-a97319c0-231b-40e9-8e55-96892a962ae0.png)

The root of the issue is that the inline `style` tags are added on a hook, either `wp_footer` or `wp_enqueue_scripts` ([source](https://github.com/WordPress/gutenberg/blob/3efbac2056858211aeda54e2ba8751817d9aaee7/lib/compat/wordpress-5.9/script-loader.php#L63)), rather than output directly inline, so the API response does not contain the styles (see https://github.com/WordPress/gutenberg/issues/35376#issuecomment-975156782, https://github.com/WordPress/gutenberg/issues/38167).

**Comment by StevenDufresne** [comment]
I was able to create a discrepancy with this block:
```
<!-- wp:group {"align":"wide","gradient":"cool-to-warm-spectrum"} -->
<div class="wp-block-group alignwide has-cool-to-warm-spectrum-gradient-background has-background"><!-- wp:buttons {"align":"wide","layout":{"type":"flex","justifyContent":"right"}} -->
<div class="wp-block-buttons alignwide"><!-- wp:button {"backgroundColor":"luminous-vivid-amber","textColor":"black","width":50,"align":"center","style":{"spacing":{"padding":{"top":"20px","right":"60px","bottom":"20px","left":"60px"}},"border":{"radius":"40px"}},"className":"is-style-fill"} -->
<div class="wp-block-button aligncenter has-custom-width wp-block-button__width-50 is-style-fill"><a class="wp-block-button__link has-black-color has-luminous-vivid-amber-background-color has-text-color has-background" style="border-radius:40px;padding-top:20px;padding-right:60px;padding-bottom:20px;padding-left:60px">Button 1</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group -->
```

| Editor | Preview |
| --- | --- |
| <img src="https://d.pr/i/hv3I8v.png"> |  <img src="https://d.pr/i/OI45bf.png"> |
