### ISSUE TITLE
Pattern flags: Make the "unpublish" threshold a setting field

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/pattern-directory#425]
The "unpublish" threshold is the number of flags a pattern can receive before its status is set back to "pending" so that it will no longer appear in the pattern directory until a moderator has reviewed it. This number is currently [hard-coded](https://github.com/WordPress/pattern-directory/blob/d7f27feb58fcdcf3f9db796b7851f6b2da72988c/public_html/wp-content/plugins/pattern-directory/includes/pattern-flag-post-type.php#L114-L147) at `3` (I told @angelasjin it was `10` but I was mistaken).

Having this number be adjustable from WP Admin would make it easier for moderators to respond if a situation arises where either too many patterns are getting auto-unpublished or too few are. The setting could live on the same page where the "initial status" setting is.

**Comment by angelasjin** [comment]
Thanks @coreymckrill! And to confirm, I think we landed on 5 flags as a good number to trigger "unpublish", is that right?

**Comment by coreymckrill** [comment]
@ryelle I'm working on this and noticed that the custom admin page with the "Default Status" setting is registered in the `pattern-creator` plugin. Which I guess makes sense since the creator is where the default status gets applied. But I was expecting it to be in the `pattern-directory` plugin since that's where all the other [admin-related code lives](https://github.com/WordPress/pattern-directory/blob/trunk/public_html/wp-content/plugins/pattern-directory/includes/admin.php). What do you think about moving the custom settings page stuff to `pattern-directory` to keep it all in one spot?

**Comment by coreymckrill** [comment]
@angelasjin Yep, I also recall we landed on `5`, so I'll make that the default.

**Comment by ryelle** [comment]
> But I was expecting it to be in the pattern-directory plugin since that's where all the other [admin-related code lives](https://github.com/WordPress/pattern-directory/blob/trunk/public_html/wp-content/plugins/pattern-directory/includes/admin.php).

Honestly the two probably shouldn't've been separate plugins in the first place. I did put it there because it directly controlled the creator, but I'm fine with moving it.
