### ISSUE TITLE
Media / Open verse not available 

### ISSUE THREAD

**Issue by bph** [WordPress/pattern-directory#434]
**Describe the bug**
Testing submitting the block pattern editor on, I tried to use a Media from the openversion as per the media modal but I run into errors. 

- /patterns/wp-json/wporg/v1/openverse/search?search=Forest&per_page=24&page=1&_locale=user:1          Failed to load resource: the server responded with a status of 500 ()

When I tried to type in a keyword into the search box 

- index.js:101          GET https://wordpress.org/patterns/wp-json/wporg/v1/openverse/search?search=Trees&per_page=24&page=1&_locale=user 500

when I tried one of the suggested keywords. 

**Screenshots**

![Screen Shot 2022-03-16 at 11 16 39](https://user-images.githubusercontent.com/39980/158624517-1392586d-2bfa-47f3-800d-1a7a66ecfdbf.png)

**Desktop (please complete the following information):**
 - OS: Mac 11.6.1
 - Browser Chrome 
 - Version  99.0.4844.51 (Official Build) (arm64)

**Additional context**
Could be a permissions problem of the site my .org username is bph

**Comment by ryelle** [comment]
The API issue (some outdated configuration) has been resolved, so image searches should be working now.

**Comment by bph** [comment]
Yes, indeed they are working now. I tested it again last night. Thank you.
