### ISSUE TITLE
Duotone doesn't apply on the frontend

### ISSUE THREAD

**Issue by ryelle** [WordPress/pattern-directory#440]
Duotone can be applied in the editor, but is missing from the frontend.

<img width="385" alt="Screen Shot 2022-03-17 at 6 26 52 PM" src="https://user-images.githubusercontent.com/541093/158904505-33d1a4eb-a78d-4a58-9a3e-6d3b13440f5f.png">

This is similar to the layout styles, we need to specifically append the duotone styles: https://github.com/WordPress/gutenberg/blob/ae021224b3c2a72b99b6c23419940e6193543479/lib/block-supports/duotone.php#L419

Thanks to @bph for the report

**Comment by webmandesign** [comment]
Hi @ryelle,

This still does not work for me at https://wordpress.org/patterns/pattern/call-to-action-with-image-and-cut-off-corner/ (The image of rabbit should have blue & red duotone applied.)

When I reload the page on Chrome 99, Win 10, during the page load the duotone seems to be working, but as soon as the page is fully loaded, it stops. Tested also on FireFox 98 with the same result.

Can you confirm this was fixed? Or do you experience the same issue as I do?
Thanks.

**Comment by ryelle** [comment]
@webmandesign I haven't deployed the fix yet. I'll comment here once that's done.

**Comment by webmandesign** [comment]
Oh, sorry about that :) I didn't know how it works.

**Comment by ryelle** [comment]
No worries — usually I do try to deploy faster than this 🙂   It should be fixed on your pattern now.

**Comment by webmandesign** [comment]
It is! Thank you and sorry for my impatience.
