### ISSUE TITLE
Openverse Images from RawPixel fail to insert

### ISSUE THREAD

**Issue by zackkrida** [WordPress/pattern-directory#443]
**Describe the bug**

Attempting to add an Openverse image that comes from the RawPixel source silently fails due to a 403 error.

**To Reproduce**
1. https://wordpress.org/patterns/new-pattern/
2. Open the browser network pane
3. Attempt to add an image block
4. Search for "Columbian Humming Bird" in the modal
5. Select the only result, and click the "Add media" button
6. Observe `403` errors in the console and that the image wasn't added

The url the pattern directory attempts to fetch from RawPixel is:

`https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/pd17-425-tong-calypte-anna-columbian-humming-bird.jpg?w=1200&#038;h=1200&#038;fit=clip&#038;crop=default&#038;dpr=1&#038;q=75&#038;vib=3&#038;con=3&#038;usm=15&#038;cs=srgb&#038;bg=F4F4F3&#038;ixlib=js-2.2.1&#038;s=98d2bd15da0cdcbecafd46b007c86573`

The encoding in the URL seems to be the cause of the 403s. If one decodes it in a tool like https://www.url-encode-decode.com/, you can see the url becomes:

https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/pd17-425-tong-calypte-anna-columbian-humming-bird.jpg?w=1200&h=1200&fit=clip&crop=default&dpr=1&q=75&vib=3&con=3&usm=15&cs=srgb&bg=F4F4F3&ixlib=js-2.2.1&s=98d2bd15da0cdcbecafd46b007c86573

which I can set as an image source correctly:

<img src="https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/pd17-425-tong-calypte-anna-columbian-humming-bird.jpg?w=1200&h=1200&fit=clip&crop=default&dpr=1&q=75&vib=3&con=3&usm=15&cs=srgb&bg=F4F4F3&ixlib=js-2.2.1&s=98d2bd15da0cdcbecafd46b007c86573" />

**Comment by LukaszJaro** [comment]
Just wanted to add I am also having this issue as of yesterday when trying to add media from openverse:

![image](https://user-images.githubusercontent.com/10998875/159016465-a5aad5e5-6ded-47e5-ad76-493e77f3a97e.png)

![image](https://user-images.githubusercontent.com/10998875/159016656-c714ec5a-93a6-463e-84f2-73f027e91a5a.png)

**Comment by webmandesign** [comment]
The same issue here.
