### ISSUE TITLE
Indicitive check for non-patterns at submission

### ISSUE THREAD

**Issue by tellyworth** [WordPress/pattern-directory#449]
We've seen several submissions that - while not spam or objectionable in any way - aren't really patterns. For example:

* A list of text (think "John's favourite movies")
* A blog post
* An entire web page with lots of copywritten content
* Patterns with almost nothing in them, like just a single heading block with some text

These aren't suitable for the directory because they're not really reusable by others. And also because of translation issues: we don't want polyglots having to translate a pattern full of content that might never be used.

We could have some simple heuristic checks to detect this:

* Check the ratio of text content to other stuff
* Check for > n blocks, or > n different types of blocks
* Make sure those blocks have some attributes present, and aren't just default styles
* Look for common types of non-patterns ("unstyled list", "just paragaphs", etc)

Depending on the type and degree of match, it could take various actions:

* Warn the user before submitting
* Send the pattern to pending instead of published
* Publish it but alert a moderator to review
* Use a special status (publish but don't translate or promote?)

This needs some discussion before implementing. Suggestions welcome.

This definitely doesn't need to be done for launch. We'll learn more about non-patterns when we have more submissions.

This might also tie into the idea of better placeholder text for translators.

**Comment by dd32** [comment]
> Check for > n blocks, or > n different types of blocks

Worth noting that I included a "If there's only paragraph blocks, nothing else, send it to spam" in the spam checks. I've since seen that 'bypassed' because they use a list or heading block in there too.

Perhaps that could be extended to be "If you're only using heading/paragraph/list blocks, goto spam" ie. non-content blocks.

My bigger question here though, is, what was the submitters intent? Were they spamming? Were they thinking it was going to be re-usable by others?

> Check the ratio of text content to other stuff

A high number of extracted strings would be a good thing to pause on, and go to pending rather than published/spam. A Pattern shouldn't have more than say, 25 strings, right? 25 oughta be enough for anyone? Maybe that number can be tweaked based on a comparison to other Patterns (This pattern contains more strings than 90% of other published blocks)

**Comment by ryelle** [comment]
I've seen two patterns submitted over the weekend that copy existing patterns - one was a complete copy, and the other copied a pattern, then added a single image to the end.

Some more data points for "non-patterns" I've seen:

- Single image + paragraph
- Single image + quote
- Cover + single child (paragraph)
- Single HTML block

>  what was the submitters intent? Were they spamming? Were they thinking it was going to be re-usable by others?

Some of them look like they're testing out the creator, not designing patterns. Maybe they don't understand what the Pattern Creator is for? but they've clicked through the whole submission modal so… I don't know.

**Comment by ryelle** [comment]
I think `< 3 block types` could be a good criteria - I checked the current block patterns, and this is what comes up for "less than 3 unique block types"

<details>
<summary>Block count results</summary>

```
Scanned 139 patterns.
7 patterns have <3 blocks.
0 patterns have >75 blocks.
There are 6.3 block types per pattern on average, 1 min, and 11 max.
There are 12.2 blocks per pattern on average, 1 min, and 41 max.
```

Pattern has only 1 block type across 1 block.

 - https://wordpress.org/patterns/pattern/heading/
 - https://wordpress.org/patterns/pattern/two-images-side-by-side/

Pattern has 2 different block types across 2 blocks.

 - https://wordpress.org/patterns/pattern/bold-condensed-ampersand-list/
 - https://wordpress.org/patterns/pattern/image-with-description-on-the-bottom-right/
 - https://wordpress.org/patterns/pattern/full-width-image-of-space-with-big-headline/
 - https://wordpress.org/patterns/pattern/large-header-with-a-heading/

Pattern has 2 different block types across 4 blocks.

 - https://wordpress.org/patterns/pattern/three-buttons/

Run across the "unlisted" patterns (all reasons, includes spam etc)

```
Scanned 58 patterns.
27 patterns have <3 blocks.
1 patterns have >75 blocks.
There are 3.3 block types per pattern on average, 1 min, and 13 max.
There are 9.3 blocks per pattern on average, 1 min, and 124 max.
```

</details>

While most of these are wordpressdotorg patterns, I think what we want for the directory now should be a bit more complex. 

The unlisted pattern with 124 blocks is a whole page, so I wonder if we could also check for > 75 blocks for the other end of "Not a Pattern".

I think in both cases you could catch valid patterns, but maybe failing this check submits the pattern as pending (not unique now, but when patterns auto-publish this would trigger manual review).

**Comment by ryelle** [comment]
Added a PR to check for a few "easy" things (block count, flagged words in title) #477

**Comment by ryelle** [comment]
Closing this issue. If we rethink moderation & want to add new automated checks, we can do that in a new issue.

**Comment by richtabor** [comment]
I've been running into the < three blocks issue here and there. It prevents me from doing more simple patterns, that still look nice, like this below. I'm not sure if the requirement is necessary to be honest. 

<img width="1102" alt="CleanShot 2023-04-18 at 15 06 58" src="https://user-images.githubusercontent.com/1813435/232879997-69acc402-6a31-4fa2-b253-93454251a7a9.png">

**Comment by ryelle** [comment]
The < 3 blocks check was added to make sure people submitting were submitting full patterns that show the creativity of the block editor, not just a heading + paragraph or plain gallery, etc.

You could wrap the cover or paragraph here in a group to pass the check.

I'm sure there will be a discussion to update the moderation & guidelines when we redesign the site, we can revisit the block count rules then.
