### ISSUE TITLE
What is the pattern description?

### ISSUE THREAD

**Issue by ryelle** [WordPress/pattern-directory#45]
In core, these descriptions are used as alternative text and are only exposed to screen reader users. From [the documentation:](https://developer.wordpress.org/block-editor/developers/block-api/block-patterns/)

> A visually hidden text used to describe the pattern in the inserter. A description is optional but it is strongly encouraged when the title does not fully describe what the pattern does.

For example, "Two columns of text, each with an image on top." or "A large hero section with a bright gradient background, a big heading and a filled button."

When filling out the pattern creator, the description is just called "description", with help text "What is this pattern for?" — this makes it seem like this should be marketing copy, which would _not_ be appropriate as non-visual descriptive text.

Should we change the name of the description field? Or have two separate fields for alternative text (used as `description`/alt text in pattern lists) and marketing copy (not used in core, but searchable/displayed on wordpress.org/patterns)?

**Comment by shaunandrews** [comment]
I initially thought we'd have separate fields for "marketing copy" and the "alternative text," but seeing it in practice worried me a little:

<img width="391" alt="image" src="https://user-images.githubusercontent.com/191598/113441356-204d3e80-93bc-11eb-8a3e-5aa8e3332be4.png">

The title, details, and alt text are all kind of asking the same question but with very subtle differences in the expected answer.

My designs have all been expecting some "marketing-type" text, but perhaps we don't need it right now.

Instead, maybe we should focus on the pattern's title and categories as the primary descriptors, and include the accessibility text as an optional field when submitting.

<img width="392" alt="image" src="https://user-images.githubusercontent.com/191598/113441626-9ce01d00-93bc-11eb-8571-e359b66872a6.png">

This will change the pattern detail's page, replacing the details with the pattern's categories:

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/191598/113441699-baad8200-93bc-11eb-8610-e85cb6aaa3f1.png">

**Comment by ryelle** [comment]
> Instead, maybe we should focus on the pattern's title and categories as the primary descriptors, and include the accessibility text as an optional field when submitting.

I like it! Do you think that might lead to overly long titles though?

**Comment by shaunandrews** [comment]
Maybe, though that might be ok. I imagine there will be some limit for the length of the title. If we start to see lots of patterns with ridiculously long titles, then it would be a good sign that we need to add a new field.

**Comment by ryelle** [comment]
Description has been implemented in the submission modal.
