### ISSUE TITLE
Unlisted patterns: Can't re-publish from the WP Admin post edit screen

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/pattern-directory#450]
While working on #448 I noticed that (in local dev at least) if you try to publish a pattern that is currently unlisted you get some weird behavior:

* First it will update the post status to `pending-review` i.e. Spam. But the "Are you ready to publish?" sidebar stays open.
* If you then click the Publish button again, you can an error saying the status must be `pending-review`.

It looks like the error message part can be resolved by changing [this permission check](https://github.com/WordPress/pattern-directory/blob/trunk/public_html/wp-content/plugins/pattern-directory/includes/pattern-validation.php#L212). `edit_others_patterns` is not actually a valid raw cap for the pattern post type, because it doesn't register any custom caps. So it should be

```php
! current_user_can( $post_type->cap->edit_others_posts )
```

or perhaps better yet would be

```php
! current_user_can( 'edit_post', $prepared_post->ID )
```

For the first problem, though, I can't figure out why hitting the Publish button is switching the post status to Spam...

**Comment by ryelle** [comment]
IIRC it should be `! current_user_can( $post_type->cap->edit_others_posts )`, because it's only editors that can bypass this check.

> For the first problem, though, I can't figure out why hitting the Publish button is switching the post status to Spam...

Are you sure it's not that it detects your pattern is spam? The spam validation still runs on wp-admin published patterns too.

**Comment by coreymckrill** [comment]
> Are you sure it's not that it detects your pattern is spam? The spam validation still runs on wp-admin published patterns too.

Ah, I bet that's what it is.
