### ISSUE TITLE
Designer view: link to profile

### ISSUE THREAD

**Issue by bph** [WordPress/pattern-directory#456]
It would be quite helpful to have a link to the WordPress profile page of the designer, in the header of the list view per designer. 
![Screen Shot 2022-03-23 at 15 02 40](https://user-images.githubusercontent.com/39980/159776645-ea5fea93-5c72-4144-976e-3c6b6ce168da.png)
[Example from this page](https://wordpress.org/patterns/author/dhansondesigns/)
In the header of the page it says: "4 patterns by Derek Hanson". Maybe the Name could hold [the link to the profile page](https://profiles.wordpress.org/dhansondesigns/)?

**Comment by ryelle** [comment]
I'm going to close this issue, since this context bar is probably going away, see https://github.com/WordPress/pattern-directory/issues/580.

**Comment by richtabor** [comment]
Could be interesting perhaps in the "More from this designer" area on single pattern perhaps. 

Maybe the name links to their profile, but there's a "View all" link. 

<img width="1024" alt="CleanShot 2023-05-17 at 19 26 41" src="https://github.com/WordPress/pattern-directory/assets/1813435/310d7508-a2dc-46e4-92a8-f2509c06a5ba">

**Comment by richtabor** [comment]
Those first two patterns ☝️ 🫣
