### ISSUE TITLE
Add a link to New pattern on the home page of patterns directory

### ISSUE THREAD

**Issue by jennydupuy** [WordPress/pattern-directory#460]
**Describe the enhancement**
The access to the patterns editor is not easy because a link to the editor is missing from the home page of the patterns directory.

When the visitors are logged into their wordpress.org account, they should be able to access the patterns editor as soon as they arrive on the directory homepage (https://wordpress.org/patterns/).
Currently, one must click on "Favorites" to then access the "New pattern" menu item.

**Expected behavior**
It would be more efficient to place a "new pattern" link next to the "favorites" link, and eventually an additional link to "My patterns", only when the user is connected at wordpress.org.

**Screenshots**
![add-link-to-patterns-directory](https://user-images.githubusercontent.com/75045144/159962381-1b416d6a-e6ae-4daa-a043-7faa01c70f86.png)

**Comment by jennydupuy** [comment]
Thank s a lot 
How fast!

**Comment by ryelle** [comment]
@jennydupuy It was actually in the works already when you made the issue, but thanks for the prompt 😁
