### ISSUE TITLE
Title is replaced by generic title on search page.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/pattern-directory#464]
**Describe the bug**
When you search for a pattern using the search bar, the page title that is first rendered by the page is correct. It is subsequently replaced by a less specific (worse) title by javascript.

**To Reproduce**
Turn off javascript via inspector tools
1. Go to `/patterns`
2. Search for 'tomato'
3. Notice the title is: `Search Results for “tomato” | WordPress.org`

Turn javascript on:
1. Go to `/patterns`
2. Search for 'tomato'
3. Notice the title is: `'Block Pattern Directory | WordPress.org'`

**Expected behavior**
The original title should continue to exists.

**Comment by ryelle** [comment]
The new theme uses the expected "Search Results for &#8220;tomato&#8221; &#8211; WordPress.org"
