### ISSUE TITLE
Need customisation support based on different screen sizes to make responsive designs

### ISSUE THREAD

**Issue by Gtarafdar** [WordPress/pattern-directory#466]
**Describe the bug**
I'm talking about the pattern creation editing panel (https://wordpress.org/patterns/new-pattern/).
Now it's tough to manage different responsive designs for Block Patterns. As I need to set different sizes of images for mobile devices, I can't do that, there is no additional CSS field option, and for that reason, I cannot set custom media queries to make responsive designs. It's tough to achieve a fully responsive design.
Check this SS: https://ibb.co/6v70K62
If I get the option to set different button padding options for small screens, the design will be more attractive. Also, you can see the line break in the heading text. If I get the option to change the typography for different screens, that issue will not happen.
Please consider it. Otherwise, it will be challenging for all of us.

**To Reproduce**
1. Go to  (https://wordpress.org/patterns/new-pattern/).
2. Create any design
3. check preview (Mobile or tab)
4. There is no different option to change the button size for the different screens; if you change the padding in the mobile preview, it changes globally. 

**Expected behavior**
We need different media query support to create responsive designs. Elementor page builder has that feature. You can have a look into that to get an initial start. In addition, we need additional CSS field support for the block pattern-creating platform. 

**Screenshots**
[If applicable, add screenshots to help explain your problem.] SS: (https://ibb.co/6v70K62)

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome]

**Additional context**
The same issue is available in the default Block Editor. We need third-party plugin support to make perfect responsive designs. Please have a look into this. It's a necessary thing. Thanks.

**Comment by ryelle** [comment]
Hi @Gtarafdar! Is this something you can do in the core editor? If not, it might be worth checking the gutenberg issues and suggesting it there. The Pattern Creator needs to stick with the functionality of the core editor. We can't add any plugin features like Elementor, since people using these patterns might not have those plugins installed.

**Comment by dd32** [comment]
This is definitely something that can't be supported at the present time, as all CSS is provided either a) inline, or b) as part of the WordPress/Gutenberg block CSS.

Gutenberg may be able to add functionality to add conditional media-query CSS through an inline `<style>` element, but it doesn't currently do that, and as a result, it's not possible for Patterns to offer that (Where Patterns are just a group of Blocks, nothing extra specialised).
