### ISSUE TITLE
Reduce confusion for Rosetta site/non-English users

### ISSUE THREAD

**Issue by naokomc** [WordPress/pattern-directory#471]
Even though only English submissions are accepted to the directory, the current process doesn't give any hint to suggest the rule. This can be confusing especially to users entering the pattern editor from a Rosetta site.

### Suggestion

How about mentioning the content language rule (and even other often-misunderstood guideline items) with a link to the [guideline](https://wordpress.org/patterns/about/) at the beginning of the submission process?

### Current Process

The "Draft saved" the message says "This pattern is only visible to you. Once approved it will be published to everyone." so users will feel encouraged to publish the pattern.

<img width="800" alt="image" src="https://user-images.githubusercontent.com/34067/161899588-c3251fbe-15c3-4ed3-b6e3-3e271d63afe4.png">

When I hit the submit button, the subsequent messages are translated but don't mention anything about the guideline.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/34067/161899874-9ecd23cb-a635-4e5d-8523-81f93fff9fe9.png">

Category selection
<img width="500" alt="image" src="https://user-images.githubusercontent.com/34067/161899915-b73126a6-16c1-4f26-ab5c-1eb695977b28.png">

Thank you page
<img width="500" alt="スクリーンショット 2022-04-06 14 08 33" src="https://user-images.githubusercontent.com/34067/161900233-96056afb-8b55-48ee-a448-161c2ff47e26.png">

**Comment by ryelle** [comment]
@naokomc Thanks for the suggestion - I put something together on #475, what do you think of this?

Persistant banner on the creator:
![ja-banner](https://user-images.githubusercontent.com/541093/162830536-d400f21c-d537-4be6-abe4-f456b92a2833.png)

And a new step in the submission modal with some guideline reminders:
![ja-modal](https://user-images.githubusercontent.com/541093/162830605-4246da94-8ef8-494a-9ff5-025f68f8141a.png)

**Comment by naokomc** [comment]
@ryelle Looks great, exactly what I was hoping to see. Thanks!
