### ISSUE TITLE
Block patterns contributor badge for the author and team

### ISSUE THREAD

**Issue by kafleg** [WordPress/pattern-directory#472]
We've different badges for contributors. So, I'd like to see contributors' badges for patterns authors (creators) and the patterns team who run and monitor the patterns directory. 

For those who submit the pattern and live, the badge should auto-assigned. With badges, we can recognize contributors and motivate them to submit patterns as well. 

Here you can see the request for adding a badge for the author of the pattern. https://twitter.com/Gtarafdarr/status/1508475635760435206

**Comment by colorful-tones** [comment]
@kafleg this is such a great idea! I believe that coordinating with one of the Meta teams may expedite this?

**Comment by kafleg** [comment]
I already talked with the Meta team and they suggested I make a ticket for it. But, I think the **design of the badge** is also necessary. 

CC: @dd32 @angelasjin

**Comment by colorful-tones** [comment]
I would be happy to take a stab at the badge design and share a Figma link. 

I’m familiar with some of the badges already and believe they’re mostly relying on Dashicons?

**Comment by colorful-tones** [comment]
@kafleg I've [started to try and figure out where/how I might help whip up an icon](https://wordpress.slack.com/archives/C02RRH4GA/p1650489911929809) in Slack #meta-devhub. That might not be best avenue and I'm open to suggestions.

Since existing badges seem to leverage Dashicons. Then I would think that [`block-default` icon](https://developer.wordpress.org/resource/dashicons/#block-default) would be adequate for the badge? 🤔

**Comment by dd32** [comment]
> I would be happy to take a stab at the badge design

All badges should be dashicons at present, unless there's an actual absolute requirement for something different.

This will likely change in the future, as dashicons are deprecated.. but for now..

Per https://make.wordpress.org/meta/handbook/documentation/profile-badges/ the things needed are:
 - Dashicon. (`block-default` makes sense to me)
 - Colour (Foreground Colour, plus a Background-colour specifically for Team)  - That's not taken already
 - Whether there needs to be a 'Pattern Team', and/or 'Pattern Contributor' group.
 - If team; where to get the initial list of members from (I'm assuming role on /patterns/ >= editor for now as the initial seed would be fine)

**Comment by kafleg** [comment]
@dd32 We can assign the badge for the contributors for now. When we finalize the list of patterns team, then we can assign them. (Team badge will be manually assigned) but the contributor's badge will be auto. 

I think we call it the Patterns Team(Like Themes Team, Core Team, Accessibility Team).

**Comment by colorful-tones** [comment]
@dd32 @kafleg 

- [x] Dashicon: [`block-default` icon](https://developer.wordpress.org/resource/dashicons/#block-default)
- [x] Colour: [`#c3bc00`](https://g.co/kgs/Uk2XaZ) - I verified that it was not taken already.
- [x] Name: **Patterns Team** (based on @kafleg )
- [x] role on [/patterns/](https://wordpress.org/patterns/) >= editor for now - sounds good to me.

I would offer to update the Handbook > Profile Badges page, but I do not have access. Feel free to add me `colorful-tones` and I can update. Thanks! 👍

**Comment by ryelle** [comment]
How about #924bb3 for the color? Or something near that? It would be nice to call back to the navy-purple of the themes team. I'm also not totally sold on the `block-default` icon either, what do you think of using [`layout`](https://developer.wordpress.org/resource/dashicons/#layout)?

It would look like…

<img width="522" alt="Screen Shot 2022-04-21 at 3 00 09 PM" src="https://user-images.githubusercontent.com/541093/164534046-a03ea653-12ef-4c27-b03a-b644852da1bd.png">

**Comment by colorful-tones** [comment]
@ryelle the `#924bb3` sounds good to me! re: Themes Team... totally makes sense 👍  Also, I thought about `layout` icon, and I'm glad you suggested it. I vote for [`layout`](https://developer.wordpress.org/resource/dashicons/#layout) now as well 😄 .

**Comment by kafleg** [comment]
Really amazing! Excited to see badges in the profiles. 👯‍♂️

**Comment by dd32** [comment]
Badges created, and users assigned per:
> role on [/patterns/](https://wordpress.org/patterns/) >= editor for now - sounds good to me.

Users can be edited via: https://profiles.wordpress.org/wp-admin/admin.php?page=bp-groups&gid=52&action=edit

Note, Pattern Author badge was created, but isn't currently assigned to anyone, other [than me (for testing)](https://profiles.wordpress.org/dd32/)

**Comment by kafleg** [comment]
Thanks a lot and it's great to see that Patterns badges are in profiles. And it's amazing to see Author badge in your profile too.

P.S.:  I don't have access for the profiles.wordpress.org site.

**Comment by dd32** [comment]
Set the initial pattern author members too.

```
SELECT distinct post_author FROM wp_posts WHERE post_type = 'wporg-pattern' AND post_status = 'publish' AND post_author>0

cat sql-result  | xargs -I% wp --url=https://profiles.wordpress.org/  bp group member create --group-id=pattern-author --user-id=%
```

I haven't looked into adding anything to automatically assign to the group.
That'll need a branch in the `wporg-profiles-association-handler.php` Profiles plugin, and code on publish in the Pattern Directory to call that.
Other option, would be to generalise the code in there, and instead, add a generic WordPress.org function for `assign_badge( 'group-name-here' )` which handles all that. Would go well with a `record_profile_activity( '.....' )` method.

**Comment by colorful-tones** [comment]
This is looking good from my end.

I tested against a few key (quantity) Pattern contributor profiles:

- [Brian Gardner](https://profiles.wordpress.org/bgardner/)
- [iniyan](https://profiles.wordpress.org/iniyan/)
- [WebMan Design | Oliver Juhas](https://profiles.wordpress.org/webmandesign/)

> I haven't looked into adding anything to automatically assign to the group.

@dd32 does this mean that there is currently no code hooked up to auto-assign theses badges should a new user create one? I’m assuming this based on your SQL query, and just wanted to clarify. Thanks for all your guidance.

@kafleg - this would likely warrant a Make post to announce these new badges, correct?

Or am I jumping the gun? We might want to wait to have more pieces in place: programmatic user hook up and does there need to be a call for an official Pattern Team? Looking for guidance there. Thanks

**Comment by dd32** [comment]
> does this mean that there is currently no code hooked up to auto-assign theses badges should a new user create one?

Correct, there's more work needed here. I just didn't have time to dig into the automation side of it at the time.

**Comment by kafleg** [comment]
I think it's better to wait for the announcement post until we have an auto badge assigned to the Patterns contributor.

**Comment by dd32** [comment]
Noting that all pattern authors submitted up until now were assigned the badge semi-manually, going forward it should be instant.
