### ISSUE TITLE
Update blockGap handling to support arrays too

### ISSUE THREAD

**Issue by ocean90** [WordPress/pattern-directory#474]
**Describe the bug**
Since https://github.com/WordPress/wordpress-develop/commit/f187393d0a2d006bcbbf7e42cb2e882b94c37122 the block gap value can also be an array. At least this line needs to be updated for the change to not throw warnings like "preg_match() expects parameter 2 to be string, array given":

https://github.com/WordPress/pattern-directory/blob/fe9866ef5a942d49ae9168bc92f01790b2e1257d/public_html/wp-content/themes/pattern-directory/includes/inline-styles.php#L48-L52

**To Reproduce**
I noticed these warnings in the #dotorg-warnings channel on Slack.

**Comment by ryelle** [comment]
Thanks for tracking down the issue! This file is a set of functions forked from core, so they just needed to be updated with the current versions, done in https://github.com/WordPress/pattern-directory/commit/c0d8f6a4a66a66b1c33d51339637e674d5aa90ad.
