### ISSUE TITLE
Directory home page / list view

### ISSUE THREAD

**Issue by tellyworth** [WordPress/pattern-directory#48]
The home page view of the Pattern Directory should feature a masonry-style grid, and a short list of filters/types for refining the view:

![patterns-signed-out-1x](https://user-images.githubusercontent.com/7200686/112904267-698b5d00-9134-11eb-91e5-29a3baad37d6.gif)

Along the top of the patterns grid is a “sort by” dropdown, followed by a list of selected categories, and then a search box. Changing the sorting or selecting a category updates the grid and exposes a secondary UI that indicates the current criteria (category, author, tag, etc) along with space for displaying related information like related categories or an author’s website.

<img width="1024" alt="image-8" src="https://user-images.githubusercontent.com/7200686/112904613-ecacb300-9134-11eb-88d7-3cd821be45f5.png">

The Patterns site focuses around a masonry-style grid of rendered patterns. The initial designs have a discrete “Load more” button, but infinite scroll could be added in future. Within the grid, Patterns focus on showing there rendered output, unlike the Plugins/Themes directory where a static image is required.

![mason-grid-2](https://user-images.githubusercontent.com/7200686/112905307-eb2fba80-9135-11eb-8b4d-245def33b2ee.gif)

**Comment by iandunn** [comment]
What's a good way to determine the related categories? 🤔 

If there'll be a hardcoded or manually curated list of categories, then we could just have a hardcoded map.

If not, then maybe look at patterns that have multiple categories assigned, and then count the number of times categories are used together? e.g., The selected category is `header`, so look all the patterns with `header` assigned`, and then count the instances of other categories, and pick the top 3. That would probably have lots of false-positives and false-negatives, though.

WordNet could be helpful, but we'd have to know [which synset to specify](http://wordnetweb.princeton.edu/perl/webwn?s=header&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=), and it wouldn't work for jargon like `hero`. It looks like they'd also want a citation in the UI, which feels like a dealbreaker to me. 

Maybe something using [significant term aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-significantterms-aggregation.html) or [synonyms](https://www.elastic.co/blog/boosting-the-power-of-elasticsearch-with-synonyms) in ElasticSearch?

**Comment by iandunn** [comment]
[Datamuse](https://www.datamuse.com/api/) looks interesting.

**Comment by ryelle** [comment]
The design used here is out of date - the site no longer needs related categories here, and we're not using masonry.
