### ISSUE TITLE
Something issue on pattern.

### ISSUE THREAD

**Issue by sumitsinghwp** [WordPress/pattern-directory#486]
Hi,

Something issue on pattern. more informatio9n you can see quick video 

https://www.loom.com/share/2035a49659184cb09a13480284849a8c

**Comment by ryelle** [comment]
@sssumitsingh The issue where an image disappears in a Media & Text block has already been reported here: https://github.com/WordPress/pattern-directory/issues/473. Is that the problem you're referring to?
