### ISSUE TITLE
Image asize issue on frontend

### ISSUE THREAD

**Issue by sumitsinghwp** [WordPress/pattern-directory#487]
Hi,

I have created pattern and when go to frontend view then image size not same nad not working image size which i have added as a pixcel in image.

More inforamtion you can see my pattern SS.
![Social-Proof-–-Block-Pattern-WordPress-org](https://user-images.githubusercontent.com/23701579/166092924-916918c5-5b5c-46a0-b657-650019821ef7.png)

https://wordpress.org/patterns/?post_type=wporg-pattern&p=51375

**Comment by ryelle** [comment]
It looks like the images are resized but are keeping the aspect ratio. I'm seeing the same thing on a plain WordPress install, so this issue should be reported up to gutenberg: [file a bug report](https://github.com/WordPress/gutenberg/issues/new?assignees=&labels=&template=Bug_report.yml).
