### ISSUE TITLE
Need to add spacing before content

### ISSUE THREAD

**Issue by minaldiwan** [WordPress/pattern-directory#497]
In wordpress pattern page we need to add spacing before content in Ipad-Air, Ipad-Mini and mobile device.

[link:https://wordpress.org/patterns/pattern/instagram-hero/](https://wordpress.org/patterns/pattern/instagram-hero/)

Below  I have added screenshot
![CleanShot 2022-06-02 at 15 34 27 2@2x](https://user-images.githubusercontent.com/77973388/171828796-8e24a304-25d1-44f2-9d87-d3b50f4fb865.png)
![CleanShot 2022-06-02 at 15 34 27@2x](https://user-images.githubusercontent.com/77973388/171828821-a26f3104-6941-40ab-9a13-c0048cf2929e.png)
![CleanShot 2022-06-02 at 15 35 23@2x](https://user-images.githubusercontent.com/77973388/171828834-62d9052d-bf4f-4755-9ac9-ca17a9d80651.png)

**Comment by ryelle** [comment]
Thanks for your report! This has already been flagged, and is being tracked in #490.
