### ISSUE TITLE
Pattern Creator: URL popup covers block toolbar

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/pattern-directory#499]
Moved from: https://meta.trac.wordpress.org/ticket/6349

**Describe the bug**
>Hi,
>
>When i am trying to select text as a bold then coming href popup and i can't able to do. more information see quick video.
>
>https://www.loom.com/share/c8ae1fd195094f7784143c7940702d9a

[@sumitsingh](https://profiles.wordpress.org/sumitsingh)

<img width="990" alt="Screen Shot 2022-06-22 at 1 04 55 PM" src="https://user-images.githubusercontent.com/541093/175096264-1089d1fa-9603-4071-bdab-e1a1d2d1e135.png">

**Comment by ryelle** [comment]
Does this happen in the core editors too, or is this specific to the Pattern Creator implementation?

**Comment by ryelle** [comment]
This does not seem to be happening anymore, in my testing the link popover appears below the text.
