### ISSUE TITLE
Remove reliance on gutenberg_get_editor_styles()

### ISSUE THREAD

**Issue by dd32** [WordPress/pattern-directory#508]
**Describe the bug**
As of https://github.com/WordPress/gutenberg/pull/41306 `gutenberg_get_editor_styles()` is no longer in Gutenberg 13.7 (Released 7hrs ago), but it's used within the Pattern Creator:

https://github.com/WordPress/pattern-directory/blob/bd9e5777151e975286dad10e285631a3e95c3893/public_html/wp-content/plugins/pattern-creator/pattern-creator.php#L138-L145

This was noticed via a fatal error in production in the pattern creator on https://wordpress.org/patterns/new-pattern/:
```Uncaught Error: Call to undefined function WordPressdotorg\Pattern_Creator\gutenberg_get_editor_styles() in wp-content/plugins/pattern-creator/pattern-creator.php:142```

~It's worth noting that the removed file, `gutenberg/lib/compat/wordpress-5.9/edit-site-page.php` IS present in the version of Gutenberg currently in use on the pattern directory.~

~Unable to reproduce at a glance, but looks like if it's not currently an issue, it will be in a future gutenberg release when that file is removed.~ reproduced, I had an old Gutenberg version installed on my test site 🤦 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dd32** [comment]
Noting that in #509 I just copied the function from Gutenberg 13.6 to the Pattern Directory, quick fix to resolve the fatals, requires some more digging to find the Gutenberg replacement function.

**Comment by ryelle** [comment]
Looks like this was replaced with `get_block_editor_theme_styles` — I'm not sure why I stuck with the older function when I have updated others, but hopefully this can be a drop-in replacement.
