### ISSUE TITLE
Media & text block validation error from blocks in the pattern directory

### ISSUE THREAD

**Issue by carolinan** [WordPress/pattern-directory#511]
**Describe the bug**
This is a copy of https://github.com/WordPress/gutenberg/issues/42805 because I do not know where this can be solved.

There was a markup change for the Media & text block.  The change included a deprecation, and there are no block validation errors when testing blocks that are placed directly in the editors: But there are block validation errors for patterns in the pattern directory.

Should I just report the individual patterns once next version of Gutenberg is released?

**To Reproduce**

1. Deactivate Gutenberg. Activate Twenty Twenty-Two.
2. Using WordPress 6.0 or newer, go to either editor and add two media and text blocks: One with media on the left, and one to the right. Save.
3. Activate Gutenberg **trunk**. Currently 13.8.0-rc.1
4. Refresh the editor where you placed the blocks.

You should see errors for block patterns in the block pattern directory if you open the browser developer tools console,
but not for any of the blocks that are placed in the editor.

**Expected behavior**
I expected there to not be any block validation errors

**Screenshots**
https://github.com/WordPress/gutenberg/pull/40806#issuecomment-1193958784

**Comment by ntsekouras** [comment]
This is a Gutenberg issue. We should close this.
