### ISSUE TITLE
Pattern preview: Image placeholder doesn't show

### ISSUE THREAD

**Issue by beafialho** [WordPress/pattern-directory#524]
Where an image block placeholder should show in the pattern preview, it does not.

**Editor**
<img width="1007" alt="Captura de ecrã 2022-09-26, às 12 13 38" src="https://user-images.githubusercontent.com/65220155/192262718-2d188306-83ad-4818-bff9-854f31a75cb4.png">

**Preview**
<img width="952" alt="Captura de ecrã 2022-09-26, às 12 10 22" src="https://user-images.githubusercontent.com/65220155/192262734-9f66be19-7e69-4cf1-9537-cc0663fe1392.png">

**Comment by ryelle** [comment]
@beafialho Is the the frontend view of the pattern? Should the placeholder be visible on the frontend?

**Comment by beafialho** [comment]
Yes @ryelle the placeholder dotted lines should be visible in the front end.

**Comment by ryelle** [comment]
@beafialho Sorry, I meant on core too — I'm asking if this needs to be a customization we build for the pattern previews, or an existing core feature that's not working on the pattern directory.

**Comment by beafialho** [comment]
Oh, I'm not sure actually. Could you answer that @mtias?

**Comment by ryelle** [comment]
@beafialho I rephrased my comment a little to make the question (hopefully) more clear 🙂

**Comment by beafialho** [comment]
@ryelle thank you for rephrasing! 

In my opinion, the placeholder should be a customization we build for the pattern previews. I'd expect to see that placeholder there due to the nature of these patterns, but I would not expect to see it on the frontend in a site I create, for instance.

**Comment by ryelle** [comment]
Okay, I've changed this to an enhancement since it's a new feature request.

**Comment by beafialho** [comment]
Oh I understand now how that may have been confusing since I added the "Bug" category 😄 Thanks!
