### ISSUE TITLE
Consider a way to mark patterns as "Site building"

### ISSUE THREAD

**Issue by jameskoster** [WordPress/pattern-directory#534]
The pattern categories that appear in Gutenberg are being revised in https://github.com/WordPress/gutenberg/issues/44501. As a part of that process a number of pattern types have been identified that users should find only when "site building", IE editing a template:

- Headers
- Footers
- Post Content (for Query loops)
- Comments (for Single templates)
- Pagination / Comment pagination
- Archive headings
- 404 (when editing the 404 template)
- Search (when editing the search template)

As we connect the Inserter with the Pattern Directory (https://github.com/WordPress/gutenberg/issues/44611), a need arises to mark site building patterns appropriately so that they can be omitted when editing content. 

I don't know if this distinction should be internal only, or whether we might want to include it in the Pattern Directory filtering options as well. That probably needs some design exploration and/or input from the community.

**Comment by ryelle** [comment]
> whether we might want to include it in the Pattern Directory filtering options as well

There was some exploration for front-end filtering here: https://github.com/WordPress/pattern-directory/issues/395.

I've marked this needs design for literally how to mark patterns as "site building", since it sounds like something that should be decided by the pattern author in the creation flow.

**Comment by jameskoster** [comment]
Perhaps it's only the _category_ that needs to be marked as "site building"? Then the block editor car surface those categories contextually (IE when editing templates). 

There's certainly a design element, but I imagine there are many ways to approach the implementation on the engineering side too.

**Comment by ryelle** [comment]
Does this already work some way in Gutenberg? I think the pattern directory would follow however it's implemented in Gutenberg.

**Comment by jameskoster** [comment]
Not that I'm aware of.

**Comment by jasmussen** [comment]
Worth noting that I would think both regular and site building patterns could be available in the site editor, whereas the post editor would only contain the regular patterns.

**Comment by jameskoster** [comment]
Agreed, with the nuance that the _template_ editor (accessed through the post editor 🙈) should also surface site building patterns.

**Comment by ryelle** [comment]
From https://github.com/WordPress/gutenberg/issues/44501 it sounds like the categories will be the split point — so we don't need to add any extra meta to patterns.
