### ISSUE TITLE
somethings going wrong with patterns 

### ISSUE THREAD

**Issue by sumitsinghwp** [WordPress/pattern-directory#539]
Hi,

my pattern was looking good. but the latest WP theme with something wrong. 

here link - https://wordpress.org/patterns/pattern/footer/

For more information see mentioned ss.
Old design - ![Footer-–-Block-Pattern-WordPress-org](https://user-images.githubusercontent.com/23701579/201175759-ebb752c2-055c-4adc-b331-c201a0f46296.png)
the broken current one - 
![Footer-–-Block-Pattern-WordPress-org (1)](https://user-images.githubusercontent.com/23701579/201176055-35e10d97-fc28-485d-b673-7e1eee333aa8.png)

**Comment by sumitsinghwp** [comment]
![Footer-–-Block-Pattern-WordPress-org (1)](https://user-images.githubusercontent.com/23701579/201176008-9fdade65-e86a-4a33-841d-e3440f9885f6.png)

**Comment by ryelle** [comment]
Do you know when this changed? [A few months ago](https://github.com/WordPress/pattern-directory/commit/07af84b67c700d4e0b5e33d629038be2ea70968a) the preview was updated to make the alignment more consistent with the core defaults. It looks like if you update your pattern to set the columns block to full width it will look correct again.
