### ISSUE TITLE
Show user information on the homepage

### ISSUE THREAD

**Issue by ryelle** [WordPress/pattern-directory#54]
If a user is logged in and has submitted patterns, the callout on the homepage should be updated to show relevant info:

<img width="417" alt="Screen Shot 2021-03-30 at 1 15 21 PM" src="https://user-images.githubusercontent.com/541093/113029042-fbf22780-9159-11eb-9781-1e397735e676.png">

**Comment by StevenDufresne** [comment]
**Questions**:

- ~~What status will the pattern have to be considered pending? Will it be custom?~~ Currently using `pending`.
- Do we have a ticket for the "View All" view? Will it be part of the MVP?
- We will need to write favoriting logic from scratch. 
  - Could we get this component in without the favorite count first?
  - As much as I like the favorite feature, I personally think it's low priority.

**Comment by StevenDufresne** [comment]
Closing this because there is an updated version in #160.
