### ISSUE TITLE
Latest posts block does not work on wordpress.org/patterns/new-pattern/

### ISSUE THREAD

**Issue by viralsampat-multidots** [WordPress/pattern-directory#555]
**Describe the bug**
Hello Team,
I am trying to create a new pattern using the Latest Posts block, But the block Post content settings setting is not working properly.
I want to display the full post, But it displays an error.
For a better understanding please see my video.

[Issue Video](https://share.cleanshot.com/gUD3FQbhgytuhGgH5jMG)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to WordPress.org
2. Open the "Pattern" page from the "Download & Extend" top nav menu
3. Go to "Create a new pattern"
4. Start Creating a pattern and select the "Latest Posts" block

**Expected behaviour**
I think that if the post has full content it will display when someone selects the "Full Content" option from the block setting.

**Screenshots**
<img width="1440" alt="CleanShot 2023-02-15 at 17 27 55@2x" src="https://user-images.githubusercontent.com/53076293/219021383-e68b23d1-e6b6-4695-8578-150551d898be.png">

**Desktop (please complete the following information):**
 - OS: [macOS 13.1]
 - Browser [Google Chrome ]
 - Version [109.0.5414.119 (Official Build) (arm64)]

Thanks,

**Comment by ryelle** [comment]
@viralsampat-multidots Could you try this again? I just tried adding a Latest Posts block and it worked for me.

**Comment by viralsampat-multidots** [comment]
Hello @ryelle 

Thank you for the update.

I have rechecked the above-mentioned issue from my end and still, and I am facing the same issue.

Here, I have provided a link where I am facing an issue with **"Latest Post"** block: [Latest Post Issue](https://wordpress.org/patterns/new-pattern/)

Also, I have prepared its video, Please see my attachment: [Issue](https://share.cleanshot.com/KlZwfw9MYCW7Yg80tfpL)

Thanks,

**Comment by ryelle** [comment]
Okay, I see the issue now, I didn't try "Full post".

Debugging notes: The problem is regular wporg users don't have access to the raw post content, so when the block tries to render, it triggers an `undefined` error. Maybe we can allow that? It would still be under the `view` context, not editable, so I don't think there would be any security issues.
