### ISSUE TITLE
Character seen after Call to Action heading in Patterns page

### ISSUE THREAD

**Issue by Joe4510** [WordPress/pattern-directory#559]
**Describe the bug**
Character seen after Call to Action heading in Patterns page - https://wordpress.org/patterns/categories/call-to-action/

**To Reproduce**
1. Go to 'https://wordpress.org/patterns/'
2. Click on 'Call to Action'
3. You can see a character after Call to Action

**Expected behavior**
There should not be any such characters. 

**Screenshots**
![image](https://user-images.githubusercontent.com/70191331/221782922-380b3c18-e112-47c5-a1db-4cee5f7a36ee.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : Google Chrome
 - Version: 110.0.5481.178

**Additional context**
I couldn't replicate the same issue in Mac.

**Comment by ryelle** [comment]
Thanks for reporting this! I've fixed it by updating the category name in the dashboard.
