### ISSUE TITLE
Search redirect causes Jetpack ES failure

### ISSUE THREAD

**Issue by pkevan** [WordPress/pattern-directory#563]
**Describe the bug**
Due to how the current redirect for search URLs `?s=[string]` => `/search/[string]` uses the `template_redirect` [action](https://github.com/WordPress/pattern-directory/blob/trunk/public_html/wp-content/themes/pattern-directory/functions.php#L19), it results in a failed ES query since the request is aborted upon the redirect.

This results in many warnings saying that the endpoint is failing, but we are just not waiting for the request to finish.

Example:

```
E_USER_WARNING: jetpack_search_abort - no_search_results_array - {"errors":{"invalid_search_api_response":["Invalid response from API - 400"]},
```

**To Reproduce**
1. Go to: https://wordpress.org/patterns/
2. Enter a search string into the box.
3. Observe that the request from the form is redirected (302).
4. See warning occur (doesn't happen 100% of the time, so may need to repeat.

**Expected behavior**
Either the search isn't redirected or the redirect occurs earlier before the search query is intercepted via `pre_get_posts`

**Comment by pkevan** [comment]
It might be best to hook in on `parse_request` since we're only really interested in forwarding the request string and not the query or query parameters.

**Comment by pkevan** [comment]
Seems like this didn't fix the issue unfortunately, or maybe there is another occurrence that is triggering the same behaviour.

**Comment by pkevan** [comment]
I *think* this might be due to the `locale` parameter, since it doesn't trigger the error when that parameter isn't present.

**Comment by pkevan** [comment]
So, the failures are actually expected when the ES query is failing (fallback to MYSQL). Upon further investigation it seems like the issue might be with the boost filters on local: https://github.com/WordPress/pattern-directory/blob/trunk/public_html/wp-content/plugins/pattern-directory/includes/search.php#L104-L130.

**Comment by ryelle** [comment]
I just tried searching in the patterns list table in wp-admin, and was redirected to `/search/…` on the frontend — is that related to #564 or a separate issue?

**Comment by pkevan** [comment]
> I just tried searching in the patterns list table in wp-admin, and was redirected to `/search/…` on the frontend — is that related to #564 or a separate issue?

Yes, looks related. I'll work on fixing that - it's probably due to having to remove the `is_search` conditional on the earlier hook.

**Comment by pkevan** [comment]
Reverted in https://github.com/WordPress/pattern-directory/pull/565
