### ISSUE TITLE
Many duplicate emails sent upon editing published pattern.

### ISSUE THREAD

**Issue by dd32** [WordPress/pattern-directory#569]
**Describe the bug**
A report has come in (via email) that a pattern author received many emails after editing two patterns.

> I wanted to let you know I edited 2 Block Patterns I initially published a long while ago and then got 52 email notifications after they were both re-published (re-approved).
> Looks like the links are mostly for translations and numbered versions of the two original patterns.

**To Reproduce**
1. Edit a pattern
2. Possibly get a million emails.

**Expected behavior**
Editing a published pattern should not trigger the "Congrats on your pattern being published!"

**Screenshots**
<img width="548" alt="Screenshot 2023-03-13 at 10 47 43 am" src="https://user-images.githubusercontent.com/767313/224585039-96cc8e17-ceee-4b3b-8465-3376003af7e6.png">

**Comment by ryelle** [comment]
When did these emails get sent? I think this is a duplicate of #560, which I fixed [on Friday](https://github.com/WordPress/pattern-directory/commit/83e043cb520872c2f43d60a4384b8721a0753d12).

>  Editing a published pattern should not trigger the "Congrats on your pattern being published!"

Editing a published pattern sets it back to pending, so it needs to be moderated again and that triggers the "congrats" email.

**Comment by dd32** [comment]
> When did these emails get sent? 

Looks like the email report was sent at `Fri, 10 Mar 2023 14:50:08 +0000` which is before your commit, so I expect you're right, this does seem to be a duplicate of #560.
