### ISSUE TITLE
Log changes to patterns

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/pattern-directory#57]
There are probably several reasons why we'd want to be able to audit changes made to a pattern. One is so we can see who removed a pattern from the directory, when they did it, and why, if they include a reason.

A log entry should have a date, user name, type of change, and an optional comment. It might look something like this:

| Date | User | Action | Comment |
| --- | --- | --- | --- |
| 2021-03-30 11:05:05 | matt | Submitted | |
| 2021-03-30 11:05:45 | patternbot | Flagged for manual review | Possible copyright issue |
| 2021-03-30 15:21:03 | admin | Approved | Looks ok |
| 2021-03-30 15:22:02 | someotheruser | Flagged for manual review | Inappropriate content |
| 2021-03-30 16:38:55 | admin | Removed | Content is inappropriate |

Log entries could be added both by automated processes (by "patternbot" or something) or by user-driven actions. In some cases the comment field could get populated automatically with pre-determined values. In other cases, like when a moderator is manually changing the status of a pattern, a textarea field should be available to add a reason, which would then get added to the log's comment field.

**Comment by coreymckrill** [comment]
Planning to use the Stream plugin for logging changes, so this is pending the merge of one of these PRs:

* https://github.com/xwp/stream/pull/1223
* https://github.com/xwp/stream/pull/1264
* https://github.com/xwp/stream/pull/1269

For the "adding a reason part" work is in progress on an ["Internal Notes" plugin](https://github.com/coreymckrill/wporg-internal-notes/).

Logging changes isn't critical for the initial launch, so I changed the milestone on this one to Pattern Creation instead.

**Comment by coreymckrill** [comment]
Development on the Stream plugin seems stalled, I haven't gotten any further responses on my PRs. I suspect we will need to write our own connector for post changes if we still want to use the plugin.

**Comment by kasparsd** [comment]
The https://github.com/xwp/stream/pull/1264 pull request has been merged and will be included in the next version of Stream.
