### ISSUE TITLE
Pattern author links on archives should include a trailing slash

### ISSUE THREAD

**Issue by jonoalderson** [WordPress/pattern-directory#574]
Links to pattern author pages on archives like https://wordpress.org/patterns/categories/call-to-action/ omit a trailing slash - resulting in an unnecessary redirect. This should be added. See screenshot.

![image](https://user-images.githubusercontent.com/11629607/233602706-25482874-687e-4e03-abb9-fd12be246e2b.png)

**Comment by ryelle** [comment]
Now that the theme is updated, this is no longer an issue.
