### ISSUE TITLE
Client-side pagination on archives should cut off at 50 for logged-out users

### ISSUE THREAD

**Issue by jonoalderson** [WordPress/pattern-directory#575]
Throughout the wp.org ecosystem, we limit pagination for logged-out users to 50 pages.

Server-side behaviour on pattern archives behaves correctly in this regard (visiting https://wordpress.org/patterns/page/51/ returns a 404 error), but the client-side interface (see https://wordpress.org/patterns/page/49/) contains links to _all_ pages.

The client-side options should be limited to a maximum of 50 results, so that it's consistent with the server-side behaviour.

**Comment by ryelle** [comment]
Now that the theme has been updated, it uses the default server-side behavior of cutting off at page 49.
