### ISSUE TITLE
"Login to report this pattern" link incorrect

### ISSUE THREAD

**Issue by jonoalderson** [WordPress/pattern-directory#576]
The "login to report this pattern" link on pattern pages (like https://wordpress.org/patterns/pattern/fullwidth-dark-banner-with-heading-top-left/) points to `/wp-login.php?redirect_to={{PATH-TO-PATTERN}}`.

This redirects to https://login.wordpress.org/?redirect_to=https%3A%2F%2Fwordpress.org%2F, and loses the return path in the process (as well as causing performance and SEO headaches).

To correct this, the link should be updated to `https://login.wordpress.org/?redirect_to={{PATH-TO-PATTERN}}`.

In the same change, a `rel="nofollow"` attribute should be added to the link.

**Comment by ryelle** [comment]
This link isn't used anymore, and the other places we use a "Log in to…" (for example, [Favorites](https://wordpress.org/patterns/favorites/)) use the correct link.
