### ISSUE TITLE
Empty archive pages (and author archives) should be noindex'd

### ISSUE THREAD

**Issue by jonoalderson** [WordPress/pattern-directory#577]
When an archive page contains zero results (such as https://wordpress.org/patterns/author/vrajeshthakkar/categories/text/), the `<head>` should include a meta robots tag with a `noindex, follow` directive.

This must be included in the server-side response, and not rely on client-side JavaScript.

**Comment by ryelle** [comment]
Now that the theme is not using a JS SPA anymore, I'm checking this out and it appears that authors & search results have `<meta name="robots" content="noindex,follow" />` regardless of empty result set. Is that correct?

**Comment by jonoalderson** [comment]
Super!
