### ISSUE TITLE
Wordpress pattern directory setting tab not working properly

### ISSUE THREAD

**Issue by pateljaymin29** [WordPress/pattern-directory#579]
Wordpress pattern directory screen setting tab first time show and close toggal functionality is working fine.
Then after I click second time setting tab is not working fine.

I have added small video
Link: [https://drive.google.com/file/d/1aFeew8kyzZl1Fa0kmPX6WqKzADwI37W8/view?usp=share_link](https://drive.google.com/file/d/1aFeew8kyzZl1Fa0kmPX6WqKzADwI37W8/view?usp=share_link)

**Comment by ryelle** [comment]
Thanks for the report! This bug is being tracked in https://github.com/WordPress/pattern-directory/issues/561, so I'm going to close this issue.
