### ISSUE TITLE
Archives: Switching categories does not update the site breadcrumbs

### ISSUE THREAD

**Issue by ryelle** [WordPress/pattern-directory#581]
The local site header on archive pages does not update when the filters are updated.

**To Reproduce**

1. Go to an archive page, e.g. ["Posts"](https://wordpress.org/patterns/categories/query/)
2. See the blue banner says "All Patterns / Category: Posts"
3. The context bar say "18 Posts patterns."
4. Click on any of the category filters to view a different category
5. The patterns update, and the context bar now reads "223 Gallery patterns."
6. The blue banner still says "All Patterns / Category: Posts"

**Screenshots**

<img width="1059" alt="Screenshot 2023-05-17 at 5 37 30 PM" src="https://github.com/WordPress/pattern-directory/assets/541093/db601c3f-e005-4e45-82a3-f88d4d5b92e5">

**Comment by richtabor** [comment]
Yea, should be resolved, though it almost seems a bit frivolous to have the category up top and right below it in the menu.

**Comment by ryelle** [comment]
I don't see us revisiting the layout of these pages until we get the redesign (except to add the community filters — I almost don't want to remove the context bar for this reason). In any case, when the redesign does roll out here, all these archive pages will have a standard header that should work with the filter bar.

**Comment by richtabor** [comment]
I'm not looking to revise the layout, just the minor filter work in #580. 

I really don't think we need the full context bar; but rather move that text to the right of the filters and take out the pattern category from the text. We don't need it three times up here (even if one of the three is wrong 🫣).

**Comment by ryelle** [comment]
This is working now that the theme is not a JS app 👍🏻
