### ISSUE TITLE
Pattern Dashboard Setting Panel Open Issue

### ISSUE THREAD

**Issue by ParinWordpress** [WordPress/pattern-directory#585]
**Describe the bug**
Pattern Dashboard Setting Panel Open Issue

**To Reproduce**
1. Go to 'Add New Pattern or Edit Pattern Dashboard' (https://wordpress.org/patterns/new-pattern/)
2. Click on 'Setting Icon' at the Top Right side (https://prnt.sc/Hv2Z8mXR4Mtc)
3. On the first click setting panel will appear, on the second click it will disappear.
4. If you click again a third time, then the panel will not appear again.

**Expected behavior**
Setting Icon click should be Toggle.

**Screenshots**
When the panel is closed, at that time icon should be white (https://prnt.sc/4q-c7VBcioOF) instead of black (https://prnt.sc/dAyofJFM8h2O) which is based on its behavior.

**Desktop (please complete the following information):**
 - OS: window 10 pro
 - Browser [Chrome, Mozilla Firefox]

**Additional context**
Setting click should behave Toggle.

**Comment by ryelle** [comment]
Thanks for the report! This bug is being tracked in https://github.com/WordPress/pattern-directory/issues/561, you can watch that issue for updates.
