### ISSUE TITLE
CORS Error when Adding Blocks in Pattern Creator

### ISSUE THREAD

**Issue by benniledl** [WordPress/pattern-directory#586]
Hello,
I have some problems with the pattern creator https://wordpress.org/patterns/new-pattern/
When I click on the + to add a block, and search for something like "Cover" the Icon's or Previews for the Blocks are not loading correctly. On the JavaScript Console there is a CORS error showing up for this domain: https://pd.w.org/

**To Reproduce**
1. Create a new Pattern
2. Click on + to add a Block
3. Search "Cover"

**Desktop (please complete the following information):**
 - Windows 11
 - Firefox (latest)

**Comment by ryelle** [comment]
The block inserter has changed since this issue was created, and the block previews no longer show up in the pattern creator. I can't replicate this issue.
