### ISSUE TITLE
New Pattern - The editor has encountered an unexpected error.

### ISSUE THREAD

**Issue by huzaifaalmesbah** [WordPress/pattern-directory#589]
If we attempt to create a new pattern on the WordPress.org website, you may have encountered an unexpected error with the editor. This issue seems to be affecting the pattern creation process, hindering contributors from seamlessly utilizing this feature.

https://github.com/WordPress/pattern-directory/assets/63150399/5a5d538c-14ea-4a5a-a8f9-3497fbd29486

**Comment by benniledl** [comment]
I got the same issue

**Comment by huzaifaalmesbah** [comment]
good work
