### ISSUE TITLE
Patterns Default Curation Curated(Core) To Community

### ISSUE THREAD

**Issue by huzaifaalmesbah** [WordPress/pattern-directory#590]
I believe selecting the default community is a favorable choice due to its abundance of patterns. However, it lacks a significant number of core elements.
<img width="1414" alt="Screenshot 2023-06-17 at 12 51 01 PM" src="https://github.com/WordPress/pattern-directory/assets/63150399/5c93578f-f40a-4a4e-9fb9-b2855ef493e9">

**Comment by ryelle** [comment]
It was decided in #580 to default the patterns to the curated view. This view mirrors the patterns available in core by default, so visitors can see an array of ready-to-use patterns. This probably won't change until the site is redesigned.
