### ISSUE TITLE
Not Able to Create a new pattern

### ISSUE THREAD

**Issue by shail-mehta** [WordPress/pattern-directory#591]
**Describe the bug**
- Create New Pattern is not working it gives error

**To Reproduce**
- Login in WordPress Account 
- Go to Patterns (https://wordpress.org/patterns/)
- Click on Create New Pattern (https://wordpress.org/patterns/new-pattern/)
- Its giving an error(The editor has encountered an unexpected error)

Ref: https://drive.google.com/file/d/1c7ziAbRjt-evSyo5OmfkEh0tyWizsuSe/view 

**Expected behavior**
- User should able to create new pattern

**Screenshots**
![create-pattern](https://github.com/WordPress/pattern-directory/assets/22027190/af716ec5-8fa6-4f9d-a946-df1a74464ee7)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 114.0.5735.199

**Comment by ryelle** [comment]
This was already reported in #589. I'm going to close this issue, but you can subscribe to the other issue to be notified when it's fixed.
