### ISSUE TITLE
Pattern Directory Links Hover Issue

### ISSUE THREAD

**Issue by huzaifaalmesbah** [WordPress/pattern-directory#592]
**Describe the bug**
Favorites, Create a new pattern, My patterns links already apply text-decoration: underline; but I saw pattern-directory all pages when hover  effect apply text-decoration and normally text-decoration: none; 

**To Reproduce**
1. Go to 'https://wordpress.org/patterns/'
2. See this

**Expected behavior**
normally text-decoration: none; 
when hover apply text-decoration: underline; 

**Screenshots**
<img width="1111" alt="hover effect" src="https://github.com/WordPress/pattern-directory/assets/63150399/a89f27e2-b2de-4645-a4f3-ba66d57abeed">

**Comment by huzaifaalmesbah** [comment]
check @ryelle

**Comment by pitamdey** [comment]
Hi Team, we can add the following CSS to fix the issue
```
.site-link:hover {
text-decoration: none;
}
```

**Comment by pitamdey** [comment]
Hi Team, we can add the following CSS to fix the issue
`.site-link:hover {
text-decoration: none;
}`
Thanks
