### ISSUE TITLE
Pagination issue on patterns 

### ISSUE THREAD

**Issue by sumitsinghwp** [WordPress/pattern-directory#595]
**Describe the bug**

**To Reproduce**
1. Go to Open this link - https://wordpress.org/patterns/categories/call-to-action/
2. Click on the **All** tab filter option
3. Scroll down to see only 6 patterns list
4. See the error

**Expected behavior**
it should show a total of 18 as per default pagination.

**Screenshots**

https://github.com/WordPress/pattern-directory/assets/23701579/ecbf92b5-3f36-4316-9e21-6976207f6a84

**Desktop (please complete the following information):**
 - Ubuntu 20.04.6 LTS
 - Browser [ chrome ]
 - Intel® Core™ i5-9400F CPU @ 2.90GHz × 6

**Comment by huzaifaalmesbah** [comment]
yes. face this same issue.

**Comment by ryelle** [comment]
The Pattern Directory theme has recently been updated, so I don't think this is an issue anymore. I see patterns in [the "Call to action" category](https://wordpress.org/patterns/categories/call-to-action/?curation=all). If you're still having trouble, leave a comment to reopen the issue.
