### ISSUE TITLE
I am not able to replce media on existing image

### ISSUE THREAD

**Issue by sumitsinghwp** [WordPress/pattern-directory#597]
**Describe the bug**

**To Reproduce**
1. Go to https://wordpress.org/patterns/new-pattern/ link
2. Click on Add a new block "Media & Text"
3. Add an image from the media then try to replace it. it will not work to replace things.
4. See the error

**Expected behavior**
It should be able to update the image.

**Screenshots**
![New-Pattern-WordPress-org](https://github.com/WordPress/pattern-directory/assets/23701579/a7c52c96-637e-444a-a918-87c67da48178)

**Desktop (please complete the following information):**
Ubuntu 20.04.6 LTS
Browser [ chrome ]
Intel® Core™ i5-9400F CPU @ 2.90GHz × 6

**Comment by ryelle** [comment]
The replace button works now, so I'm going to close this issue.
