### ISSUE TITLE
Pattern submission details

### ISSUE THREAD

**Issue by ryelle** [WordPress/pattern-directory#60]
When a user goes to submit a pattern, they will get a modal with 3 "steps" (2 + done).

![Step-1](https://user-images.githubusercontent.com/541093/117467609-d6f39000-af21-11eb-98a2-c0c39743f0b3.png)

![Step-2](https://user-images.githubusercontent.com/541093/117467610-d6f39000-af21-11eb-939f-0077d26d8322.png)

![Done](https://user-images.githubusercontent.com/541093/117467607-d65af980-af21-11eb-92c9-a919a3e28c28.png)

It should be pre-filled with any meta information they entered in the pattern sidebar. Clicking Publish will call the API to save the post. Tracking validation & post-save is in #36

**Comment by StevenDufresne** [comment]
@ryelle I'll take this one. I'll build it in the existing creator and make it easy to move over should we go make the change you mention here: https://github.com/WordPress/pattern-directory/issues/59#issuecomment-827174674

**Comment by shaunandrews** [comment]
Here's the SVG shapes for the background: [SVG Shapes.zip](https://github.com/WordPress/pattern-directory/files/6517294/SVG.Shapes.zip)

I've added a little "Required" label that I think it helpful. Here's an updated GIF of the steps:

![Pattern Publish Modal](https://user-images.githubusercontent.com/191598/119029965-4d0ee280-b977-11eb-8fd3-6b51dee4fdf1.gif)
