### ISSUE TITLE
Pattern About Page Spacing - Mobile View

### ISSUE THREAD

**Issue by BenjaminZekavica** [WordPress/pattern-directory#600]
Bug Spacing on Mobile: 
[Link to Page](https://wordpress.org/patterns/about/)

**Info:** If it's ok, I will fix it. But I need premission to edit this page. I no found this page in the repository templates. 

![padding](https://github.com/WordPress/pattern-directory/assets/15845265/24a04524-05a4-489d-8257-db223ff21f21)

**Comment by ryelle** [comment]
This has been fixed by updating the page content to add some padding:

![Screen Shot 2023-08-17 at 13 41 00](https://github.com/WordPress/pattern-directory/assets/541093/f209cc7c-3b34-418c-b1b8-2dde79a3eb30)
