### ISSUE TITLE
The text within the select option (dropdown) is slightly truncate

### ISSUE THREAD

**Issue by shail-mehta** [WordPress/pattern-directory#603]
### The text within the select option is slightly cut (Line height issue in select option)

**To Reproduce**
1. Go to this page (https://wordpress.org/patterns/?curation=community&orderby=favorite_count)
2. you will able to see text is slightly cut (https://prnt.sc/l0YNs-vycthq)
3. Go to  https://wordpress.org/patterns/my-patterns/draft/?orderby=favorite_count page, you will able to see same text cut issue. (https://prnt.sc/zKHtQxjwkrWB)

**Expected Behavior**
- https://prnt.sc/p05GXvLc4Th4
- https://prnt.sc/h7JqxiVINVFA

**Desktop**
 - OS: Windows
 - Browser : Chrome

**Comment by shail-mehta** [comment]
PR : https://github.com/WordPress/pattern-directory/pull/605

**Comment by ryelle** [comment]
The theme has been updated, so this is no longer an issue.
