### ISSUE TITLE
Pattern editor font family differs from pattern preview

### ISSUE THREAD

**Issue by webmandesign** [WordPress/pattern-directory#607]
**Describe the bug**

There is a mismatch between pattern editor and pattern preview, rendering the editor unusable:

The pattern editor does not set any font family so browser default font is used, but the pattern preview uses `-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif` font family.

**Expected behavior**
Both editor and preview font family should be the same.

**Screenshots**

Editor view:

![wporg-patterns-editor](https://github.com/WordPress/pattern-directory/assets/2456735/3e66e918-65ee-40fa-9401-4bf303b9bdd7)

Preview:

![wporg-patterns-preview](https://github.com/WordPress/pattern-directory/assets/2456735/d7e29211-ff29-4d7d-acf7-cd1060d40a22)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 117

**Comment by ryelle** [comment]
The theme providing the styles for the pattern creator was updated, and this no longer appears to be a problem.
