### ISSUE TITLE
Patterns categories terms translations rendering when there are apostrophes

### ISSUE THREAD

**Issue by lidialab** [WordPress/pattern-directory#610]
**Describe the bug**
In the Patterns categories terms translations the character « ' » (apostrophe) is rendered with the HTML entity: `&#039;` .

**To Reproduce**
1. Go to https://it.wordpress.org/patterns/categories/call-to-action/ or to https://ca.wordpress.org/patterns/categories/call-to-action/
2. See the errors in three different points (see attached screenshot)

**Expected behavior**
Translations with apostrophes are generally not a problem.
I expected to see the apostrophe.

**Screenshots**
![2023-10-17_11h37_39](https://github.com/WordPress/pattern-directory/assets/12560308/8e19f880-6936-4599-a83f-cc71fb8fcfed)

**Desktop (please complete the following information):**
 - OS: Win 11 Pro (22H2)
 - Browser Firefox 118.0.2 64bit
(Same problem in Google chrome on an Android mobile.)

**Additional info**
I'm trying to see if some workarounds work in the meanwhile such as to use `&#039;` in the Italian translation instead of «'», but it tooks 24~36 hours to the change to be visible, in case it works for the Italian please go to https://ca.wordpress.org/patterns/categories/call-to-action/ to see the same errors in their Rosetta site.  Thanks.

**Comment by lidialab** [comment]
In the previous comment I meant "...such as to use `&#039` in the Italian translation instead of «'»...".

Anyway I just reverted the [Italian translation](https://translate.wordpress.org/projects/meta/pattern-directory/it/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=15093455&sort%5Bby%5D=translation_date_added&sort%5Bhow%5D=asc&historypage) from "Invito all`&#039;`azione" to "Invito all'azione", because `&#039;` (workaround test) didn't work to display an apostrophe either. 

Thanks.

**Comment by ryelle** [comment]
This is fixed now that the theme has been updated.
