### ISSUE TITLE
Proposal: Don't ship core patterns to WordPress sites in the "Featured" category

### ISSUE THREAD

**Issue by richtabor** [WordPress/pattern-directory#612]
I'm proposing that we do not ship core patterns to WordPress sites within the "Featured" category. Instead, patterns "featured" on a site should be very close to the design, look, feel, and intention of the site — not generic patterns shipped to everyone. 

It's fine if these core patterns are available within specific categories, but "Featured" feels like an area where a theme should put its best work forward; and core pattern's can't be that. 

### Visual 

 I've attached a screen recording below of the Featured category in Twenty Twenty-Four. It looks great, as the theme has opted to place a number of compelling patterns in the category. But as you scroll, you'll notice the quality dropping quite drastically. The colors, look, feel, and general vibe doesnt match up with the high-quality patterns provided by the theme. 

https://github.com/WordPress/pattern-directory/assets/1813435/b0ddd2b1-9b65-456d-bdd4-1e81dd1215d9

**Comment by richtabor** [comment]
How do we move this forward? I think we need to be more intentional about letting themes decide what patterns are feature, especially as we lean into the next default theme, Twenty Twenty-Five, which will surface many patterns. 

I wouldn't want patterns that don't serve the purpose, style, or vibe of the theme "featured" in the Inserter.

**Comment by ryelle** [comment]
I just replied to #587 with this:

> One thing I might be able to do is removed featured from the API response sent to WP sites, if you know you will never want pattern-directory patterns in the featured category (which would include patterns loaded via slugs in theme.json). Then "featured" on wporg/patterns and "featured" on local WP sites would be fully separate things, and remote patterns would never be in featured on local sites.

Which I think may fulfill this request? The pattern directory (wporg/patterns) would still have a Featured category, and those patterns would still be sent to local WP sites, but they would not appear in the local sites' "Featured" category.

**Comment by richtabor** [comment]
Yes, I think that will work too. I still think we audit what patterns we're serving (#587)—but notably, none will be featured in the Inserter.
