### ISSUE TITLE
Redesign: The "More from this author" shows up even if there are none

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/pattern-directory#636]
**Describe the bug**
Visit an account with only 1 pattern: https://wordpress.org/patterns/pattern/card-with-polaroid-photo-shape/. 

Notice that we still show the "More from this author" section even though there aren't any.

## Screenshot
<img width="1917" alt="Screenshot 2024-03-12 at 1 03 26 PM" src="https://github.com/WordPress/pattern-directory/assets/1657336/8a724332-4b44-4df2-a809-ed562b52088c">

**Comment by ryelle** [comment]
There is no easy/GB-native way to do this, unfortunately (there's [a issue requesting it](https://github.com/WordPress/gutenberg/issues/53316)).

@StevenDufresne Do you think it's worth creating our own `wporg/query-has-results` wrapper (like the issue suggests), or finding another workaround?

**Comment by ryelle** [comment]
We'll go with creating `wporg/query-has-results` block, and using that here.
