### ISSUE TITLE
Change "Curated" filter to defaulted sort.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/pattern-directory#638]
**Describe the bug**

The "Curated" filter was added via #580 as a way to ensure high-quality patterns are presented to users first. However, it has introduced 2 unfortunate side effects:
- It hides patterns from contributors
- It makes it look like there are not many patterns in the directory.
  - If you click through the categories, you will only see (Featured - 4, Posts - 2, Text - 8 ) 

~~The data does suggest that users are not finding the filter often.~~ [See comment](https://github.com/WordPress/pattern-directory/issues/638#issuecomment-2017106405).

Can we make curated (+ newest) as the default sort instead of a separate defaulted dropdown?

cc @richtabor

**Comment by ryelle** [comment]
> Can we make curated (+ newest) as the default sort

Do you mean default everywhere, or just on the homepage?

The "curated flag" is a boolean (a taxonomy term), not really a sort value. We could maybe hack it with custom SQL like we do for [the locale preference](https://github.com/WordPress/pattern-directory/blob/c3478b345002fe5a7421abdc9f9bc3c34a5adad6/public_html/wp-content/plugins/pattern-directory/includes/pattern-post-type.php#L799), but I'm not sure if that would even work to match a taxonomy term.

I think this would also change up the filter options, though I guess talking through that depends on whether you meant just on the homepage or "all patterns" & archives too.

**Comment by StevenDufresne** [comment]
I'm thinking that it should be a "sort" whereever relevant, which I assume is everywhere except author views?

<img width="983" alt="Screenshot 2024-03-13 at 9 48 17 AM" src="https://github.com/WordPress/pattern-directory/assets/1657336/478b826a-ad51-4fbb-a167-3f7e98811cca">

I'm not familiar with the backend, but technicals aside, we would bubble up all the curated patterns to the top of the list relevant to the query. 

I think that's more logical than having "curated" vs "community". Curated patterns are made by the wporg account which are provided through Gutenberg which is a representative of the community. 

I also think this will remove the "community" reference which gets complicated when we think about the theme/plugin categorizations.

**Comment by ryelle** [comment]
That makes sense. I think the technical details might be an issue, but worth checking out.

Any objections or other thoughts @WordPress/meta-design? This would merge the curated & sort dropdowns into one.

**Comment by jasmussen** [comment]
I recall an older design that had Curated / Community as much more prominent tabs, making it all the more easy to swap betwen them. However I would not change the default, nor include "newest" or "popular" in the default sorting method. Perhaps as a result of the lack of any acceptance criteria, review, or guidelines, or simply the lack of grouping or bundling or better sorting mechanisms, the current archive of community patterns is not yet in a good place to elevate in prominence. I would address all those mechanisms before we change such defaults.

**Comment by fcoveram** [comment]
To @StevenDufresne's points

Hiding patterns is not an unfortunate side effect but an expected consequence of the curation. I don't recall the context of this request, but if the data says users struggle with finding patterns, then worth revisiting the decisions. However, the following feels strange

> Curated patterns are made by the wporg account which are provided through Gutenberg which is a representative of the community.

The curation conveys the idea of selected patterns from the community rather than patterns created by a single user; WPorg, in this case.

Blending sorts with a category filter might confuse users as these actions belong to different types. I am optimistic that the new design (#635) has a better layout where hero section is cleaner and the white space before the results grid is bigger and therefore, users will afford these filters more easily.

On the other hand, the small amount of patterns (Featured - 4, Posts - 2, Text - 8) might be a picture of the early stage of the directory. It can increase its size if the curation process becomes more intense, but I'm unaware of this works.

**Comment by jasmussen** [comment]
All of those decisions are a result of the lack of guidelines, good sorting, good categories, and missing design tools in the block editor at the time of the inception. As we work to address those, we can indeed improve the curation quite a bit.

But for now, the WP.org user represents not just a single user, but WordPress itself, meaning those are the patterns that are bundled/directly available in the block editor. 

As noted, I don't think we should change that until we change the other mechanisms, including pattern bundles, etc, lest the problem that was meant to be solved with this change simply re-emerges.

**Comment by richtabor** [comment]
> The data does suggest that users are not finding the filter often.

What data? 

> All of those decisions are a result of the lack of guidelines, good sorting, good categories, and missing design tools in the block editor at the time of the inception. As we work to address those, we can indeed improve the curation quite a bit.

100%.

Perhaps we can explore adding other ways to see all patterns, like linking the pattern count to all results. We probably wouldn't need the kinda awkward "View all patterns" link at the bottom either. 

![CleanShot 2024-03-22 at 16 41 39](https://github.com/WordPress/pattern-directory/assets/1813435/91625ed5-8e8d-4b53-b953-7b1f6e35fec5)

**Comment by StevenDufresne** [comment]
> What data?

I looked at anonymous GA pageview data, but on further inspection, I made a mistake. Unlike other wp.org directories, the current directory is a Single Page Application, which means pageview data is pretty meaningless since we don't send back updates from the JS interactions. 👍

**Comment by ryelle** [comment]
I'm going to leave this issue open to keep the discussion of improving the curation/moderation/guidelines, but take it out of the current redesign iteration — we'll leave "curation" as a separate filter from sort for now.

**Comment by ryelle** [comment]
I know I said I'd leave this open for discussion, but I think discussing changes to the moderation/guidelines should happen in a make/themes (or meta) p2 post, not here, so that the community is aware/involved. That doesn't need to be tied to larger updates, if someone feels strongly about improving the guidelines, go for it 🙂

**Comment by StevenDufresne** [comment]
For me, this isn't related to how we curate or the choice to promote curated patterns. This is related to the User experience in the current directory related to how this is implemented.

**Comment by fcoveram** [comment]
I shared [an idea](https://github.com/WordPress/wporg-mu-plugins/discussions/603#discussioncomment-9164633) in [wporg-mu-plugins#603](https://github.com/WordPress/wporg-mu-plugins/discussions/603) that proposes a new way of showing these actions.
