### ISSUE TITLE
Breadcrumbs: rename Block Pattern Directory to Patterns

### ISSUE THREAD

**Issue by jasmussen** [WordPress/pattern-directory#640]
Followup to #633. This title should also just say "Patterns", not "Block Pattern Directory":

![Screenshot 2024-03-14 at 10 43 23](https://github.com/WordPress/pattern-directory/assets/1204802/5822fab2-9740-4e6d-8afb-8724b2655bbf)

**Comment by ryelle** [comment]
This was done in https://github.com/WordPress/pattern-directory/commit/2a7f19312ae05d28848c0a5f96d4ca3e262ee4e7.
