### ISSUE TITLE
Block theme: Reorganize single pattern details

### ISSUE THREAD

**Issue by ryelle** [WordPress/pattern-directory#644]
Pattern title, copy button, and favorite button at the top.

Add "Tags:" label before tags.

Update background color on "More from this author" section.

(preview toggles handled in another issue)

![Pattern details](https://github.com/WordPress/pattern-directory/assets/541093/7a8e701c-7d17-45a3-900b-e83e61b9947f)

**Comment by fcoveram** [comment]
It would be great if you can test how aligning "More from this creator" and creator's name in their text baseline. If that takes big effort, the vertical alignment of all elements is sufficient.
