### ISSUE TITLE
Style of "View all patterns" link

### ISSUE THREAD

**Issue by fcoveram** [WordPress/pattern-directory#647]
**Description**
The "View all patterns" link at the end of the homepage could reuse the same style as in Showcase. This adds more consistency and stands out the action.

**Screenshots**
![Screenshot of homepage demo version. "View all patterns" link is focused](https://github.com/WordPress/pattern-directory/assets/895819/524df1eb-a12e-4b06-94aa-bf57b8ec77f9)

**Comment by ryelle** [comment]
Showcase style:

<img width="1486" alt="Screenshot 2024-03-25 at 12 57 28 PM" src="https://github.com/WordPress/pattern-directory/assets/541093/562c43ae-67b2-4496-a317-2df356940a5c">


@fcoveram Do you just want the link + arrow style, or add the dots too?

**Comment by fcoveram** [comment]
With everything, dots included. Thanks

**Comment by ryelle** [comment]
The text "View all patterns" is just long enough with the more narrow width of the patterns grid that it wraps to a second line. I don't think that looks very good, plus it takes up a lot of space. Should we shrink the font down to "Heading 1" size? It's still a good callout size, compared to the rest of the content on the page.

| CTA | Heading 1 |
|---|---|
| ![Screen Shot 2024-03-27 at 14 28 28](https://github.com/WordPress/pattern-directory/assets/541093/8c8cd26d-6616-4935-98b8-b64999343a28) | ![Screen Shot 2024-03-27 at 14 29 10](https://github.com/WordPress/pattern-directory/assets/541093/10784c2d-b43d-4df6-bc64-6a04609f1dc9) |

**Comment by fcoveram** [comment]
That's a good idea. Let's go with it. Thanks @ryelle
