### ISSUE TITLE
Block Theme: Filters: Default state and clear action in Sort

### ISSUE THREAD

**Issue by fcoveram** [WordPress/pattern-directory#648]
**Describe the bug**
I noticed an odd interaction while sorting on the homepage. The default sort is by popularity, but when clicking on it, I'm able to clear the action and set an "empty" sort. This flow was thought to be for applying filters, and it seems this case inherits the same logic.

I am drawn to always keep one sort enabled, as in radio, where users can not deselect. "Apply" would still exist as it confirms the change, but "clear" is no longer needed.

**To Reproduce**
1. Go to the homepage
2. Click on "Sort: Popular"
3. Click on "Clear" and then on "Apply" to confirm the change
4. See how the label shows "Sort" only.

**Video recording**

https://github.com/WordPress/pattern-directory/assets/895819/4d831032-4e9b-4ea1-8e40-dce2d09659b8

**Comment by ryelle** [comment]
I've labelled this as blocked as the update here will require a change to the shared component in wporg-mu-plugins first. Once the design is finalized and that issue is completed, I can make whatever remaining changes are necessary here (though it will probably inherit everything automatically).

**Comment by fcoveram** [comment]
Perfect. Thanks Kelly

**Comment by fcoveram** [comment]
Here is an idea I've been polishing for the single- and multiple-selection flows

Figma file: [WordPress.org Navigation](https://www.figma.com/file/SQwX90pGxS0XlNTEyNhDRE/WordPress.org-Navigation?type=design&node-id=2-1965&mode=design&t=vqRm8SmEnAJmUkCc-0)

## Single selection

![Single selection flow](https://github.com/WordPress/pattern-directory/assets/895819/d133a05e-7c20-4473-afd4-21dd6df1b21e)

Design: ["Single selection" section](https://www.figma.com/file/SQwX90pGxS0XlNTEyNhDRE/WordPress.org-Navigation?type=design&node-id=1006-756&mode=design&t=vqRm8SmEnAJmUkCc-11) in Figma file

## Multiple selection

![Multiple selection flow](https://github.com/WordPress/pattern-directory/assets/895819/0d80dbd4-95c7-48f6-8997-65c72451d1a1)

Design: ["Multiple selection" section](https://www.figma.com/file/SQwX90pGxS0XlNTEyNhDRE/WordPress.org-Navigation?type=design&node-id=1005-595&mode=design&t=vqRm8SmEnAJmUkCc-11) in Figma file.

**Comment by ryelle** [comment]
@fcoveram Thanks! I've created [the single select update issue in wporg-mu-plugins](https://github.com/WordPress/wporg-mu-plugins/issues/594).

I'm not sure when looking at the multiple selection version what exactly the changes are, could you create an issue in wporg-mu-plugins clearly marking what needs to change from what's on production?

**Comment by fcoveram** [comment]
Sure. The change is mostly visual where cross icon is now replaced by the check one on the left.

**Comment by fcoveram** [comment]
Apologies. I didn't have time to create the issue 🙏  I will do it today.

**Comment by fcoveram** [comment]
So sorry for arriving late. I created [this issue](https://github.com/WordPress/wporg-mu-plugins/issues/601) suggesting two style changes.
