### ISSUE TITLE
Block Theme: My patterns button stuck against footer.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/pattern-directory#651]
**Describe the bug**
If you don't have any patterns pending reviews or drafts, there is no spacing below the button.

**To Reproduce**

_Have no pending patterns under review_

1. Go to https://wordpress.org/patterns/my-patterns/?status=pending
2. Notice the button doesn't have padding.

**Expected behavior**
- Add padding
- We can probably change that button to a link, seems like overkill? Soft opinion.

**Screenshots**

<img width="1036" alt="Screenshot 2024-04-02 at 8 25 36 AM" src="https://github.com/WordPress/pattern-directory/assets/1657336/01551428-8be4-4441-a492-b1039d8e9cad">

**Comment by ryelle** [comment]
I added space under the section, but have left the button a button to match the design.
