### ISSUE TITLE
Block theme: Update favorite interactions.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/pattern-directory#653]
**Describe the bug**
It isn't clear that you can click on the favorite button on the grid view.

Can we:
- Add a hover state
- Update the cursor when hovering.

**Screenshots**

<img src="https://github.com/WordPress/pattern-directory/assets/1657336/0146c5cf-efee-479e-9624-13adb803f429" width="400" >

**Comment by ryelle** [comment]
I only added the pointer cursor, haven't changed anything on hover. Switching the cursor is probably enough to make it clear it's clickable. Anything else we would probably need design input on, since there was no specific hover state here.
