### ISSUE TITLE
Block Theme: Single pattern header layout feels awkward.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/pattern-directory#654]
**Describe the bug**
When viewing a specific pattern, the layout feels a bit chaotic and disordered. Would we consider using the theme directory layout?

**Screenshots**
**Current**
| Mobile | Desktop |
|--------|--------|
| <img width="544" alt="Screenshot 2024-04-02 at 12 02 50 PM" src="https://github.com/WordPress/pattern-directory/assets/1657336/eeec6701-8708-4adc-99a3-0bd2f2ba31ce"> | <img width="1361" alt="Screenshot 2024-04-02 at 12 02 37 PM" src="https://github.com/WordPress/pattern-directory/assets/1657336/2e022ce5-34f5-4970-b4f0-1d9271fadbe5"> | 

**Idea**

I've quickly moved some container around using DevTools for a basic example.

| Theme Directory | Quick dev tools experiment |
|--------|--------|
| <img  alt="Screenshot 2024-04-02 at 12 19 39 PM" src="https://github.com/WordPress/pattern-directory/assets/1657336/3f0dcda8-6081-400a-9150-e2331b254b9b"> | ![wordpress org_patterns_pattern_event_ (2)](https://github.com/WordPress/pattern-directory/assets/1657336/3e7597fa-4d08-430e-b731-b57af7b9b964) |

**Comment by ryelle** [comment]
This seems like the kind of thing we could think about for the next redesign, but would be too big of a change for the simple "refresh" iteration.

I'm going to close this issue, I think it would be better posted on figma or p2 when the designers start up the redesigns again.

**Comment by StevenDufresne** [comment]
I don't know that this is complete but agree that my suggestion would be a bigger change. I still feel this layout is more awkward since removing the colored border adds some visual predictability to the layout.

| Before | After |
|--------|--------|
| <img width="1384" alt="Screenshot 2024-04-04 at 8 57 32 AM" src="https://github.com/WordPress/pattern-directory/assets/1657336/ed0c94e8-6cd3-4f12-8167-1c668e810967"> | <img width="1387" alt="Screenshot 2024-04-04 at 8 57 43 AM" src="https://github.com/WordPress/pattern-directory/assets/1657336/d538b934-4a3f-4ec2-8d59-c8e7bb5a08c8"> |
