### ISSUE TITLE
Update the opengraph image for social media previews

### ISSUE THREAD

**Issue by ryelle** [WordPress/pattern-directory#659]
Currently, the image used on social media is this:

![social-image](https://github.com/WordPress/pattern-directory/assets/541093/5b4c6ef1-c7aa-4fce-baed-a2facc5b1b02)

We should update this before the redesign rolls out. cc @WordPress/meta-design

**Comment by jasmussen** [comment]
Two quick options:

![Screenshot 2024-04-12 at 09 11 56](https://github.com/WordPress/pattern-directory/assets/1204802/277a4ca5-0e89-48d8-8547-52f9055b08c0)

![Screenshot 2024-04-12 at 09 14 48](https://github.com/WordPress/pattern-directory/assets/1204802/c52ac91d-da2c-4a88-8ead-a2e1bd8611e6)

The syntax of the latter is one we can hopefully also use with the theme and plugin directories.

PNG exports of those two.

[Archive.zip](https://github.com/WordPress/pattern-directory/files/14955208/Archive.zip)

**Comment by ryelle** [comment]
I like the second one, I think it will have more context for someone just scrolling by on social media.
