### ISSUE TITLE
Text Encoding Error in Catalan Pattern Directory menu label

### ISSUE THREAD

**Issue by marcarmengou** [WordPress/pattern-directory#660]
The "Call to action" option is translated as "Crida a l'acció" in Catalan. The text is correctly translated on translate.wp.org but `Crida a l&#039;acció` appears in the menu. Here (https://ca.wordpress.org/patterns/)

I attach two images where you can see how it is correctly translated, and how the text appears in the category menu.

![1](https://github.com/WordPress/pattern-directory/assets/83702259/79ada403-341d-4b5b-8fa7-af6092664208)
![2](https://github.com/WordPress/pattern-directory/assets/83702259/d7c2680b-3c25-4bb6-a6a6-984ddff507fa)

**Comment by ryelle** [comment]
Thanks for the report. This is fixed on the new theme, so I'm going to close this issue. You can preview the new theme with the "Preview this theme" link in the admin bar, or by using this link: https://ca.wordpress.org/patterns/?new-theme=1

<img width="1249" alt="Screenshot 2024-04-12 at 10 20 50 AM" src="https://github.com/WordPress/pattern-directory/assets/541093/6c047ae6-cd2e-4dca-90e7-89ff61e0da35">
