### ISSUE TITLE
Block theme: Link pattern author name to archive

### ISSUE THREAD

**Issue by ndiego** [WordPress/pattern-directory#671]
In the new block theme, it's a bit hard to find all patterns created by a certain author. One improvement would be to link the author's name in the heading of the single pattern template. The author's name in the "More from this designer" section is already linked and looks exactly the same as the name in the header. 

<img width="1513" alt="image" src="https://github.com/WordPress/pattern-directory/assets/4832319/cd678173-0cf7-4d3c-a29d-345dd2430159">

**Comment by ndiego** [comment]
cc @ryelle

**Comment by ryelle** [comment]
That was intentional, to avoid duplicate links on the page. Plus, the top "author name" always shows up, while the second does not if the user has no patterns (so it's not linked, because the viewer is already on the only pattern they have).

See discussion on https://github.com/WordPress/pattern-directory/issues/670

**Comment by ndiego** [comment]
Hmm, I see now. It just feels weird to me that both look exactly the same, but one is a link, and the other is not. Thoughts @jasmussen?

**Comment by ryelle** [comment]
That's one reason to keep underlining links 😁   

But seriously, @jasmussen did suggest that we could remove it from the "More from…" line if necessary, so we could do that and switch the top "author name" to be a link.

**Comment by ndiego** [comment]
> But seriously, @jasmussen did suggest that we could remove it from the "More from…" line if necessary, so we could do that and switch the top "author name" to be a link.

I think this would work well.

**Comment by jasmussen** [comment]
That seems the simplest thing to try.
