### ISSUE TITLE
Block theme: Standardize star color for favorites

### ISSUE THREAD

**Issue by ndiego** [WordPress/pattern-directory#675]
This is very minor, but I noticed that the star color is different in a few spots. It would be nice to standardize this. Thoughts @WordPress/meta-design?

| Pattern Grid (`-wp--preset--color--charcoal-4`) | Single Pattern (`currentColor`) |
|-|-|
|<img width="504" alt="image" src="https://github.com/WordPress/pattern-directory/assets/4832319/5b1e47e0-222d-419d-bb8e-faefd4dd4619">|<img width="413" alt="image" src="https://github.com/WordPress/pattern-directory/assets/4832319/c2e401c2-016f-44eb-acd4-fd3a8d88cf76">|

Whatever color is decided, it should be the same one used in the Plugin Directory if the heart icon is switched to a star, as noted in https://github.com/WordPress/wordpress.org/issues/265 cc @StevenDufresne

**Comment by ryelle** [comment]
Looks like the single pattern one should also be charcoal-4 according to figma, I'll fix that.

**Comment by ryelle** [comment]
As to whether this should be used for plugins, that's probably a question for a different issue.
