### ISSUE TITLE
Add tooltip about some blocks not triggering "Upload external images"

### ISSUE THREAD

**Issue by pedddro** [WordPress/pattern-directory#676]
I've added this issue https://github.com/WordPress/gutenberg/issues/60323 and think many people don't know they will be using external images that could potentially break.

**Comment by ryelle** [comment]
Patterns in the directory should not be using images from external sources (excluding those from Openverse). You can report those patterns with the "Report this pattern" button and adding a note about the image in the details.

**Comment by pedddro** [comment]
@ryelle The patterns are hosted on wp.org but they can break if someone imports them and does not host as many blocks currently don't trigger the "Upload external images".

**Comment by ryelle** [comment]
Okay, I think that's something that will need to be fixed in Gutenberg, if core blocks are not working as expected.

**Comment by pedddro** [comment]
Yes, that's why I suggested warning people until it gets sorted. Using 3rd-party images in this particular case it's really bad.
