### ISSUE TITLE
Block theme: Change default filtering to "Curated" by default

### ISSUE THREAD

**Issue by ryelle** [WordPress/pattern-directory#677]
The current pattern directory defaults to showing "Curated" patterns, patterns from the WordPress.org user. This filter persists across all tabs. E.g.

* Go to pattern directory, note how the "All" tab says "Curated".
* Then click "Posts", and note that the curation still defaults to "Curated". That particular tab has 2 curated patterns at the moment.

The refresh changes this behavior, so only the "All" tab shows curated patterns. E.g. 

* Go to [the refreshed pattern directory](https://wordpress.org/patterns/?new-theme=1), note how the "All" tab says "Curated". 
* Then click "Posts", and note the filter changes to "All". 

The behavior should be the same in the new, since it's mainly a refresh, and then we can discuss a change in defaults separately.

**Comment by ryelle** [comment]
@jasmussen I've changed this locally and will push shortly, but there's an awkward behavior now where the "View all patterns ->" link (going to the archive) no longer shows _all_ patterns, and in fact repeats most of the patterns you've just seen.

| Homepage | Archive page |
|---|---|
| ![Screen Shot 2024-04-17 at 12 21 50-fullpage](https://github.com/WordPress/pattern-directory/assets/541093/bbdb3f27-ae8c-4e41-ac82-95ce93c618ed) | ![Screen Shot 2024-04-17 at 12 22 05-fullpage](https://github.com/WordPress/pattern-directory/assets/541093/8330cd47-bbd2-4696-8350-677bab041617) |

**Comment by jasmussen** [comment]
Thanks for the work, and appreciate the screenshots.

That is awkward, yes. I wonder, was there any context for the addition of the "View all patterns" CTA on the landing, vs. just showing pagination right there? Would that be an option?

**Comment by ryelle** [comment]
Initially this grid was meant to be the curated section, and then the Archive showed the full listing of patterns, like from Showcase. This was done to set the stage for other featured sections in the future, like pattern bundles, if/when those are built.

**Comment by ndiego** [comment]
Perhaps the "All" on the homepage should not be selected. Then when you click "All" or "View all patterns", you are taken to the archive page. 

<img width="997" alt="image" src="https://github.com/WordPress/pattern-directory/assets/4832319/64d7aca5-7ac2-4498-a97a-e05735a8c918">

**Comment by ryelle** [comment]
Would that still default to "curated"?

**Comment by ndiego** [comment]
> Would that still default to "curated"?

Yeah, I think so for this iteration. That keeps parity with the current site.

**Comment by ryelle** [comment]
I'm not sure if that helps — the issue is still that clicking the "View all patterns" link in the footer will show you all the same patterns.

**Comment by ndiego** [comment]
One possible thought would be to include the "curated" and "community" in the pattern number:

<img width="1310" alt="image" src="https://github.com/WordPress/pattern-directory/assets/4832319/ce47128d-d030-41f2-9f5e-b49e51fead04">

That makes it a bit clearer what you are viewing. The "All" section would just be "XX patterns"

**Comment by ryelle** [comment]
Oh, that made me realize— there's also the issue that the query total is different now. On the homepage, it's the count of all patterns ("1,875 patterns") but on the archive page it's just the count for the current query, i.e., curated patterns ("43 patterns"). I suppose adding "curated" would fix _that_ issue.

> The "All" section would just be "XX patterns"

We don't really have an "All" section anymore — you can technically select "All" out of the filter options dropdown, but now clicking "All" will take you to curated patterns.

**Comment by ryelle** [comment]
We could change the "View all patterns" link to use `https://wordpress.org/patterns/archives/?curation=all` — so the top category links would all use "curated" as default, but if you've specifically clicked that link it will show all…? But then if you click any other category once on that page it flips back to curated, so maybe not.

**Comment by ryelle** [comment]
We could also remove that link entirely? Let users navigate using the top row of categories only.

**Comment by ndiego** [comment]
> We could also remove that link entirely? Let users navigate using the top row of categories only.

I'm inclined to keep the "All" in the categories row, at least for now, since it's on the current site.

**Comment by ryelle** [comment]
> I'm inclined to keep the "All" in the categories row, at least for now, since it's on the current site.

Yes, that would stay in place. I'm just talking about the "View all patterns" link above the footer on the homepage. 

<img width="402" alt="Screenshot 2024-04-17 at 3 42 32 PM" src="https://github.com/WordPress/pattern-directory/assets/541093/dc321cc1-257a-46d1-9331-6994853b6805">

**Comment by jasmussen** [comment]
[This older design](https://www.figma.com/file/bz4qs4jZCkqvQzPH2fmX6C/Pattern-Directory?type=design&node-id=5293%3A7856&mode=design&t=sl2EfZCOkfY5l2f6-1) doesn't include the "View all patterns" link at the bottom, essentially dives right into the full paginated list of all patterns, just as the current directory does, and the tabs simply filter that curation into subcategories.

I think there are a lot of opportunities for improvements across filters, categories, improving guildelines for submission, better author profiles, pattern bundles, endless good ideas to explore. But many of those are larger, and could use good and broad input and consideration. In the mean time, it would be good to find the simplest path forward, in case that means removing the "view all patterns" link, and just showing the pagination directly, as is the case on the existing version.

**Comment by ryelle** [comment]
"Just showing the pagination" is more complicated than it sounds, because the new theme was set up to use a separate page for the homepage. I realize I didn't complete [the thought here](https://github.com/WordPress/pattern-directory/issues/677#issuecomment-2061971011), but that was intended to explain that we can't use pagination here, because the home and archive are two entirely separate queries/pages.

I'm trying to switch that now to see if we can bring in pagination, but I need to remove all references to the archives page, which is harder than a simple swap.

**Comment by ryelle** [comment]
Archives page is officially gone now. I think I've checked all the paths that could have lead there, so there should be no dead ends. The homepage has pagination on it, and all views default to only showing curated patterns (except author archives).

**Comment by jasmussen** [comment]
> "Just showing the pagination" is more complicated than it sounds

Apologies, I should've learned by now to never use the term "just" in software development. This was my bad.
