### ISSUE TITLE
Patterns have a different viewport width than the default in core

### ISSUE THREAD

**Issue by richtabor** [WordPress/pattern-directory#683]
**Describe the bug**

The default viewport width for patterns from the directory is a different value than the default in core. 

The visual below is of the same pattern, one from the directory and the other duplicated from it. This test is with using the [Assembler theme](https://github.com/Automattic/themes/pull/7765), but this occurs for any pattern served from the directory. 

The scale of patterns served from the directory are zoomed in further, with a smaller viewport width, than the same patterns from on the site. 

![CleanShot 2024-04-23 at 10 38 25](https://github.com/WordPress/pattern-directory/assets/1813435/33fc617a-7a63-4ff6-aa8e-2fd1e627d163)

**To Reproduce**
1. Add any of the curated patterns from the editor.
2. Create a pattern from the same exact pattern.
3. Compare the previews of both patterns. 

**Expected behavior**
The patterns should have the same default scaling, regardless of source. 

**Additional visual**

Here's an example using a core pattern that is already served to WordPress sites: 

![CleanShot 2024-04-23 at 10 57 04](https://github.com/WordPress/pattern-directory/assets/1813435/e0bc2b60-257b-45f3-ad4e-24af910ed48e)
![CleanShot 2024-04-23 at 10 56 08](https://github.com/WordPress/pattern-directory/assets/1813435/700ac321-fb0b-4e81-9015-187c853a0a12)

**Comment by richtabor** [comment]
While it'd be nice to have to declare viewport width for patterns (https://github.com/WordPress/pattern-directory/issues/614), we need a consistent default first.

**Comment by ryelle** [comment]
I believe the one supplied by the pattern directory is 800px, which did match GB at some point. What is the current gutenberg default?

**Comment by richtabor** [comment]
Looks like 1200 ([source](https://github.com/WordPress/gutenberg/blob/006107338d284b9d88f3ecf901dad4e41eca86dc/packages/block-editor/src/components/block-preview/index.js#L27)).

**Comment by richtabor** [comment]
Is this something we can fix?

**Comment by richtabor** [comment]
We're about to kick up Twenty Twenty Five, which will likely use the directory to house patterns—but I consider this a blocker, as the patterns don't look great coming in with a different viewport width than any included in the theme.
