### ISSUE TITLE
My Patterns page pending list not properly show.

### ISSUE THREAD

**Issue by trushaamin** [WordPress/pattern-directory#690]
**Describe the bug**

**To Reproduce**
1. Go to 'wordpress.org'
2. Click on the 'My Pattern button'
3. Scroll down to the top side navigation bar and click on the My Pattern button after so many options are available ALL, Pending Review, Draft, etc..in the All option shows all pending patterns but the pending review does not show all listings pattern'

**Expected behavior**
After logging into WordPress.org, we navigated to the "My Patterns" option and located the "My Patterns" button at the top. Select that option and show the many options like the All, Draft, Pending Review, and Published Buttons added.
The Pending Review section does not show all of the videos that are shown as pending in the 'All' view.

**Screenshots**

https://github.com/WordPress/pattern-directory/assets/169051711/4a53309c-9222-417f-914a-df9606e9b007

**Desktop (please complete the following information):**
 - OS: iOS
- Browser chrome, safari
- Version macOS 10.15.7

**Additional context**
The All Pending Pattern listing does not show properly in the Pending Review option.

**Comment by ryelle** [comment]
I wasn't able to reproduce this, and I haven't seen any other reports. It was probably a caching issue, but if it happens again, leave a comment here and I'll reopen the issue.
