### ISSUE TITLE
Translations - Core and community patterns are not separated

### ISSUE THREAD

**Issue by timse201** [WordPress/pattern-directory#693]
**Describe the bug**
It seems that core patterns and community patterns are not separated internally. Therefore the assignment of rights for community patterns does not work. GTEs can grant permissions to translate core and/or community patterns.

If you look at the following URL, the URL contains a core term.

https://translate.wordpress.org/projects/patterns/core/de/formal/?filters%5Bterm%5D=https%3A%2F%2Fwordpress.org%2Fpatterns%2Fpattern%2Fyogger%2F&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated_or_rejected_or_changesrequested_or_old&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

**To Reproduce**
We have granted community rights and the feedback was that it does not work.

**Comment by dd32** [comment]
This is currently expected, we don't have the pattern translations split by Core/Community, and the `Community` translation  project is marked as Inactive (Which means not-used).

See #444 for splitting it.

<img width="472" alt="Screenshot 2024-05-22 at 1 44 04 PM" src="https://github.com/WordPress/pattern-directory/assets/767313/fb1c4308-7ab9-4379-822e-6d25cb332e60">

**Comment by timse201** [comment]
Thank you for clarification
