### ISSUE TITLE
My friend created new pattern and he is not able to edit

### ISSUE THREAD

**Issue by sumitsinghwp** [WordPress/pattern-directory#699]
**Describe the bug**

**To Reproduce**
1. Go to '[Patterns](https://wordpress.org/patterns/my-patterns/)'
2. iopend this pattern https://wordpress.org/patterns/my-patterns/' to edit./
3. I can see the blank white screen page
5. See error in added quick recording

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser chrome
 - Version 22

**Additional context**
here quick recording.

https://github.com/WordPress/pattern-directory/assets/23701579/fa0f33cd-df15-48cb-99be-d5aadc7045bc

**Comment by ryelle** [comment]
There was an issue a few days ago with the pattern creator not loading, but this has been fixed (in #700). Are you able to edit your patterns now?

If you are still having trouble, can you share which pattern it is (the edit link or a link to the pattern itself)?
