### ISSUE TITLE
Theme: "Report this pattern" button and form

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/pattern-directory#80]
This issue is pulling out the **Front End UI** section of #61, and building off the work done in #77.

When viewing a single pattern in the directory, there should be a "Report this pattern" button to click in the case that the pattern is problematic for some reason. Clicking the button should bring up a modal similar to this mockup:

<img width="414" alt="image-15" src="https://user-images.githubusercontent.com/916023/113040728-fa226700-914d-11eb-97fc-aff27c38b0f7.png">

I would suggest that instead of a textarea that only applies to the "Other" category, the textarea should always be present beneath the radio button group, labeled "Details", and perhaps always be a required input. It seems that no matter which reason is chosen for reporting a pattern, more context will be necessary for a moderator to effectively review the report.

**Further requirements:**

* The options in the radio button group for "Please choose a reason" will be drawn from terms in the `wporg-pattern-flag-reason` taxonomy.
* When the form in the modal is submitted, it should send a `POST` request to `/wp-json/wp/v2/wporg-pattern-flag`. The request must have the following parameters:
  * `parent` The ID of the pattern post
  * `wporg-pattern-flag-reason` The ID of the "reason" taxonomy term
  * `excerpt` The user-input string of text providing details about the problem with the pattern
* The API will send back an error in some cases, which we may want to surface to the end user. Some examples of relevant errors:
  * `You have already flagged this pattern.`
  * `Flags cannot be submitted for this pattern.` (if it is not published, for example)
  * `You must be logged in to submit a flag.`
* Perhaps the "Report this pattern" button shouldn't be shown unless the user is logged in? Or perhaps if they aren't logged in, the modal should instead show an explanatory message and a link to log in that will then bring them back to the pattern page afterwards?
* Ideally the "Report this pattern" button would be aware if the current user has already submitted a flag for the pattern, and would show with a checkmark or something, as well as being unclickable.

**Comment by StevenDufresne** [comment]
I'll look at this.
