### ISSUE TITLE
Should core patterns live in the directory?

### ISSUE THREAD

**Issue by tellyworth** [WordPress/pattern-directory#81]
For consistency of search, we could include all core patterns in the pattern directory, and return them as part of API search results. That would eliminate the need to separately search core patterns locally on the user's site, and enable us to consistently apply search ranking and filtering across both third party and core patterns.

Patterns registered by a plugin or theme would still need to be searched locally though. Unless we implemented discovery and indexing of patterns found in the plugin and theme directories (which wouldn't cover plugins or themes hosted elsewhere). It might make sense for plugin and theme patterns to be grouped separately from others though - I could see it being useful to group each plugin's patterns together.

**Comment by ryelle** [comment]
Core patterns have already been loaded into wp.org/patterns 👍🏻  (I even have [a draft PR into gutenberg](https://github.com/WordPress/gutenberg/pull/28800) to transparently replace the existing patterns with these API results, but then we started talking about redesigning the editor search…)

@iandunn started a discussion about how to combine locally-registered patterns with the API patterns/how to display those over on the gutenberg repo: https://github.com/WordPress/gutenberg/issues/28248
