### ISSUE TITLE
Build the pattern submission tool.

### ISSUE THREAD

**Issue by tellyworth** [WordPress/pattern-directory#9]
Patterns should be submitted from a purpose-built front-end form based on Gutenberg.

Tentative assumptions:
* Any logged-in user should be able to submit a pattern.
* It will be necessary to preview and edit a pattern during the submission process.
* Submitted patterns will need to pass some kind of validation, curation, moderation process before being published to the world.
* Users might expect to be able to see and use patterns they have submitted even if they're not yet published.
* Users will need to provide some metadata with their patterns, such as description and language.
* Copying or "forking" an existing pattern will probably be a common flow.
* Translations and i18n will need to be solved.

This is an umbrella task, specific issues should be created as needed.

**Comment by MichaelArestad** [comment]
I created a few issues for the above:

Pattern submission tool: https://github.com/WordPress/pattern-directory/issues/14
Login flow: https://github.com/WordPress/pattern-directory/issues/15
Submitted patterns page: https://github.com/WordPress/pattern-directory/issues/16
Forking a pattern: https://github.com/WordPress/pattern-directory/issues/17
Pattern submission modal: https://github.com/WordPress/pattern-directory/issues/18

**Comment by ryelle** [comment]
I think every task here is covered by an existing issue, and this "parent issue" can be closed because the project is being tracked in https://github.com/WordPress/pattern-directory/projects/1 — I prefer to keep issues to actionable tasks that can be closed, but @tellyworth if you'd rather have this issue you can reopen it.
