### ISSUE TITLE
Creator: Pattern Creator Welcome Guide

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/pattern-directory#96]
In order to help users understand the process of creating and uploading patterns, we should provide them with information when they load the pattern creator for the first time.

**Designs**

![](https://d.pr/i/sWkZNZ.png)

**Comment by shaunandrews** [comment]
Here's an SVG export of the illustrations and the geometric backgrounds:

[Archive.zip](https://github.com/WordPress/pattern-directory/files/6442419/Archive.zip)

**Comment by StevenDufresne** [comment]
How particular are we that the SVG backgrounds match the designs? The exports are not identical and/or very tricky to get to match. The triangles and squares are particularly out of sorts and will require a lot of manual tweaking to get them to match. It's probably easier to simplify the SVGs.

| Diamond |  Squares |Triangles |
| --- | --- | --- |
| ![](https://d.pr/i/eisHN6.png) | ![](https://d.pr/i/re218P.png)   | ![](https://d.pr/i/I1TkJN.png) | 
| Extra squares | Nothing appears aligned | Not sure what is going on here |

**Comment by shaunandrews** [comment]
Ah, my bad. I should have double-checked before uploading. I forgot to outline the shapes, and I've adjusted the export frame so we don't have to worry about positioning.

[This ZIP should be better.](https://github.com/WordPress/pattern-directory/files/6454928/Archive.zip)

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/191598/117724033-2dc2c900-b1b1-11eb-8936-f9eebd205641.png">
