### ISSUE TITLE
Coordinate Nginx caching for API

### ISSUE THREAD

**Issue by iandunn** [WordPress/pattern-directory#99]
Once the API is stable, we'll need to ask Systems to cache it, to avoid performance/stability issues.

Draft at https://make.wordpress.org/systems/wp-admin/post.php?post=1788&action=edit _(old, may need to be updated)_

**Comment by iandunn** [comment]
Converting this to an issue to make sure it doesn't get missed.

FYI @ryelle , @StevenDufresne , @tellyworth

**Comment by ryelle** [comment]
What does "stable" mean in this context?

**Comment by iandunn** [comment]
I was mostly thinking of all the endpoints being there, parameter names/types having their final names, etc

----

xref https://make.wordpress.org/systems/2021/05/18/patterns-api-maybe-cache-direct-to-proper-upstreams/

cc @dd32

**Comment by iandunn** [comment]
This is done

xref https://make.wordpress.org/systems/2021/05/18/patterns-api-maybe-cache-direct-to-proper-upstreams/#comment-1846
